### ISSUE TITLE
Lazy `initialValues`

### ISSUE THREAD

**Issue by bca-rh** [formium/formik#1011]
### Current Behavior

The `initialValues` prop passed in to Formik must be evaluated on every re-render, even though it's typically only necessary on the first render.

### Desired Behavior

A lazy way to specify `initialValues` would be excellent.

### Suggested Solution

A `getInitialValues()` prop would solve this problem for us.

### Who does this impact? Who is this for?

This should improve performance for any app where computing `initialValues` is relatively expensive.

### Describe alternatives you've considered

We currently compute & memoize the value of `initialValues` at the start of the app, but this is not ideal.

### Additional context

The initial values for our form state is derived from query params on the URL, which are expensive to access and parse on each render.

**Comment by maddhruv** [comment]
Closing due to long inactivity
