### ISSUE TITLE
Head 0 will be trimmed in a type number field

### ISSUE THREAD

**Issue by wxywj1005** [formium/formik#1012]
### Current Behavior
It may return trimmed value In a type number field when  validating.
```js 
<Field
  name="veriCode"
  type="number"
  component={this.renderCodeInput}
  label={i18n.t(lk.FILL_VERICODE)}
/>
```
<img width="313" alt="screen shot 2018-10-19 at 2 17 07 pm" src="https://user-images.githubusercontent.com/17468968/47200876-59d78e00-d3aa-11e8-81bc-92cf563cb63d.png">

```js 
const validate = values => {
  let errors = { _error: {} }
  const { veriCode } = values    // It will be 11111
  if (!veriCode) {
    errors.veriCode = i18n.t(lk.SIGNUP_ERROR_VERICODE)
  } else if (!/^\d{6}$/.test(`${veriCode}`)) { 
    errors.veriCode = i18n.t(lk.SIGNUP_ERROR_VERICODE_1)
  }
  return errors
}
```

### Expected behavior
can get '011111' from the values when entering '011111' into a type number field

### Additional context
moving form from redux-from may encounter this problem

### environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.1
| React            | 16.3
| Operating System |osx

**Comment by Intregrisist** [comment]
Possible that you are missing the`pattern="[0-9]*"` in the input tag?

**Comment by wxywj1005** [comment]
I filled the missing pattern but it still doesn't work.
thanks @Intregrisist .

**Comment by maddhruv** [comment]
Closing due to long inactivity
