### ISSUE TITLE
[docs] Improve props documentation

### ISSUE THREAD

**Issue by nicolas-besnard** [formium/formik#1036]
## 📖 Documentation

I'd like to create a PR to add documentation on props. For instance, `FieldProps` is mentioned in several places in the documentation, but I wasn't able to find a central place to find the values of this props.

I'd like to be able to find the values quickly. Should I add a new section in the documentation after "API references" ?

**Comment by jaredpalmer** [comment]
Pin

**Comment by maddhruv** [comment]
Hey @nicolas-besnard thanks for raising this issue and concern, yeah, I can understand the trouble when you are not able to locate certain definitions and references.

Feel 🤗 welcomed to raise a PR and write the required docs.

I would suggest you to add the section on the `Field` page itself - https://formik.org/docs/api/field
