### ISSUE TITLE
Hooks Rewrite

### ISSUE THREAD

**Issue by jaredpalmer** [formium/formik#1046]
```jsx
import React, {
  useContext,
  useState,
  createContext,
  createElement,
} from 'react';

const FormikContext = createContext(null);

export function Formik({
  initialValues,
  validate,
  onSubmit,
  validateOnBlur = true,
  validateOnChange = true,
  ...props
}) {
  const [values, updateValues] = useState(initialValues);
  const [errors, updateErrors] = useState({});
  const [touched, updateTouched] = useState({});
  const [submitAttemptCount, updateSubmitAttemptCount] = useState(0);
  const [isSubmitting, updateIsSubmitting] = useState(false);
  const [isValidating, updateIsValidating] = useState(false);

  function validateForm(vals = values) {
    updateIsValidating(true);
    return Promise.resolve(validate ? validate(vals) : {})
      .then(x => x, e => e)
      .then(e => {
        // return or take a callback?
        updateErrors(e);
        updateIsValidating(false);
      });
  }

  function getFieldProps(name, type) {
    return {
      value:
        type === 'radio' || type === 'checkbox'
          ? undefined // React uses checked={} for these inputs
          : values[name],
      onChange(e) {
        e.persist();
        updateValues(
          prevValues => ({ ...prevValues, [name]: e.target.value }),
          () => {
            if (validateOnChange && validate) {
              validateForm();
            }
          }
        );
      },
      onBlur() {
        updateTouched(
          prevTouched => ({ ...prevTouched, [name]: true }),
          () => {
            if (validateOnChange && validate) {
              validateForm();
            }
          }
        );
      },
    };
  }

  async function submitForm() {
    updateTouched(setNestedObjectValues(values, true));
    updateIsSubmitting(true);
    updateSubmitAttemptCount(prev => prev++);
    try {
      await validateForm();
      const errors = await onSubmit(values);
      if (errors) {
        updateErrors(errors);
      }
      updateIsSubmitting(false);
    } catch (errors) {
      updateErrors(errors);
      updateIsSubmitting(false);
    }
  }

  function handleSubmit(e) {
    e.preventDefault();
    submitForm();
  }

  const ctx = {
    values,
    updateValues,
    errors,
    updateErrors,
    touched,
    updateTouched,
    submitAttemptCount,
    updateSubmitAttemptCount,
    isSubmitting,
    updateIsSubmitting,
    isValidating,
    validateOnChange,
    validateOnBlur,
    getFieldProps,
    handleSubmit,
    submitForm,
  };

  return (
    <FormikContext.Provider value={ctx}>
      {props.children}
    </FormikContext.Provider>
  );
}

export function Form(props) {
  const formik = useContext(FormikContext);
  return <form onSubmit={formik.handleSubmit} {...props} />;
}

export function Debug(props) {
  const formik = useContext(FormikContext);
  console.log({ formik });
  return null;
}

// Backwards compatible Field
export function Field({
  component = 'input',
  render,
  children,
  name,
  ...props
}) {
  const { getFieldProps } = useContext(FormikContext);

  const fieldProps = {
    ...getFieldProps(name, props.type),
    ...props,
  };

  if (children && typeof children === 'function') {
    return children(fieldProps);
  }

  if (render && typeof render === 'function') {
    return render(fieldProps);
  }

  return createElement(component, fieldProps, children);
}

/** @private is the given object an Object? */
export const isObject = obj => obj !== null && typeof obj === 'object';

/**
 * Recursively a set the same value for all keys and arrays nested object, cloning
 * @param object
 * @param value
 * @param visited
 * @param response
 */
export function setNestedObjectValues(
  object,
  value,
  visited = new WeakMap(),
  response = {}
): T {
  for (let k of Object.keys(object)) {
    const val = object[k];
    if (isObject(val)) {
      if (!visited.get(val)) {
        visited.set(val, true);
        // In order to keep array values consistent for both dot path  and
        // bracket syntax, we need to check if this is an array so that
        // this will output  { friends: [true] } and not { friends: { "0": true } }
        response[k] = Array.isArray(val) ? [] : {};
        setNestedObjectValues(val, value, visited, response[k]);
      }
    } else {
      response[k] = value;
    }
  }

  return response;
}
```

**Comment by prichodko** [comment]
Love it.

I think we can simplify it even more by exposing `useField()` and removing one layer. Potentially getting rid of Field completely in the future.

**Comment by weyert** [comment]
I think the `Field` is mainly there for backward compatibility as in to ease the migration to the use of hooks?

**Comment by jaredpalmer** [comment]
Correct.

**Comment by danpantry** [comment]
Is it not a bit early to be migrating to this? :P

**Comment by jaredpalmer** [comment]
Nope. In fact it actually comes at a great time. We can use hooks to avoid breaking changes while we perfect some stuff.

**Comment by ConnorBryan** [comment]
This is fantastic and a perfect example to show others the power of hooks!

**Comment by mohsinulhaq** [comment]
is this all of Formik? :O

**Comment by weyert** [comment]
How would you progress from this? Do you want to use this in v2 of Formik? 
Wouldn't hooks make it easier to implement features like setFieldWarnings?

**Comment by klis87** [comment]
@jaredpalmer at the same time we could add `schemaValidation` to `ctx`, which would solve #797 feature requests

**Comment by jaredpalmer** [comment]
@klis87 Agree. I think we will also implement the PR where only one key of the schema is executed.

**Comment by klis87** [comment]
@jaredpalmer you mean to handle #1007 issue?

**Comment by weyert** [comment]
How would you extend Formik when using hooks? Would that be possible?

**Comment by tgriesser** [comment]
Sharing this here as well as #1063 incase anyone is interested, took a stab at rewriting Formik using hooks yesterday and this is what I ended up with:

https://gist.github.com/tgriesser/fdd08da075fec80328792319606c76e5

As you can see it uses a lot of refs rather than state, I found this to work the best w/ Formik's imperative API, so you can set a field and submit the form in the same event handler without having stale values. 

Probably not going to take the time to make it into a formal PR since I'm changing some of the APIs a bit for my own purposes, so if anyone wants to use this as a starting point for a PR feel free!

**Comment by jaredpalmer** [comment]
See #1063

**Comment by tannerlinsley** [comment]
I think one of the problems with using a hook like `useField` instead of the `Field` get's problematic with arrays and nested values.  The reason `Field` and `FieldArray` work great is because they can be dynamically and conditionally rendered (something you cannot do with hooks without breaking the "rules of hooks"). 

Don't get me wrong, I would love a hook-only API, but I ran into this problem myself and am curious how to move beyond it.

**Comment by TrySound** [comment]
@tannerlinsley Render a input conditionally. `useField` not necessary to be used in all branches.

**Comment by tannerlinsley** [comment]
Right, that makes sense for top level fields, but what about for a nested field like `friends[3].hobbies[2]`?

**Comment by TrySound** [comment]
How they this currently works? I never used fields api.

**Comment by tannerlinsley** [comment]
I believe right now you would need to use the `FieldArray` component: https://jaredpalmer.com/formik/docs/api/fieldarray

**Comment by klis87** [comment]
Personally I think that hooks are perfect alternative for HOCs or render props, but they are not replacement for components. For example you can avoid nesting with hooks in contrast to composed hocs or chained render props.  I am not sure why would we give up components like Field and FieldArray and substitute them with hooks. Nice candidates for hooks are `Formik` and `connect` for instance, but field definitely not, at least not as a replacement, but alternative API is someone for some reason would like to use sth like `useField`.

I really want to still do things like <Field name="myField" component={MyCustomInput} {...otherProps} /> Imagine a form with 20+ fields. With JSX it is super readible, but using 20+ `useField` hooks and having some many variables? It would be sooo messy

**Comment by klis87** [comment]
> @tannerlinsley Render any input conditionally. `useField` not necessary to be used in all branches.

It should be really taken with care, as order of hooks matters, if for some cases you won't use a hook and for another you will, it won't work as expected https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

**Comment by TrySound** [comment]
@klis87 Performance will not suffer unless you use hundreds of fields in your form. But this still will require splitting with components to keep code maintainable and the problem becomes fixed.

**Comment by diegohaz** [comment]
I'm trying to design a hook-only API for [Reakit](https://github.com/reakit/reakit). After weeks of experimenting, it doesn't seem to be feasible.

If you want to render fields conditionally, the way to go is to create a new component:
```jsx
function Field() {
  const field = useField();
  return <input {...field} />
}

function Form() {
  return (
    <form>
      {condition && <Field />}
    </form>
  );
}
```
Also, as far as I know, things like `FastField` can't be properly implemented with only hooks unless you return elements from them. 

The approach I'm taking for now is to expose both `useField` and `<Field />` (just examples, I'm actually working on other components) and let the user decide what to use.

**Comment by klis87** [comment]
@TrySound so you mean that instead of writing a custom input component which then is passed to `component` prop of `Field` component, which then has all necessary state passed by Formik automatically (`field` and `form`), we could just create some custom inputs which would get necessary state by `useField` for instance, and then we could use this component directly in our forms without necessity of using `<Field />` If that is so, that could work, but as @diegohaz, I am wondering what about `FastField` then, mamy PureComponent/memo will suffice as an alternative?

**Comment by jaredpalmer** [comment]
FastField cannot be implement with hooks because React.memo does not compose. Put differently, there really isn’t an equivalent to sCU for hooks. Also, without anyway to have a second argument to setState or emitEffect in a reducer. Top level validation has to be much simpler....just put it in useEffect and that’s it. This has less than desirable impacts on how people current rely on setFieldValue and setFieldTouched. At this point, I’m not sure a full hooks rewrite will be worth it. Aside from being hip and cool, Formik will not work the same way. That being said, introducing a useField would be a very quick win.

**Comment by wkrueger** [comment]
Formik inspired article (not by me)
https://upmostly.com/tutorials/using-custom-react-hooks-simplify-forms/

**Comment by tz5514** [comment]
Any update for hooks? Thanks!

**Comment by mbrowne** [comment]
It seems like a `useField()` hook would come with another limitation as well: you wouldn't be able to use it directly inside `Formik` or `Form`, but only in a separate child component, because otherwise the context wouldn't have been created yet. Or is there some way around that?

**Comment by Evanion** [comment]
Here is my TS revision of the code, Still some issues that I need to sort out, but it works fairly well.
https://gist.github.com/Evanion/a8d69ae963fed2924f0b4ef394f61515

**Comment by johnrom** [comment]
@evanion v2 is already implemented, but you can submit TS PRs to `master` if you'd like. With revisions to types. There are already PRs open with type revisions you may want to piggy back off of.

#1336 (v1 example of strongly typed fields, in the middle of re-implementing in v2)
#1786
