### ISSUE TITLE
validationSchema nested object using type:number unexpected behavior

### ISSUE THREAD

**Issue by mzachariadis** [formium/formik#1125]
## 🐛 Bug report

Hello all, 

I am using validationSchema and I want to validate a nested object that has a property with type number. When I try to submit the form leaving this field empty, I get an error saying that this field must be a number. 

I forked the codesandbox example from #1091 and I changed the social.facebook to number, so you can see the unexpected behavior. This is the updated version https://codesandbox.io/s/w7r17nnxzk

**Comment by jaredpalmer** [comment]
All HTML inputs are strings. Formik does not convert or transform these for you, you have to do that on your own prior to storing them in Formik state. This is a design decision.

**Comment by mzachariadis** [comment]
The same thisn

Is it possible to combine

**Comment by huangbin30** [comment]
I get the problem.

In validateYupSchema, nested empty strings aren't converted to undefined.

`
  for (let k in values) {
    if (values.hasOwnProperty(k)) {
      const key = String(k);
      validateData[key] = values[key] !== '' ? values[key] : undefined;
    }
  }
`

**Comment by maddhruv** [comment]
Closing due to long inactivity
