### ISSUE TITLE
defaultProps of a Wrapped Component aren't show in handleSubmit

### ISSUE THREAD

**Issue by aaronnunez95** [formium/formik#1170]
I am using withFormik HOC and set the option *handleSubmit*,then in the callback I access to the formikBag and get props of the WrappedComponent, why it doesn't show WrappedComponent's defaultProps?

**Comment by bellerus** [comment]
Getting the same.

**Comment by jaredpalmer** [comment]
The default props are just booleans . What’s the use case?

**Comment by maddhruv** [comment]
Closing due to long inactivity
