### ISSUE TITLE
Request for an example of dependant and dynamic selects

### ISSUE THREAD

**Issue by realtebo** [formium/formik#1205]
## 📖 Documentation
I've a request for documentation: an example of 2 selects, where the first one throw a refetch and a repopulate of the second.

Imagine a simple case where select 1 has provinces and select 2 the postal code.

I was looking for a 'global' change handler in the form or in the formik, but probably I'm doing wrong something because I'cannot console.log() anything when first combo changes

**Comment by billdybas** [comment]
Here's an [example](https://codesandbox.io/s/8zy3o1p9p9) where one select's value changes another select's options. Note, the options are static, but you can imagine dynamically fetching them.

**Comment by maddhruv** [comment]
Closing due to long inactivity
