### ISSUE TITLE
New lodash module (@^4.17.9) causes Formik load failure via CommonJS

### ISSUE THREAD

**Issue by cps333** [formium/formik#1245]
This lodash [commit](https://github.com/lodash/lodash/commit/f73db1f02c30ea0386e198ef4ec47d368d6f2cec) added `freeModule.require('util')` into the `nodeUtil` function, which inadvertently triggers CommonJS dependency detection and causes CommonJS to throw `ModuleError`.

Same issue has been found by [stealjs](https://github.com/stealjs/steal/issues/1412).

**Comment by jaredpalmer** [comment]
Can you make a PR?

**Comment by jaredpalmer** [comment]
@TrySound is this is a valid bug?

**Comment by maddhruv** [comment]
Closing due to long inactivity
