### ISSUE TITLE
Add callbacks to ArrayHelpers

### ISSUE THREAD

**Issue by pierroberto** [formium/formik#1253]
### Current Behavior

`arrayHelpers` does not support callbacks. Indeed its methods behave asyncronously (e.g. `remove` and `push` ).

### Desired Behavior

It would be useful to have the possibility to fully manage local state together with Formik state syncronously.

### Suggested Solution

Add a callback as parameter in the methods of `arrayHelpers` in order to manage asyncronous behaviour.

Example:
```
<Form>
 <FieldArray
  name={stepName}
  render={arrayHelpers => (
   <Field>....</Fiedl>
  <button type="submit" onClick={() => arrayHelpers.push({}, **cb**)}>submit</button>
</Form>
```

### Who does this impact? Who is this for?

This would impact on users who need to work with dynamic forms and need different behaviour of their components based on an array of objects generated with ArrayField.

### Describe alternatives you've considered

At the moment, I use `setFormikState` in order to get a syncronous behavior of `push` and `remove` methods.

**Comment by jaredpalmer** [comment]
This makes sense. My issue is that hooks is going to make this API impossible in v2.

**Comment by pierroberto** [comment]
It could be, meanwhile I added a callback to arrayHelpers in my project.
I think someone can benefit from that.
I am going to do a pull request soon these days and waiting for your feedback.

**Comment by johnrom** [comment]
If "hooks is going to make this API impossible in v2", should we move this to the backlog (2.1+), or consider resolving it another way in the v2.0 milestone?

**Comment by maddhruv** [comment]
Closing due to long inactivity

**Comment by simdd** [comment]
> It could be, meanwhile I added a callback to arrayHelpers in my project. I think someone can benefit from that. I am going to do a pull request soon these days and waiting for your feedback.

following up?
