### ISSUE TITLE
render vs component vs children inconsistency

### ISSUE THREAD

**Issue by maraisr** [formium/formik#1256]
## ❓Question

If you look at https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L166-L189 the `Field` component.

The `render` prop executes the component, which when used as you bind the `onChange` handler, every keystroke, re-renders the component, sure, but uses the same element each time, just applying a new prop. Simply try a `Math.random()` in the render, it'll be the same for every keystroke. The same goes for children. However; if you use the `component` prop, you get a brand new component out the other end, every keystroke. 

Is there a reason why we're using a `React.createElement` to create a brand new react element out the other end - which to me offers a vastly different outcome to the `render` and `children` apis.

**Comment by jaredpalmer** [comment]
What would you change it to?

**Comment by maddhruv** [comment]
Closing due to long inactivity
