### ISSUE TITLE
Rerender FastField on changes in name

### ISSUE THREAD

**Issue by charlax** [formium/formik#1257]
### Current Behavior

When a `FastField`'s `name` changes, it is not re-renderered.

### Desired Behavior

It would seem logical to re-render a `FastField` when its `name` changes.

### Suggested Solution

Just add a check for `name` change in `FastField`'s `shouldComponentUpdate`.

### Who does this impact? Who is this for?

Would impact all users.

### Describe alternatives you've considered

In theory, you can provide a custom `shouldUpdate` to `FastField`, but it skips the default checks for changes in `touched`, `errors`, `values` etc. See #1238.

**Comment by maddhruv** [comment]
Closing due to long inactivity
