### ISSUE TITLE
Form conflict when rendering form multiple times

### ISSUE THREAD

**Issue by jp3492** [formium/formik#1259]
I am mapping over a list where each list item includes a form to edit the list items information. Since i am rendering the form multiple times and there is no way of giving the Formik object an id (based on map index) to differntiate between multiple instances of that form.

Any idea on how to solve this?

**Comment by pierroberto** [comment]
Could you give an example of your code?

Did you try to use refs?

**Comment by jaredpalmer** [comment]
@jp3492 Can you fill out the the issue template and create a reproducible example in codesandbox?

**Comment by maddhruv** [comment]
Closing due to long inactivity
