### ISSUE TITLE
TypeScript: Array of Files in Values

### ISSUE THREAD

**Issue by fabb** [formium/formik#1265]
## ❓Question

Hi everyone! I'm trying to build a form in with Formik in TypeScript. Until I added an array of files to my Values, everything worked fine. Now Formik throws a type error (but the application would work correctly). How should I keep my file array in the values? I did it like this:
```
interface MyFormValues {
    email: string
    subject: string
    message: string
    files: File[]
}
```
I get type errors for the  `touched` and `errors` props:
* `touched`: `Type 'any[]' is not assignable to type 'boolean | undefined'`
* `errors`: `Type 'any[] | undefined' is not assignable to type 'string | undefined'.`

Formik seems to think that I want to specify a "subform" by that `files` array in my values. The problem stems from the types of `FormikTouched` and `FormikErrors`:
```
export declare type FormikErrors<Values> = {
    [K in keyof Values]?: Values[K] extends object ? FormikErrors<Values[K]> : string;
};
export declare type FormikTouched<Values> = {
    [K in keyof Values]?: Values[K] extends object ? FormikTouched<Values[K]> : boolean;
};
```
Any idea how I can work around this (without giving up on type safety and setting `files: any`)?

**Comment by jaredpalmer** [comment]
How does your file input work? Can you create a reproducible example in codesandbox.io?

**Comment by fabb** [comment]
I wrapped [react-dropzone](https://github.com/react-dropzone/react-dropzone) in a component and wrap its callback in one of my own with additional info (rejection reasons because of file type, size or count).
I can try to build an example, but it may take a while until I get to it.

**Comment by maddhruv** [comment]
Closing due to long inactivity
