### ISSUE TITLE
How to get value in TouchableOpacity 

### ISSUE THREAD

**Issue by virginiarcruz** [formium/formik#1273]
## ❓Question

I have two byttons (yes or no) with TouchableOpacity on the react-native.
I want to get the value when click in some of two.

How I do to get this value?

```
<TouchableOpacity 
    value={props.values.main_home} 
     onPress={text => props.setFieldValue("main_home", text)}
     style={style.footerBtn}>
    <Text style={style.textButtonFt}> Yes</Text>
</TouchableOpacity>

<TouchableOpacity 
    value={props.values.main_home} 
     onPress={text => props.setFieldValue("main_home", text)}
     style={style.footerBtn}>
    <Text style={style.textButtonFt}> No</Text>
</TouchableOpacity>
```

**Comment by jaredpalmer** [comment]
AFAIK React Native's `TouchableOpacity` does not accept a `value` prop. What text are you trying to pass? "Yes" and "No" ? Can you elaborate in more depth or create a Snack on snack.expo.io to reproduce?

**Comment by virginiarcruz** [comment]
I trying to pass value **true** when click in 'Yes' and **false** when click in 'No'

**Comment by Andreyco** [comment]
Just modify onPress handlers like this

```
// for yes button
onPress={() => props.setFieldValue("main_home", true)}

// for no button
onPress={() => props.setFieldValue("main_home", false)}
```

**Comment by maddhruv** [comment]
Closing due to long inactivity
