### ISSUE TITLE
FieldArray remove returns nothing

### ISSUE THREAD

**Issue by wschmrdr** [formium/formik#1285]
## 🐛 Bug report

One quick little bug I found with the remove method while trying to debug a problem I was having with the FieldArray remove:

### Current Behavior

The FieldArray remove is returning an undefined value. This happens regardless of which element (first, middle, last) you remove.

### Expected behavior

As per your documentation, the FieldArray remove should be returning the value that was removed.

### Suggested solution(s)

Considering making a deep clone of the array value that is slated to be removed when setting result. Since result is being set to a reference to the array entry, once it's sliced, it's gone from result as well as the array.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.2
| React            | 16.7.0
| TypeScript       | (none; using JS)
| Browser          | Firefox (latest)
| npm/Yarn         | 6.4.1
| Operating System | Linux Mint 17

**Comment by stsiwo** [comment]
I have the same issue. the FieldArray pop also returns undefined.

**Comment by lyquangthai1993** [comment]
When array is only one item in this, function remove is working, size >=2 it not working

**Comment by maddhruv** [comment]
Closing as stale for long
