### ISSUE TITLE
How to call handleSubmit on a particaular set of fields?

### ISSUE THREAD

**Issue by prateek3255** [formium/formik#1298]
I have a form that is divided into separate sections, when I call handleSubmit on the form, errors are shown next to all the fields that are not valid according to the validation schema (which is awesome BTW).
But is there a way to do that for a particular set of fields, i.e., can I call handleSubmit for a particular set of fields that are not valid according to the validation schema, so that I can block the user from moving to the next section until those set of fields are filled.

**Comment by jaredpalmer** [comment]
I think so. ValidationSchema can be a function that returns a Yup schema. You could track your “stage” outside of Formik and then return a different schema accordingly. I think that would work.

**Comment by maddhruv** [comment]
Closing due to long inactivity
