### ISSUE TITLE
Update v2 to 16.8 stable

### ISSUE THREAD

**Issue by jaredpalmer** [formium/formik#1310]
- [ ] Update react-testing-library tests to use `.act`
- [ ] Update deps

**Comment by matmalkowski** [comment]
@jaredpalmer ✋ I can help with that one

**Comment by johnrom** [comment]
Note from PR:

> We were blocked by facebook/react#14853 (await act(() => )). We are going to jump to 16.9.0-alpha instead. - Jared Palmer

**Comment by ri7nz** [comment]
Hello, @jaredpalmer .

I want to contributing in this project. 

I have been try in my local machine & change `react-testing-library` to new version `@testing-library/react`. 

but have failed in test in my branch https://github.com/ri7nz/formik/tree/issue-1310/update-deps :
- `test/Field.test.tsx`
- `test/FieldsArray.test.tsx`

Thanks 👍
