### ISSUE TITLE
`onChange/ onInput` not be fired if input value is a empty string

### ISSUE THREAD

**Issue by robertu7** [formium/formik#1346]
### Current Behavior
As title. `validate` can be fired even if input value is empty string.

### Expected behavior
`onChange/ onInput` should be fired  even if input value is empty string.

### Reproducible example
```tsx

const BaseSearchBar = ({
  values,
  handleChange,
  handleSubmit
}: FormikProps<FormValues>) => {
  return (
    <form onSubmit={handleSubmit}>
        <input
            type="search"
            name="q"
            autoComplete="off"
            onChange={e => {
                console.log('onChange', values)
            }}
        />
    </form>
  )
}

export const SearchBar = withFormik<FormProps, FormValues>({
  validate: values => {
    console.log('validate', values)
  },
})(BaseSearchBar)

```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.1
| React            | 16.8.1
| TypeScript       | 3.3.3
| Browser          | Chrome
| npm/Yarn         | npm
| Operating System | macOS

**Comment by Andreyco** [comment]
1. validate is triggered on `submit` action. Add, e.g. `<button type="submit">Submit</button>` into `BaseSearchBar` form
2. Formik has no way of knowing there is a change happening inside, since you are not using Formik's `onBlur/onChange` handlers, or `setFieldValue/setFieldTouched`

Please, adjust and try again

**Comment by RoberMac** [comment]
@Andreyco Use `Form` and `Field` still does not work :( 
![image](https://user-images.githubusercontent.com/4065233/53063359-c2707c00-34fe-11e9-9bc8-5032113c7c0d.png)

**Comment by Andreyco** [comment]
As I said, main issue is not using `handleChange` and `handleBlur` handlers. Please, see corrected example, `values.q` is in sync with actual input field. https://codesandbox.io/s/2x54kwo43n

**Comment by maddhruv** [comment]
Closing due to long inactivity
