### ISSUE TITLE
validateField after handlChange can't get latest state

### ISSUE THREAD

**Issue by Ryomasao** [formium/formik#1349]
## ❓Question
I want to avoid running Validation with multiple fields, so I set `validateOnChange:false` and use `handleChange` and `validateField` in `onChange` 
 
However, `ValidateField` does not seem to refer to the value updated by handleChange.

what should i do?

```javascript

const validateName = value => {
  // value is previous state...
  return value.length > 3 && "Error";
};


const MyForm = props => {
  const { handleChange, validateField, errors } = props;

  return (
    <form>
      <label htmlFor="name">Name</label>
      <Field
        id="name"
        name="name"
        type="text"
        onChange={e => {
          handleChange(e);
          validateField("name");
        }}
        validate={validateName}
      />
    </form>
  );
};

const EnhancedForm = withFormik({
  validateOnChange: false,
  validateOnBlur: false,
  mapValueToProps: () => ({
    name: ""
  })
})(MyForm);
```

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by zlanich** [comment]
+1 for this. This is 100% relevant to all of my current Formik issues around implementing auto-save functionality and partial submits. See my umbrella issue: #1506

**Comment by Andreyco** [comment]
There is work in progress which turns setters into promises (and possibly resolve next value). I think this and awaiting handleChange would help

**Comment by zlanich** [comment]
@Andreyco Is there a PR or Issue for this WIP?

**Comment by maddhruv** [comment]
Closing due to long inactivity
