### ISSUE TITLE
React Typescript Error in Compile

### ISSUE THREAD

**Issue by tynarbekov** [formium/formik#1354]
@jaredpalmer 
### Reproducible example When npm install and import Formik

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:59 
    TS1005: '>' expected.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:123 
    TS1109: Expression expected.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:129 
    TS1109: Expression expected.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:145 
    TS1005: ';' expected.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:232 
    TS1109: Expression expected.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:238 
    TS1109: Expression expected.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:59 
    TS2365: Operator '<' cannot be applied to types 'boolean' and 'number'.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:90 
    TS2339: Property 'ProviderProps' does not exist on type 'Promise<typeof "/node_modules/create-react-context/lib/in...'.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:104 
    TS2693: 'FormikContext' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:118 
    TS2693: 'any' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:125 
    TS2693: 'any' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:131 
    TS2304: Cannot find name 'FormikConsumer'.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:147 
    TS2365: Operator '<' cannot be applied to types 'boolean' and 'number'.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:153 
    TS2339: Property 'ComponentClass' does not exist on type 'typeof React'.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:199 
    TS2339: Property 'ConsumerProps' does not exist on type 'Promise<typeof "/node_modules/create-react-context/lib/in...'.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:213 
    TS2693: 'FormikContext' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:227 
    TS2693: 'any' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/formik/dist/connect.d.ts:3:234 
    TS2693: 'any' only refers to a type, but is being used as a value here.

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.1
| React            |  16.1.1
| TypeScript       | 2.8.1
| Browser          | Any
| npm/Yarn         | npm =>  5.6.0
| Operating System | Ubuntu 16

**Comment by mcmaceac** [comment]
Getting the same errors:

Software | Version(s)
-- | --
Formik | 1.5.4
React | 16.8.4
TypeScript | 2.8.3
Browser | Any
npm/Yarn | npm => 6.4.1
Operating System | macOS Mojave 10.14.2

**Comment by jaredpalmer** [comment]
Bump to 1.5.6

**Comment by mcmaceac** [comment]
1.5.6 fixed most of the errors except for the following:

`ERROR in /node_modules/formik/dist/Formik.d.ts(13,28):
TS2304: Cannot find name 'unknown'.
ERROR in /node_modules/formik/dist/Formik.d.ts(40,92):
TS2304: Cannot find name 'unknown'.
ERROR in /node_modules/formik/dist/Formik.d.ts(62,96):
TS2304: Cannot find name 'unknown'.
ERROR in /node_modules/formik/dist/Formik.d.ts(104,96):
TS2304: Cannot find name 'unknown'.
ERROR in /node_modules/formik/dist/types.d.ts(54,22):
TS2304: Cannot find name 'unknown'.
ERROR in /node_modules/formik/dist/types.d.ts(54,114):
TS2304: Cannot find name 'unknown'.`

It looks like I would have to move up to Typescript 3 to use this.

**Comment by jaredpalmer** [comment]
Oof that was a mistake. We probably should have bumped to 1.6 to use unknown.

**Comment by maddhruv** [comment]
Closing due to long inactivity
