### ISSUE TITLE
Field with custom input type="checkbox" component while using onReset doesn't turn checked

### ISSUE THREAD

**Issue by Vagantem** [formium/formik#1366]
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by johnrom** [comment]
@vagantem can you provide a Sandbox for this? I'm seeing it work in v2 here:

https://codesandbox.io/s/formik-2-irey5

**Comment by maddhruv** [comment]
Closing due to lacking information and long inactivity
