### ISSUE TITLE
Persist errors?

### ISSUE THREAD

**Issue by checkhavoc** [formium/formik#1396]
Scenario:

- Submit empty form with required fields that uses `FieldArray`
- All fields that are empty and required, will have errors
- Push an additional value to `FieldArray`
- After pushing the additional value to `FieldArray`, is forces a re-render and the previous errors from the first submission are cleared. 

Question
Is there any way to persist these errors (in formik) without having to maintain a component state?

**Comment by maddhruv** [comment]
Closing due to long inactivity

**Comment by DiegoArrieta** [comment]
> Scenario:
> 
> * Submit empty form with required fields that uses `FieldArray`
> * All fields that are empty and required, will have errors
> * Push an additional value to `FieldArray`
> * After pushing the additional value to `FieldArray`, is forces a re-render and the previous errors from the first submission are cleared.
> 
> Question
> Is there any way to persist these errors (in formik) without having to maintain a component state?

did you find any solution?
