### ISSUE TITLE
form onSubmit handlers

### ISSUE THREAD

**Issue by isaacalves** [formium/formik#1420]
The code below is taken from the [overview](https://jaredpalmer.com/formik/docs/overview) page and I'm very confused about the `onSubmit` handlers:

The form element has an `onSubmit` property that refers to `handleSubmit` which is passed on that anonymous function : `<form onSubmit={handleSubmit}>`. Where does that come from?

The Formik component has an `onSubmit` property as well. 

`onSubmit={(values, { setSubmitting }) => { ... }` 

How these relate to each other? What is going on? 

Thanks so much

```
import React from 'react';
import { Formik } from 'formik';

const Basic = () => (
  <div>
    <h1>Anywhere in your app!</h1>
    <Formik
      initialValues={{ email: '', password: '' }}
      validate={values => {
        let errors = {};
        if (!values.email) {
          errors.email = 'Required';
        } else if (
          !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(values.email)
        ) {
          errors.email = 'Invalid email address';
        }
        return errors;
      }}
      onSubmit={(values, { setSubmitting }) => {
        setTimeout(() => {
          alert(JSON.stringify(values, null, 2));
          setSubmitting(false);
        }, 400);
      }}
    >
      {({
        values,
        errors,
        touched,
        handleChange,
        handleBlur,
        handleSubmit,
        isSubmitting,
        /* and other goodies */
      }) => (
        <form onSubmit={handleSubmit}>
          <input
            type="email"
            name="email"
            onChange={handleChange}
            onBlur={handleBlur}
            value={values.email}
          />
          {errors.email && touched.email && errors.email}
          <input
            type="password"
            name="password"
            onChange={handleChange}
            onBlur={handleBlur}
            value={values.password}
          />
          {errors.password && touched.password && errors.password}
          <button type="submit" disabled={isSubmitting}>
            Submit
          </button>
        </form>
      )}
    </Formik>
  </div>
);

export default Basic;
```

**Comment by lee-reinhardt** [comment]
The "anonymous function" you're referring to is using the render-prop pattern ([read more](https://reactjs.org/docs/render-props.html)).

The child of the `<Formik />` component is a function that Formik calls to render the actual form elements (form tag, inputs, submit buttons, etc.). The props that are passed to this function are the `FormikProps` ([source](https://github.com/jaredpalmer/formik/blob/master/src/types.tsx#L226)). Some of those props are the `FormikHandlers` ([source](https://github.com/jaredpalmer/formik/blob/master/src/types.tsx#L134)) which includes a `handleSubmit` function. This handler is passed to the "native" `onSubmit` handler of the `<form />` element.

The `handleSubmit` handler eventually calls the function that is defined as `onSubmit` of the `<Formik />` component.
- `handleSubmit` first does some dev-only checks/warnings ([source](https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L394)), then calls...
- `submitForm` which updates some Formik state, then runs form validation ([source](https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L426)). If validation passes, it calls...
- `executeSubmit` which calls `this.props.onSubmit(this.state.values, this.getFormikActions())` (your submit handler) passing the valid form values and some Formik actions ([source](https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L453))

I hope this helps!

**Comment by maddhruv** [comment]
Closing due to long inactivity
