### ISSUE TITLE
Formik validation does not consider changes in the errors structure

### ISSUE THREAD

**Issue by acooleva** [formium/formik#1427]
## 🐛 Bug report

Formik validation does not consider changes in the errors structure

### Current Behavior
 
Currently Formik in order to know whether to update the error messages uses a logic which checks whether the current field exists in the previous and current list of errors but it does not consider the changes in the properties of the errors  (not just the length but its properties as well). 

```
ErrorMessageImpl.prototype.shouldComponentUpdate = function (props) {
    if (getIn(this.props.formik.errors, this.props.name) !== getIn(props.formik.errors, this.props.name)
      || getIn(this.props.formik.touched, this.props.name) !== getIn(props.formik.touched, this.props.name)
      || Object.keys(this.props).length !== Object.keys(props).length ) {
      return true;
    } else {
      return false;
    }
  };
```

In this case there is an issue in the following scenario:

On a screen there are two radio buttons. Once the first button is checked a Form A of type X needs to be displayed and when the second button is checked a Form B of the same type X needs to be displayed.

type X would be: 
```
type {
  firstName: string,
  lastName: string,
}
```

Those forms on the screen in fact would be symmetrical and whenever the one is hidden the another one is displayed on the same place. So, if the errors for the one form are not refreshed the errors will stay for the another form when the another radio button is checked. 
For instance, let's say that the firstName is with errors in Form A and with no errors in Form B. According to your check the firstName from the Form B will not be present either in the previous errors state (for Form A as its name path is ```formB.firstName```) neither in the current errors (for Form B as it has no errors). There will be no change in the props keys length as well, so the condition whether the error message should be updated or not will be set to false and the error message will not be updated and will remain for the screen B as well, although there we have valid first name. Just for clarification, the errors state when the Form A is displayed is ```formA: { ...errors...} ``` and when Form B is displayed it is ```formB: {...errors...} ```.

### Expected behavior

The error messages not to be mixed up between the two forms. 

### Suggested solution(s)
It might be good to check whether the errors state has changed as well. For instance, to check whether there is a change in the previous and current error state structure before the check whether the current field name is in the previous errors state as well in the current one. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.1
| React            | 16.8.4
| Node version | 10.12.0
| Operating System | Windows 10

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by maddhruv** [comment]
Closing due to long inactivity
