### ISSUE TITLE
Unable to load initial value with withformik

### ISSUE THREAD

**Issue by raytangRT** [formium/formik#1430]
## ❓Question

Hi, I am trying to `withFormik` to initialize my form, but unable to load init value, and idea why? 

the form initializing depend on an object that is fetched from server inside React.useEffect

codesandbox [here](https://codesandbox.io/s/xp3zz0przp)

**Comment by lee-reinhardt** [comment]
I believe you will need to set `enableReinitialize={true}` (https://jaredpalmer.com/formik/docs/api/withformik#enablereinitialize-boolean).

You have to opt-in to behavior that will cause "initial values" to update. By default, Formik only reads the initial values once on initial mount. This is also discussed in https://github.com/jaredpalmer/formik/issues/811

**Comment by SistemasSouza** [comment]
I have a problem with enableReinitialize, when do validation in backend have this error

 A component is changing a controlled input of type text to be uncontrolled

**Comment by godmar** [comment]
This means your `mapPropsToValues` function failed to set all form fields. Say you have <Field name="x" .../> but the object you return from `mapPropsToValues` doesn't have an property `x`.

**Comment by maddhruv** [comment]
Closing due to long inactivity
