### ISSUE TITLE
A working example of the MultistepWizard for react native

### ISSUE THREAD

**Issue by sunviwo** [formium/formik#1438]
Hi, could someone provide me with a working example of the multistepwizard for react native ? [https://github.com/jaredpalmer/formik/blob/master/examples/MultistepWizard.js](https://github.com/jaredpalmer/formik/blob/master/examples/MultistepWizard.js)
I'm trying for a week now and still can't get a perfect result. I can go forth and back in steps. Still here are some of things I'm intending to achieve:
* update the state with value from TextInputs, pickers (custom) and other field types;
* a Yup validation of each step;
* get values after submit and process them and send them with an API call to server. 

EXTRA : one step consist of inviting the user to take  images with his camera, or select images from camero roll, and choose one of them as cover image (Radio button involved or a check on the selected image ?) Any help on that side would be highly appreciated too. Thanks in advance.

**Comment by maddhruv** [comment]
Closing as being tracked in https://github.com/formium/formik/issues/1315
