### ISSUE TITLE
withFormik() Reset Form After Submit

### ISSUE THREAD

**Issue by siolishe** [formium/formik#1456]
hi guys I know it might be repetitive but i already have read lots of pages but found nothing i have some problems to reset my form after submit when i use withFormik() here is a part of my code :

`const schema = yup.object<ICompanyCreateModel>({
    Publisher: yup.string().required()
});
const EnhancedForm = (props: {
    values: any;
    touched: any;
    errors: any;
    handleChange: any;
    handleSubmit: any;
}) => {
    const {
        values,
        touched,
        errors,
        handleChange,
        handleSubmit
    } = props;
    return (
        <div className="container">
            <Form onSubmit={handleSubmit}>
                <Form.Row>
                    <div className="col-md-6">
                        <Form.Group>
                            <InputGroup>
                                <Form.Control
                                    type="text"
                                    required
                                    aria-describedby="inputGroupAppend"
                                    name="Publisher"
                                    className="text-right"
                                    // value={values.Publisher ? toString() : ""}
                                    onChange={handleChange}
                                    isInvalid={!!errors.Publisher}
                                    isValid={touched.Publisher && !errors.Publisher}
                                />
                                <InputGroup.Append>
                                    <InputGroup.Text>Publisher</InputGroup.Text>
                                </InputGroup.Append>
                            </InputGroup>
                        </Form.Group>
                <Button type="submit">submit</Button>
            </Form>
        </div>
    );
};
const companyAdCrud = withFormik({
    mapPropsToValues: () => schema,
    enableReinitialize: true,
    handleSubmit: (values, actions) => {
        CRUD.companyAds()
            .create(values)
            .then(res => {
                if (res.status === 200) {
                    actions.resetForm();
                    actions.setStatus({success: true});
                    alert("ok");
                } else {
                    alert("Not Ok!");
                    actions.setStatus({success: false});
                    actions.setSubmitting(false);
                }
            });
    }
})(EnhancedForm);
export default companyAdCrud;`

**Comment by yuritoledo** [comment]
Can u create a codesandbox with example?

**Comment by maddhruv** [comment]
Closing due to long inactivity
