### ISSUE TITLE
About FastField not really show optimization

### ISSUE THREAD

**Issue by phatNfqAsia** [formium/formik#1460]
## ❓QuestionI implement
I copy and paste the Basic component you provided in the document onto an empty project

But when I typed in the FastField I saw the whole form glow in the React Profiler. It seem that the component still make the whole form rerender when it get updated

Look forward to seeing your reply

**Comment by Andreyco** [comment]
Curious to know, do you observe same speed with `FastField`? Based on visual observations or profiling?

**Comment by maddhruv** [comment]
Closing due to long inactivity
