### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by alqamabinsadiq** [formium/formik#1465]
### Current Behavior
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
<img width="704" alt="Screenshot 2019-04-25 at 6 06 27 PM" src="https://user-images.githubusercontent.com/16412803/56737892-df3a6180-6784-11e9-9127-d3e4aa80be0f.png">

### Expected behavior
I am trying to use Formik with a CDN in Preact application.

### Reproducible example

https://codepen.io/alqamabinsadiq/pen/oOQrYM?editors=0010

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |https://unpkg.com/formik/dist/formik.umd.production.js
| Preact            |https://unpkg.com/preact

**Comment by maddhruv** [comment]
Closing due to long inactivity

**Comment by jeslenbucci** [comment]
I'm getting this exact same error if I try to successfully submit my form a second time. The error happens only to touched fields that are using the useField() helpers.

**Comment by jeslenbucci** [comment]
So, I was able to resolve this. 

I'm using my form to manage payment processing as well as store the submissions. I don't want to store all of the payment data with the submission. On my form I have an address set of fields that can be used to populate a billing address set of fields. I do not want to store the billing address in my submissions, only use the data, if required, for the payment processing.

In my onSubmit prop function, I was doing the following:

```
onSubmit={async (values, { resetForm }) => {
  // attempt to clone values
  const submissionValues = values
  
  // delete the billing address props
  delete submissionValues.billingAddress
  
  // submit values without billing address
  await axios.post('/api/submit-form', submissionValues)
  
  // do other stuff
  ...
  
  // reset the form
  resetForm()
}
```

What I thought I was doing was cloning the values object, removing the billing fields, and then passing the clone as my submission (see code comments). However, what I believe is actually happening is that I created a reference to the values, deleted those fields, and then when the submission function resolved, Formik tried to reset the form, but now my validation schema did not match my initialValues/values. This caused the error in the original post.

I guess you need to maintain the shape of the values object or else it will break the validation.
