### ISSUE TITLE
context-based comps, hooks and missing provider in 2.0

### ISSUE THREAD

**Issue by slorber** [formium/formik#1477]
Hi,

Currently, it's possible to use formik in v2 which does not require a parent FormikProvider

But this will make all components using FormikContex to fail. It's actually a bit nasty because there's no warning on mount, but as the context methods are not injected into the consumer components, we get this kind of errors:

![image](https://user-images.githubusercontent.com/749374/56979565-60756800-6b7a-11e9-9a1e-acf9d6c74b9d.png)

I think we should

**1) Make it fail fast**

```js
const form = useFormik()
return <FieldArray>...</FieldArray>
```

This should crash/error on mount instead of on attempt to modify form

**2) Document that this is possible:**

```js
const form = useFormik()
return <FormikProvider value={form}><FieldArray>...</FieldArray></FormikProvider>
```

It's a workaround I'll use temporarily (as I'm for strong typesafety/manual typesafe wiring, I try to avoid using context-based components)

**3) Allow all context-based components to be able to receive the form as props**

```js
const form = useFormik()
return <FieldArray form={form}>...</FieldArray>
```

**Comment by jaredpalmer** [comment]
All context based components and hooks should crash with a warning. In a perfect world there is a formik.getFieldArrayHelpers that can be used without context just like formik.getFieldProps

**Comment by maddhruv** [comment]
Closing due to long inactivity
