### ISSUE TITLE
values prop references getInitialValues function

### ISSUE THREAD

**Issue by conor909** [formium/formik#1478]
## 🐛 Bug report
| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |  v2.0.1-alpha.2

`values` prop references the `getInitialValues` function.

![values](https://user-images.githubusercontent.com/2417359/57015532-24d7ae00-6c0d-11e9-969b-535176e07e7a.PNG)

**Comment by jaredpalmer** [comment]
Yeah that seems like a buggo

**Comment by conor909** [comment]
This happens in the latest version too, it's when I use a custom component as oppose to a basic HTML `<input>`

**Comment by maddhruv** [comment]
Closing due to long inactivity
