### ISSUE TITLE
 dynamic validation schema based on type of form submit.

### ISSUE THREAD

**Issue by viv3kk** [formium/formik#1482]
### Current Behavior

Not able to use dynamic validation schema based on type of form submit. 
Types can be : Save partial form or Submit entire form

### Desired Behavior
to be able to specify which validation scheme to be used depending on state variable.
this.state.submitType == 'partial' ? Partial_Validation : Default_Validation

**Comment by Andreyco** [comment]
Please, search thru issues, there is nice example how to solve this use case

**Comment by maddhruv** [comment]
Closing due to long inactivity
