### ISSUE TITLE
Why limit error to just a string?

### ISSUE THREAD

**Issue by vincentjames501** [formium/formik#1489]
### Current Behavior

Form errors are currently of type `string`. In most other form validation libraries I've used this is an `any` type so a user could do things like the following:

```js
setErrors({
  password: ['Must be more than 8 characters', 'Must contain a special character']
})
```
or for localization:

```js
setErrors({
  password: [{type: 'min', min: 3, value: 1}]
})
```

```js
setErrors({
  password: [{localizationKey: 'blah', value: 1}]
})
```

Is there any reason why it needs to strictly be of type `string`? It actually works setting it to whatever I want so long as I cast it but makes working with TypeScript funky and limits the flexibility of users.

Similar to #1244, #1293

**Comment by Andreyco** [comment]
Errors are not limited to strings. You can use whatever data structure you wish.

**Comment by maddhruv** [comment]
Closing due to long inactivity
