### ISSUE TITLE
Is it possible to set enableReinitialize conditionally?

### ISSUE THREAD

**Issue by omung** [formium/formik#1493]
First of all, thanks for all your great help... I have a scenario where I need to reset form values conditionally, is it possible?
Specifically based on props value, can I set enableReinitialize?

In more detail: Is it possible to not refresh form on props update conditionally?

**Comment by Andreyco** [comment]
Please, provide code example and expected result. Thanks.

**Comment by maddhruv** [comment]
Closing due to long inactivity
