### ISSUE TITLE
Is it possible to run a particular validation only on submit ?

### ISSUE THREAD

**Issue by tonyhallett** [formium/formik#1500]
Here is my [workaround](https://codesandbox.io/s/k2mov78zmo).  Is there a better way ?

**Comment by jaredpalmer** [comment]
Yes, but not in an official way. The workaround you've proposed is probably okay. Can you explain the use case in more detail?

**Comment by tonyhallett** [comment]
From what I reminder the use case was just to lazily determine validity as it is expensive and is expected that before submitting the form the user would have to transition from/to the invalid state and it was not necessary to report errors.

Perhaps the formik validate method could be provided with an isSubmitting boolean value ?

**Comment by ShadiSimplbit** [comment]
> From what I reminder the use case was just to lazily determine validity as it is expensive and is expected that before submitting the form the user would have to transition from/to the invalid state and it was not necessary to report errors.
> 
> Perhaps the formik validate method could be provided with an isSubmitting boolean value ?
I think this is what you are looking for
https://stackoverflow.com/questions/56742376/react-formik-trigger-validation-only-on-form-submit/56742581

**Comment by ShadiSimplbit** [comment]
> From what I reminder the use case was just to lazily determine validity as it is expensive and is expected that before submitting the form the user would have to transition from/to the invalid state and it was not necessary to report errors.
> 
> Perhaps the formik validate method could be provided with an isSubmitting boolean value ?

      ```
<Formik
        validateOnChange={false}
        validateOnBlur={false}
      >
```
[https://codesandbox.io/s/formik-codesandbox-template-7hu5m](is that are you looking for?)

**Comment by tonyhallett** [comment]
The behaviour is different in your example.  I am using validateOnChange to clear the error when typing again.

**Comment by richmeij** [comment]
I have a similar use case where I want to do simple validations on change (e.g. required) and a more complex/expensive validation on submit.

**Comment by HYJ29** [comment]
I think you can put your validation logic on 'onSubmit' function with the values passed on.

**Comment by CooCooCaCha** [comment]
I have a similar use case where I want to display an error summary modal only on submit.

**Comment by maddhruv** [comment]
Closing due to long inactivity
