### ISSUE TITLE
Set form to touched when Reinitialized

### ISSUE THREAD

**Issue by douglasrcjames** [formium/formik#1542]
So I am trying to use `enableReinitialize={true}` in my form so when I change the state externally, the form will update the values to match what that state has change to. The values are successfully changing when the state changes externally, however, the form is un-submittable because the form isn't being recognized as being changed/touched, even though the value is seen as changed. If I change the value of a field manually, it will allow me to submit.  How do I explicitly set the form to be submit-able?

This is my current attempt to just set 1 field as touched when the field has changed so that it will allow me to submit form: (currently not submitting form)
```
.
.
.
 <PlacesAutocomplete
       value={this.state.fullAddress}
       onChange={ e => {
            props.setFieldTouched('address.line1', true, true);
            this.handleAddressChange();
         }}
        onSelect={this.handleSelect}
        >
.
.
.
```

**Comment by Andreyco** [comment]
When form is reinitialized, its state is reset. Changing props outside of Formik does not mean Formik should consider them touched.

**Comment by douglasrcjames** [comment]
So the question wasn't on whether Formik should or shouldn't consider anything touched. I am asking how what might be the best way to set the form as submittable explicitly, after the form is Reinitialized, without having to change/touch any other values.

**Comment by Andreyco** [comment]
Honestly I dont know, but I believe we are open to good ideas. Do you track/sync touched state outside of formik? What is your usecase?

**Comment by douglasrcjames** [comment]
Thanks for taking a look again. I attached my use case. As you can see if the user searches for their address and makes a selection, the form will reinitialize the other address inputs, however, the form will not allow submission until the user types something manually. I was hoping there was a way for me to allow form submission after the address selection was made without having to edit another input?  Hopefully it makes more sense now, let me know if you need more clarification. 

![submit_after_reinit](https://user-images.githubusercontent.com/22306305/58279161-8691c080-7d52-11e9-965b-0169a323bf83.gif)

**Comment by maddhruv** [comment]
Closing due to long inactivity
