### ISSUE TITLE
Namespace React has no exported member ProviderExoticComponent

### ISSUE THREAD

**Issue by FabienEssid** [formium/formik#1553]
## 🐛 Bug report
Formik version used : 1.5.7

### Current Behavior

When I launch `./gradlew test` on my project with Formik 1.5.7, I have these two errors :
`ERROR in [...]/node_modules/formik/dist/connect.d.ts(3,44):
TS2694: Namespace 'React' has no exported member 'ProviderExoticComponent'.`
`ERROR in [...]/node_modules/formik/dist/connect.d.ts(3,132):
TS2694: Namespace 'React' has no exported member 'ExoticComponent'.`

### Expected behavior

When I downgraded my version to Formik 1.5.4, everything works like expected.

### Suggested solution(s)
I haven't any idea about a solution.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.4.2
| TypeScript       | 3.0.1
| Browser          | Mozilla Firefox Quantum 67.0
| npm/Yarn         | npm 3.5.2
| Operating System | Ubuntu 18.04.2

Thanks for your attention

**Comment by johnrom** [comment]
ExoticComponent is used in a number of newer React scenarios. 

`React.Fragment`: `<></>`.

- If newer Formik 1.x versions use a Fragment, and you have a version of React which hasn't defined Fragments yet, this could be why. Try updating React.
- It's possible that your version of TypeScript doesn't yet understand this format of JSX. Try updating TypeScript.

`React.Provider / React.Consumer`:

React defines Context Provider + Consumer with ExoticComponent, so if any code uses React Context, that could be the issue. I would check if that version of Formik is using Context.

And of course, make sure you have a good package.lock or yarn.lock in version control so you can roll back any of these changes for testing purposes.

**Comment by Andreyco** [comment]
@FabienEssid closing the issue if no information/response will be provided

**Comment by jaredpalmer** [comment]
I think we should start asking for the @types/react version in the issue template

**Comment by Andreyco** [comment]
> I think we should start asking for the @types/react version in the issue template

Agree

**Comment by FabienEssid** [comment]
Thank you for your answers, I will try it

**Comment by maddhruv** [comment]
Closing due to long inactivity
