### ISSUE TITLE
Financial contribution to Formik Development

### ISSUE THREAD

**Issue by wwahammy** [formium/formik#1579]
### Current Behavior
There doesn't seem to be a way for users to support the sustainable maintenance of Formik. To be clear, I certainly don't have complaints, I  love Formik, I just want to make sure it continues to be the best form library on React.

### Desired Behavior

A way to financially contribute to the projects success.

### Suggested Solution
Don't have clear one yet. First the question would be who would maintain the program and be responsible for the money. After that, there's the need to be a transparent ways to decide how spend it. This depends on the type of revenue too. General donations need to be handled differntly than a pay for hire situation. Lots to think about and I'm happy to assist with that if I can.

**Comment by jaredpalmer** [comment]
I can’t publicly say yet what we’ve been working on, but some epic shit is in the works. I can share more info via Twitter DM. As for donations, I’m open to ideas/discussions, however, having a few small donors is not going to incentivize development. I would rather

**Comment by Andreyco** [comment]
I will get in touch on Twitter, very curious about this info

**Comment by maddhruv** [comment]
Closing due to long inactivity
