### ISSUE TITLE
[v2] Field onChange handler

### ISSUE THREAD

**Issue by LorenzoOpWerk** [formium/formik#1582]
## ❓Question

Hey, I noticed in the `getFieldProps` function from `useFormik` it will return `handleChange` without a path. Since the path is already known at this point since you provide the name as parameter for the `getFieldProps` function, wouldn't it make sense to send this along to the change handler instead of relying on getting the name from the event target later on:
https://github.com/jaredpalmer/formik/blob/e51f09a318cba216a1ba3932da0906202df0b979/src/Formik.tsx#L496

**Comment by jaredpalmer** [comment]
Yes. This is on my todo list.

**Comment by maddhruv** [comment]
Closing due to long inactivity
