### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'React.useRef(props.initialValue)') in formik@2.0.1-rc.4

### ISSUE THREAD

**Issue by mohamadnabikhani** [formium/formik#1589]
## 🐛 Bug report
In react-native, when I want to set errors in formik to Api's errors that come from redux (I mean I save the API's error messages in redux and do Api request in saga), According to @jaredpalmer  comment on twitter, i can use formik V2 for this, but when I upgraded it, there was a typeError error. but in formik v 1.5.7. everything was ok.
### Current Behavior
I just got this error in withFormik function.
![photo_2019-06-08_01-42-59](https://user-images.githubusercontent.com/7503107/59133932-d3021080-898e-11e9-9a2b-956e58fa0173.jpg)
### Reproducible 

in login container:
```
import LoginForm from '../Components/Login/LoginForm'
import LoginFormikEnhancer from '../FormHandlers/LoginForm'
...
const EnhancedLoginForm = LoginFormikEnhancer(LoginForm);
```

in FormHandlers/LoginForm
```
const LoginFormikEnhancer = withFormik({

  validationSchema: Yup.object().shape({
    username: Yup.string()
      .min(5)
      .required('Email is required'),
    password: Yup.string()
      .min(6)
      .required('Password is required'),
  }),

  mapPropsToValues: props => ({
   username: "", 
   password: "",

  }),
  handleSubmit: handleSubmit,
  displayName: 'LoginForm',
});
```
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.6.3
| TypeScript       | -
| Browser          | -
| react-native     | 0.58.6
| npm       | 5.6.0
| Operating System | ubuntu 18.04

**Comment by johnrom** [comment]
@mohamadnabikhani please create a minimal code sandbox that can reproduce this issue, and also list the versions of each, React, Formik, typescript/react (if using), typescript, node, npm, etc. This was all written in the initial "Bug Report" new issue template. If you need that information again, click "new issue -> bug report" and copy it from there.

My guess is that you updated formik, but you didn't update react to a version supported by formik v2 (therefore `useRef` doesn't exist). updating to the latest one should fix it. If that's not the case, we'll need a reproduction as described above.

**Comment by mohamadnabikhani** [comment]
> @mohamadnabikhani please create a minimal code sandbox that can reproduce this issue, and also list the versions of each, React, Formik, typescript/react (if using), typescript, node, npm, etc. This was all written in the initial "Bug Report" new issue template. If you need that information again, click "new issue -> bug report" and copy it from there.
> 
> My guess is that you updated formik, but you didn't update react to a version supported by formik v2 (therefore `useRef` doesn't exist). updating to the latest one should fix it. If that's not the case, we'll need a reproduction as described above.

I updated the code, is this sufficient? maybe I think the react version is not compatible with Formik v2, is it? so `useRef` is not existed in this version? I just has been updated formik, not others.

**Comment by johnrom** [comment]
Hooks were added in React 16.8 according to [the docs](https://reactjs.org/docs/hooks-reference.html), so Formik v2 won't be compatible with anything lower. You should have gotten a warning when you ran `npm install`, since `react@^16.8.0` is a peer dependency.

**Comment by jaredpalmer** [comment]
Hrmm is there another error message we should show folks?

**Comment by johnrom** [comment]
I think we can both add a Compatibility Matrix to the documentation and, if we use package.json or something to store this matrix, maybe we can add a dev environment warning when that compatibility isn't being met? Could be related to #1598

**Comment by jgoux** [comment]
Hello all,

I'm using React v16.8.6 and I'm unable to run formik@next properly.

I have the same kind of error : 
```
Uncaught TypeError: (0 , e.useRef) is not a function
    at W (Formik.tsx:128)
    at H (Formik.tsx:838)
    at renderWithHooks (react-dom.development.js:12938)
    at mountIndeterminateComponent (react-dom.development.js:15020)
    at beginWork (react-dom.development.js:15625)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
```

It's odd because I don't have this error if I use formik@2.0.1-rc.4, but for all the next releases I get it. Also I'm using hooks all over my project without issues.

**Comment by mohamadnabikhani** [comment]
> Hooks were added in React 16.8 according to [the docs](https://reactjs.org/docs/hooks-reference.html), so Formik v2 won't be compatible with anything lower. You should have gotten a warning when you ran `npm install`, since `react@^16.8.0` is a peer dependency.

thanks, the problem declared in the issue file has been fixed by updating react version to 16.8.0; I ran `npm install formik@next`, and next here refers to (2.0.1-rc.6) version at this time. by the way, how can I see the versioned documentation for V2?

**Comment by denkristoffer** [comment]
I'm seeing the same issue as @jgoux with the same setup. It's possible this has something to do with Parcel's bundling.

**Comment by johnrom** [comment]
@jgoux @denkristoffer the issue you guys are experience is different than the original issue here, so it may be best to create a separate issue for tracking purposes.

(I don't have experience with Parcel so I'm not going to be any help with your issue)
