### ISSUE TITLE
CodeSandbox error in Basic Formik example in Safari

### ISSUE THREAD

**Issue by MysticKnight** [formium/formik#1593]
When I went to your website and followed the link to the demo, it crashed when I clicked on one of the input fields.

I started doing a little research and many examples of Formik from different sources crashed in the same way.

Is Formik still being supported? I can’t imagine I’m the only person seeing this issue. If you need exact error messages, let me know and I’ll post them here.

Formik looks very promising, so I hope I can get some feedback on this.

**Comment by jaredpalmer** [comment]
Far from it

**Comment by jaredpalmer** [comment]
Can you share the link?

**Comment by MysticKnight** [comment]
Thanks for the fast reply. I’ll get you the details and post them here.

**Comment by MysticKnight** [comment]
https://codesandbox.io/embed/zKrK5YLDZ?codemirror=1

If I type in a letter, it crashes. I’m on my iPhone, but I believe it did it on my iMac too.

Error Message:

Unhandled Rejection (TypeError)
undefined is not an object (evaluating 'yupError.inner.length')

**Comment by jaredpalmer** [comment]
I can't seem to reproduce this.

**Comment by MysticKnight** [comment]
I checked it on my iMac and I get the same error...

![screen_shot_01](https://user-images.githubusercontent.com/15038721/59161031-1b562700-8a92-11e9-8e81-60300fc9e778.png)

![screen_shot_02](https://user-images.githubusercontent.com/15038721/59161035-21e49e80-8a92-11e9-84ad-20380b5712a6.png)

**Comment by MysticKnight** [comment]
Why did you close this?

**Comment by TrySound** [comment]
@MysticKnight Which safari version do you have? We may still discuss this with in closed issue.

**Comment by jaredpalmer** [comment]
Can confirm now in Safari.

**Comment by MysticKnight** [comment]
I could see closing this after a day or two if I wasn't being responsive, but I was replying within minutes. Anyway, it works fine with Chrome. It does NOT work with Safari and Safari on my iPhone. Here are the specifics of my environment...

Mac OS 10.14.5
iOS 12.3.1
Safari Version 12.1.1 (14607.2.6.1.1)

**Comment by TrySound** [comment]
Looks like it's codesandbox error.
![image](https://user-images.githubusercontent.com/5635476/59161224-b974dc00-8ae8-11e9-87b4-7da1f1c75094.png)

@CompuIves do you have any ideas why this could happen?

**Comment by jaredpalmer** [comment]
Yep.

**Comment by tannerhallman** [comment]
Still seems to crash. 
Safari 12.1.2

**Comment by bigredwill** [comment]
I was running in to a similar issue where the form submitted on Firefox/Chrome, but not in Safari.  In particular, my issue had to do with accidentally passing an object to the `validate` function on the `Formik` component.

I was calling a function to pass the correct validation function to Formik like so:
```
<Formik validate={validateForm(formType)}  ... />
```
The `validateForm` function that was failing returned an object as the fallback rather than a function that returns an object:
```
const validateForm = (formType) => {
  if (formType === 'email') {
    return validateEmail;
  }
  // here's where the error was occurring
  return  {};
};
```

Here's what `validateForm` should do:
```
onst validateForm = (formType) => {
  if (formType === FORM_TYPE_EMAIL) {
    return validateEmail;
  }
  // need to return a function
  return () => {};
};
```

**Comment by tannerhallman** [comment]
```
<Formik
        initialValues={this.state}
        validationSchema={Yup.object().shape({
          roomName: Yup.string().required('Room name is required!'),
          capacity: () => {
            if (this.state.type !== 'Equipment') {
              return Yup.number()
                .required('Capacity is required!')
                .min(1, 'Must be 1 or more.')
            }
            return Yup.number().min(1, 'Must be 1 or more.')
          },
        })}
.....
```

This is what my `validationSchema` passed in looks like.

**Comment by guiihlopes** [comment]
Using formik submitForm prop to trigger a form submission seems to doesn't work in safari too. When I call submitForm imperatively it's not triggering handleSubmit.
