### ISSUE TITLE
TypeScript Compatibility - Improving back-compat or defining supported versions

### ISSUE THREAD

**Issue by johnrom** [formium/formik#1598]
From @jaredpalmer 👍 

> @johnrom @weswigham Is there a way to programmatically test Formik's types against versions of TypeScript and @types/react. I feel like it would be nice to show a matrix or chart of what TS version we actually support. With adding this unknown to the types I also don't fully understand what happens to users on earlier versions of TS.

ref: https://github.com/jaredpalmer/formik/pull/1559#issuecomment-500225328

**Comment by johnrom** [comment]
I did some digging, and found the following references:

https://github.com/Microsoft/TypeScript/issues/25778
https://github.com/microsoft/TypeScript/issues/22605
https://github.com/microsoft/TypeScript/pull/26568

**Comment by maddhruv** [comment]
Closing due to long inactivity
