### ISSUE TITLE
`isObject` should be defined to narrow the type automatically

### ISSUE THREAD

**Issue by johnrom** [formium/formik#1599]
`isObject` should be defined to narrow the type automatically, like:

```
type NonObject = string | number | boolean | symbol | null | undefined;
const isObject = <T extends object>(maybeObject: NonObject | T): maybeObject is T => 
    typeof value === 'object'; // or whatever isObject's test really is, maybe check for array?
// then
if (isObject(propsOrFieldName)) { // propsOrFieldName is inferred as FieldAttributes<Val> }
```

ref: https://stackoverflow.com/questions/54192291/generic-type-narrowing-via-the-is-operator-and-conditional-types

_Originally posted by @johnrom in https://github.com/jaredpalmer/formik/pull/1555_

**Comment by maddhruv** [comment]
closing as the PR is already merged 💯
