### ISSUE TITLE
Formik 2.0 Field `as` prop

### ISSUE THREAD

**Issue by jdetle** [formium/formik#1601]
## 📖 Documentation
Currently the typescript type here https://github.com/jaredpalmer/formik/blob/next/src/Field.tsx#L29 gives this component access to only the ['field'] props, but why am I disallowed from access to the `form` props? I think knowing why this is would help me understand how I could be using formik better.

**Comment by maddhruv** [comment]
Closing due to long inactivity

**Comment by jaredpalmer** [comment]
The as prop is for element-like components like Styled Components. Otherwise, component or children provide access to the `form` prop you are looking for
