### ISSUE TITLE
Allow non-string values with checkbox lists

### ISSUE THREAD

**Issue by fantapop** [formium/formik#1613]
### Current Behavior

When using Formik V.2 checkbox groups, any value that is put in, is stringified and henceforth not found in the array of existing values.  I tracked this down to using the html input element to store the value which only works with strings.

### Desired Behavior

It would be great to be able to use other types or at least Numbers here.

### Suggested Solution

I don't have any amazing ideas here but for numbers you could stringify the numbers on the way in and then on the way out.  Mixing types gets a little weird here. For example "1" and 1 would have obvious issues.

Another idea here is to use something else as the actual input value such as a string id and then keep a mapping of id => value.  This would allow arbitrary types such as objects to be stored as values.

### Who does this impact? Who is this for?

People using checkboxes and radios.  The current behavior allows erroneously using a non-string type.

### Describe alternatives you've considered

I haven't figured it out yet but I'll probably stringify my numbers on the way in and way out.  I don't have a case where mixed numbers and strings or objects is necessary to use.

**Comment by maddhruv** [comment]
Closing due to long inactivity
