### ISSUE TITLE
Can't use "true" / "false" in grouped checkbox

### ISSUE THREAD

**Issue by fantapop** [formium/formik#1614]
### Current Behavior
Using "true" and "false" as values in a group checkbox does not return an array as defined in the api.

### Expected behavior

<Field name="bools" value="true" />
<Field name="bools" value="false" />

should return an array 

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-zyrjc

### Suggested solution(s)

It looks like the Array.isArray check is missing here:

https://github.com/jaredpalmer/formik/blob/next/src/Formik.tsx#L949

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc5
| React            | 16.8.6
| TypeScript       | 3.5.1
| Browser          | Version 74.0.3729.131 (Official Build) (64-bit)
| npm/Yarn         |
| Operating System |

**Comment by michellekphan** [comment]
Also running into this. 

Notice that the 'jobType' value is simply `true` even when all three options are checked 
![image](https://user-images.githubusercontent.com/52019282/64652178-0f9f3700-d3d8-11e9-8d0c-7fea76efbeab.png)

Tested using the codesandbox provided and replacing the email input with the same example provided in docs for checkbox (https://github.com/jaredpalmer/formik/blob/master/examples/Checkbox.js)

Based on the code comment left in the example, I also expected an array returned:
> Multiple checkboxes with the same name attribute, but different
> value attributes will be considered a "checkbox group". Formik will automagically
> bind the checked values to a single array for your benefit. All the add and remove
> logic will be taken care of for you.

**Comment by johnrom** [comment]
@michellekphan I'm not sure you're having the same issue. I've created a sandbox representing how I'd create a form like the one you depict above:

https://codesandbox.io/s/formik-multicheckbox-httpsgithubcomjaredpalmerformikissues1614-ns3f8

**Comment by michellekphan** [comment]
:) Any chance we'd be able to get a fix for this? I think @fantapop pointed a possible area where a check is missing.

**Comment by johnrom** [comment]
@michellekphan the original issue is about Formik v2, which is still in beta. I think in v1 your best bet is going to be to wire it up yourself. There's an example here:

https://github.com/Andreyco/formik/blob/feature/examples/formik-examples/src/views/examples/CheckBoxesExample/CheckBoxesExample.tsx
https://codesandbox.io/s/o5pw1vx916

And the first issue of this kind: https://github.com/jaredpalmer/formik/issues/363

There may be others too spread throughout the issues here. But in v2, it just works (unless you pass "true" or "false" as a value!)

**Comment by michellekphan** [comment]
@johnrom aweseome - thank you i'll give it a try while waiting for v2 :)

**Comment by krnlde** [comment]
Now that v2 is out, could you retest this?

**Comment by maddhruv** [comment]
Please upgrade to latest (`v2`) with which, this works fine
