### ISSUE TITLE
Performance on validation

### ISSUE THREAD

**Issue by NoureldeanSaed** [formium/formik#1615]
### Current Behavior

When having forms of relatively many (> 30) fields, the validation becomes somewhat annoyingly laggy and the performance becomes frustrating when typing, and that lag is on some high end computers, any slower computers give even worse lag, even more, the lag worsens on Edge browser.

### Expected behavior

The validation process doesn't take that long (~100ms-500ms) and the form acts smoothly 

### Reproducible example

https://codesandbox.io/s/formik-lag-example-r65un

Note: Try the sandbox on the worst computer you've got, or slow down the CPU performance, ideally that shouldn't be the case, but the main problem of this issue is that it is.

### Suggested solution(s)

As far as I know, your form re-renders all fields on many events (onChange, onBlur, onSubmit, your validation event ...etc), and this happens even if we're using `<Field />` with its validation since it still changes the values of the form leading to a full re-render to all other fields.
What you could do, is treat each field of yours as a form of itself, rendering independently, and leaving `values`, `errors`, `touched` and their setters to be handled by whatever state-management-library the developers are using. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik         | ^1.5.1   |
| React          |  16.8.4  |
| TypeScript   |      -      |
| Browser       |  Edge (any) |
| npm/Yarn     |  6.9.0   |
| Operating System | Ubuntu 18.04.2 LTS |

**Comment by ARChilton** [comment]
You could try using <FastField /> https://jaredpalmer.com/formik/docs/api/fastfield

**Comment by jaredpalmer** [comment]
See #1597

**Comment by NoureldeanSaed** [comment]
@ARChilton Can't say I haven't tried that already, but still, there's a correlation between the number of fields in the form and the amount of lag you'll notice, and this doesn't even happen on extremely large (>100 fields) forms, the lag starts becoming noticeable before I hit the 100 fields ceil. After that? Man it becomes a pain to type, I would start typing and then leave the keyboard to watch the screen typing on its own.

**Comment by maddhruv** [comment]
Closing due to long inactivity
