### ISSUE TITLE
Field validate doesn't mark as touched on submit

### ISSUE THREAD

**Issue by MikeSuiter** [formium/formik#1623]
## 🐛 Bug report

In our product we use validationSchema to validate our form but we also allow customers to add their own form fields to it. Since we have no idea what their validation will be it can't be included in our Yup validation, so they need to validate at the Field level. When the form is submitted Formik shows the field as invalid but not as touched like it does with validationSchema. 

### Current Behavior

Fields with validate don't get marked as touched so the error isn't shown as you can see below. Email is Yup validation and Age field validation. 

```
props = {
  "values": {
    "email": ""
  },
  "errors": {
    "age": "Age is required",
    "email": "Required"
  },
  "touched": {
    "email": true
  },
  "isSubmitting": false,
  "isValidating": false,
  "submitCount": 1,
  "dirty": false,
  "isValid": false,
  "initialValues": {
    "email": ""
  },
  "validateOnChange": true,
  "validateOnBlur": true
}
```

![image](https://user-images.githubusercontent.com/5289509/59876742-01f28c00-936a-11e9-9227-044e98f4f588.png)

### Expected behavior

Field marked as touched and error shows.

### Reproducible example

Click on the Submit button and look at the Formik state. Email is validated by Yup and has error and is touched. Age is validated at the field and has an error but is NOT touched. 

[![Edit Formik Yup + field validation bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formikyup-number-validation-bug-9t9ee?fontsize=14)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.8.6
| Yup | 0.27.0

**Comment by sigerello** [comment]
Hey @MikeSuiter, this is a dup of #691 and #738.
In your particular case the workaround is just to specify both fields in `initialValues` option:
```
"initialValues": {
  "email": "",
  "age": "",
}
```

**Comment by maddhruv** [comment]
Closing due to long inactivity
