### ISSUE TITLE
Documentation grammar and spelling review.

### ISSUE THREAD

**Issue by krichter722** [formium/formik#1632]
## 📖 Documentation
Sentences like

> Custom React Components will be passed FieldProps which is same render prop parameters of <Field render> plus any other props passed to directly to <Field>.

from https://jaredpalmer.com/formik/docs/api/field make the documentation hard to read.

**Comment by maddhruv** [comment]
With the latest documentations here - https://formik.org/docs/api/field
We've more described the FieldProps and exactly which props are being passed to the child/custom react component

> Custom React components will be passed onChange, onBlur, name, and value plus any other props passed to directly to <Field>.
