### ISSUE TITLE
Necessary to change the type of initialValues

### ISSUE THREAD

**Issue by Adisey** [formium/formik#1642]
### Current Behavior
   <Formik
                    initialValues={{
                        userLogin: 'user1',
                        password: '11111',
                        remember: false,
                    }}
.... 
I have error
Type '{ userLogin: string; password: string; remember: boolean; }' is not assignable to type 'string'.  TS2322

![image](https://user-images.githubusercontent.com/37780231/60337397-a5b3eb80-99ab-11e9-8acd-28fe15e1ef03.png)

### Expected behavior

initialValues must accept an object

### Suggested solution(s)
src/types.tsx
need change row 65 
from 
- readonly initialValues: Values;
to 
+ readonly initialValues: FormikValues;

### Additional context
Sorry if I did not by the rules.
This is my first issue for a serious system.
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.8.6
| TypeScript       |3.5.1
| Browser          |Chrome 75
| npm/Yarn         | yarn 1.12.3
| Operating System | Windows

**Comment by maddhruv** [comment]
Hey @Adisey Can you try using the latest formik, I don't think this is an error anymore, the initialValues is of an inherit type, so object of any shape is accepted here.

Please try migrating to latest `2.x`, more info here - https://formik.org/docs/migrating-v2 and let us know if there are still some issues.

Feel free to re-open
