### ISSUE TITLE
Reset form not working when call this.props

### ISSUE THREAD

**Issue by wkpuy** [formium/formik#1651]
I want to reset form in componentWillReceiveProps with code " this.props.resetForm();" but not any reset.

`import React, { Component } from "react";
import { connect } from "react-redux";
import { Link } from "react-router-dom";
import { Formik, withFormik } from "formik";
import * as yup from "yup";
import moment from "moment";
import {
  Button,
  Form,
  Input,
  Select,
  Row,
  Col,
  message,
  Spin,
  DatePicker,
  Transfer,
  Alert
} from "antd";
import { GeneralStyledContent } from "../../../../styled/common-styled";
import * as actions from "../actions";
import * as uiActions from "../../../../modules/ui/actions";

const FormItem = Form.Item;
const Option = Select.Option;

class Forms extends Component {
  state = {
    name: "",
    code: ""
  };
  componentDidMount() {
    if (this.props.match.params.id != undefined) {
      this.props.getLocation(this.props.match.params.id);
    } else {
      // console.log("test");
    }

    ///  console.log(this.props);
  }

  componentWillReceiveProps = nextProps => {
    if (nextProps.location.dataLocation.name.length > 0) {
      const {
        dataLocation: { name, code }
      } = nextProps.location;
      this.setState({ name, code });
    }

    if (nextProps.location.status != this.props.location.status) {
      this.props.setFlashMessage("เพิ่มสถานที่", nextProps.location.status);
      //this.props.resetForm();
      //this.props.setValues({ ...this.props.values, name: "" });

      this.props.resetForm();//can' not reset form

      // console.log(this.props);
    }
  };

  render() {
    // const {
    //   dataLocation: { name, code }
    // } = this.props.location;

    const { createLocation, updateLocation, getLocationByID } = this.props;

    const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 8 }
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 10 }
      }
    };

    return (
      <GeneralStyledContent>
        {this.props.flash && (
          <Alert
            message="Warning Text Warning Text Warning TextW arning Text Warning Text Warning TextWarning Text"
            type="warning"
            closable
          />
        )}

        <h3>Create Location</h3>
        <Spin spinning={this.props.location.locationLoading} size="large">
          <Formik
            enableReinitialize={true}
            initialValues={{
              name: this.state.name,
              code: this.state.code
            }}
            validationSchema={yup.object().shape({
            
            })}
            onSubmit={(values) => {
              const loading = true;
              if (this.props.match.params.id != undefined) {
                this.props.updateLocation(values, loading);
              } else {
                this.props.createLocation(values, loading);
              }
            }}
            render={({
              values,
              errors,
              touched,
              handleChange,
              handleBlur,
              handleSubmit,
              handleFocus,
              setFieldValue,
              resetForm
            }) => (
              <Form onSubmit={handleSubmit}>
                <FormItem
                  {...formItemLayout}
                  label="Name"
                  validateStatus={touched.name && errors.name && "error"}
                  help={touched.name && errors.name}
                >
                  <Input
                    placeholder="name"
                    name="name"
                    onChange={handleChange}
                    onBlur={handleBlur}
                    value={values.name}
                  />
                </FormItem>

                <FormItem
                  {...formItemLayout}
                  label="Code"
                  validateStatus={touched.code && errors.code && "error"}
                  help={touched.code && errors.code}
                >
                  <Input
                    placeholder="code"
                    name="code"
                    onChange={handleChange}
                    onBlur={handleBlur}
                    value={values.code}
                  />
                </FormItem>
                <FormItem>
                  <Row gutter={8}>
                    <Col span={3} offset={8}>
                      <Button type="defualt" block>
                        <Link to="/location">Cancel</Link>
                      </Button>
                    </Col>
                    <Col span={3}>
                      <Button type="primary" htmlType="submit" block>
                        Save
                      </Button>
                    </Col>
                  </Row>
                </FormItem>
              </Form>
            )}
          />
        </Spin>
      </GeneralStyledContent>
    );
  }
}
const mapStateToProps = ({ location, auth: { profile }, ui: { flash } }) => ({
  location,
  profile,
  flash
});

const mapDispatchToProps = {
  createLocation: actions.createLocation.request,
  updateLocation: actions.updateLocation.request,
  getLocation: actions.getLocationByID.request,
  setFlashMessage: uiActions.setFlashMessage
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(withFormik({})(Forms));
`

**Comment by maddhruv** [comment]
closing due to long in-activity
