### ISSUE TITLE
How to Use submitForm as props from higher level

### ISSUE THREAD

**Issue by prajavk** [formium/formik#1682]
## 🐛 Bug report
Parent container has Save button to handle form changes (child).

### Current Behavior
Using withFormik(), how to avoid <form onSubmit={handleSubmit}> and handle submit using parent button event handler

### Reproducible example

https://codesandbox.io/s/withformik-codesandbox-template-vz1yu

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5. 7
| React            | 16.8.6
| TypeScript       |
| Browser          |
| npm/Yarn         | 10.15.0
| Operating System | windows

**Comment by jabirhussaintrui** [comment]
@prajavk this is not a formik issue. When you want to submit a form via button outside form childs it has the following steps to do.
1- Set your form an "id" attribute
2- After that set button attribute "form" with your form id name 

i.e 

<button type="button" form="test"></button>
<form id="test"></form>

[Codesandbox link](https://codesandbox.io/s/withformik-codesandbox-template-w65wi)

**Comment by bricejar** [comment]
Please also read about ref forwarding. https://reactjs.org/docs/forwarding-refs.html

**Comment by maddhruv** [comment]
Closing due to long inactivity
