### ISSUE TITLE
ArrayHelper => No ability to "reset" the array

### ISSUE THREAD

**Issue by slorber** [formium/formik#1685]
Hi,

In V1 and V2 there is no way to reset the array.

I think it would be convenient to be able to:
- empty the value/touched/error arrays
- reset the arrays to a given list of values (with touched/errors can be emptied)

I'm thinking of an api like this:
- arrayHelper.reset();
- arrayHelper.reset("value1","value2")

I can submit a PR if feature/api is validated

**Comment by bricejar** [comment]
Hi,

You can use setField for that, however I agree that it would be convenient to be able to do that directly with the arrayHelpers.

**Comment by slorber** [comment]
Hi,

Will setField() also reset the error/touched arrays?

**Comment by maddhruv** [comment]
Closing due to long inactivity
