### ISSUE TITLE
Remove non-free fonts from the repository to avoid copyright issue

### ISSUE THREAD

**Issue by silverhook** [formium/formik#1686]
I noticed that with https://github.com/jaredpalmer/formik/pull/1671 new fonts got pulled into the repository.

Looking at the contents of the `.ttf` fonts in [website/static/fonts/](https://github.com/jaredpalmer/formik/tree/master/website/static/fonts), it looks like these are either derivative/modified or simply rebranded [Maison Neue typeface by Milieu Grotesque], that as far as I can see can only be obtained under a proprietary EULA, which seems to [explicitly forbid modifying and/or publicly making the fonts available for download](https://www.milieugrotesque.com/info/#).

If this is indeed the case then it is likely that publication of these font files in this repository could constitute a copyright infringement and it would be very prudent to remove them from the repository.

**Comment by maddhruv** [comment]
Closing due to long inactivity, feel free to re-open

**Comment by silverhook** [comment]
Just checked again, the problem indeed seem to have gone away, at least in master. Thanks for triaging.
