### ISSUE TITLE
setFieldValue not working when called too early

### ISSUE THREAD

**Issue by the-clx** [formium/formik#1707]
### Current Behavior

Calling setFieldValue on first render doesn't trigger update. It also occurs when calling it in child components componentDidMount methods

### Expected behavior

It should update field value.

### Reproducible example

https://codesandbox.io/embed/formik-setfieldvalue-not-working-d3fyk

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.8

**Comment by bricejar** [comment]
Can we get access to the sources please ? Could you create a codesanbox link ?

**Comment by the-clx** [comment]
Hi. Sorry, this is first time I'm sharing something from sandbox :). It's proper now.

**Comment by bricejar** [comment]
I am trying to understand the use case. Why don't you provide the value directly in initialValues ?

**Comment by the-clx** [comment]
We have component rendered inside Formik and that calls it on componentDidMount, but it does not work there either.

I think that if it's available it should work regardless of use case, or there might be note in documentation why shouldn't we call it early.

**Comment by bricejar** [comment]
In React, children are mounted before the parent. So your componentDidMount fires before Formik is mounted.

**Comment by bricejar** [comment]
![image](https://user-images.githubusercontent.com/45051524/61879926-f1ca5100-aec1-11e9-8d17-28ce920f7589.png)

This function Component works.

**Comment by bricejar** [comment]
You are not supposed to udpate a state in a render function.

**Comment by bricejar** [comment]
More about key resets : https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#alternative-2-reset-uncontrolled-component-with-an-instance-method

**Comment by maddhruv** [comment]
Closing due to long inactivity
