### ISSUE TITLE
When installing formik on a create-react-app typescript project, it deletes some of the @types folders like "react"

### ISSUE THREAD

**Issue by arielvol** [formium/formik#1711]
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by maddhruv** [comment]
Closing due to long inactivity

**Comment by maddhruv** [comment]
Closing due to long inactivity
