### ISSUE TITLE
Add a way to run Yup validation in strict mode

### ISSUE THREAD

**Issue by PatoBeltran** [formium/formik#1727]
## 🚀 Feature request

Currently the code in `validateYupSchema` only sets the `abortEarly` and `context` options. I have a case where I need to mutate my form schema only on cast and not on every validation, so being able to set the `strict` option to yup validation would be useful.

Could it be possible to expose the validation options so that I can specify the validation needed? This could be as props to the formik component or with whatever method is easier.

Here is the yup docs that explain the validation options: https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror

And this is the code that would need to pass in the exposed options:

```
/**
 * Validate a yup schema.
 */
export function validateYupSchema<T extends FormikValues>(
  values: T,
  schema: any,
  sync: boolean = false,
  context: any = {}
): Promise<Partial<T>> {
  let validateData: FormikValues = {};
  for (let k in values) {
    if (values.hasOwnProperty(k)) {
      const key = String(k);
      validateData[key] = values[key] !== '' ? values[key] : undefined;
    }
  }
  return schema[sync ? 'validateSync' : 'validate'](validateData, {
    abortEarly: false,
    context: context,
  });
}
```

**Comment by maddhruv** [comment]
Not sure if exposing all the yup Options be right here, as more options can make things go complex around the core APIs.

For now, I would recommend you to use custom validation/form validation, more info here - https://formik.org/docs/guides/validation

where you can easily write custom yup validations and also pass the corresponding `strict` checks
