### ISSUE TITLE
How to write unit test case for FieldArray?

### ISSUE THREAD

**Issue by vineet-agrawal96** [formium/formik#1791]
HI

I'm writing Unit Test case for my application. I used formik in my application. I'm facing a case how to write unit test case for FieldArray Component. I'm sharing my component code, unit test case and console message:-

My component code is:-

`
import React, { Component } from "react"
import PropTypes from "prop-types"
import Grid from "@material-ui/core/Grid"
import { withStyles } from "@material-ui/core/styles"
import { Field, FieldArray } from "formik"
import FieldTypeSelector from "./components/FieldTypeSelector"
import FormikCheckbox from "components/forms/formikFields/FormikCheckbox"
import { settingStyles } from "../../../../../common/Styles"
import EditableField from "./components/EditableField"

export class AdditionalCustomFields extends Component {
  renderFields = () => {
    const { classes, values } = this.props
    const { additionalData } = values

    return (
      <FieldArray
        name="additionalData"
        render={props => {
          return additionalData.map((field, index) => {
            return (
              <Grid item md={3} key={field.id} className="pt-0">
                <Field
                  name={`additionalData.${index}.flag_active`}
                  component={FormikCheckbox}
                  className="my-3 mb-0"
                  inputprops={{ maxLength: 80 }}
                />
                <EditableField
                  field={field}
                  index={index}
                  classes={classes}
                  additionalData={additionalData}
                />
                <FieldTypeSelector
                  field={field}
                  index={index}
                  {...this.props}
                />
              </Grid>
            )
          })
        }}
      />
    )
  }

  render() {
    return (
      <Grid container>
        {this.renderFields()}
      </Grid>
    )
  }
}

AdditionalCustomFields.propTypes = {
  classes: PropTypes.object.isRequired
}

export default withStyles(settingStyles)(AdditionalCustomFields)

`

Test case for above component:-
`
import React from "react"
import { shallow } from "enzyme"
import { AdditionalCustomFields } from "./index"
import { additionalData, customFieldData} from "../../../../mockData"
import { settingStyles } from "../../../../../common/Styles"
import { withStyles } from "@material-ui/core/styles"
import PropTypes from "prop-types"

const props = {
       values : {
        additionalData,
        customFieldData
       }
}

const Composer = ({ classes}) =>{
    return <AdditionalCustomFields classes={classes} {...props}/>
}

Composer.propTypes = {
    classes: PropTypes.object.isRequired
  }
  
const Composition = withStyles(settingStyles)(Composer)

describe("Composer",()=>{
     const wrapper = shallow(<Composition />).dive().find(AdditionalCustomFields).shallow()

     it("Describe CustomFieldForm component",()=>{
         console.log("sub component========>", wrapper.debug())

    })
})

`

console showing 

`
Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 7 passed, 8 total
Snapshots:   0 total
Time:        12.114s
Ran all test suites related to changed files.

PASS src/pages/Settings/components/Application/components/CustomFields/components/CustomFieldForm/component/AdditionalCustomFields/AdditionalCustomFields.test.js
  ● Console

    console.log src/pages/Settings/components/Application/components/CustomFields/components/CustomFieldForm/component/AdditionalCustomFields/AdditionalCustomFields.test.js:31
      sub component========> <WithStyles(ForwardRef(Grid)) container={true}>
        <FormikConnect(FieldArrayInner) name="additionalData" render={[Function: render]} />
      </WithStyles(ForwardRef(Grid))>

PASS src/pages/Settings/components/Application/components/CustomFields/CustomFieldsQyery.test.js (11.856s)
PASS src/pages/Settings/components/Application/components/CustomFields/CustomFields.test.js (8.129s)
PASS src/pages/Settings/components/Application/components/CustomFields/components/CustomFieldForm/CustomFieldsForm.test.js
PASS src/pages/Settings/components/Application/components/CustomFields/components/CustomFieldForm/component/CustomFields/CustomFields.test.js

Test Suites: 5 passed, 5 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        14.029s
Ran all test suites related to changed files.
`

**Comment by maddhruv** [comment]
we've certain test cases already written in the repo for `FieldArray` can you give them a try - https://github.com/formium/formik/blob/master/packages/formik/test/FieldArray.test.tsx
