### ISSUE TITLE
getSelectedValues throws an error when using a select-multiple

### ISSUE THREAD

**Issue by bmccord** [formium/formik#1838]
### Current Behavior

getSelectedValues throws an error because options is a HTMLOptionsCollection and not an array.  getSelectedValues tries to do a .filter on the options, but since it isn't an array, that call fails.

### Expected behavior

I would expect the function to complete without error.  Thereby making select multiple lists work properly.

### Reproducible example

This can actually be demonstrated by running the Checkbox example form from the examples folder in Github

### Suggested solution(s)

If you convert the options object to an array, it works properly.  The following code works, but there may be a better way:

```
return Array.apply(null, options).filter(function (el) {
    return el.selected;
  }).map(function (el) {
    return el.value;
  });
```

### Additional context

None

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.13
| React            | 16.9.0
| TypeScript       | Not using
| Browser          | All
| npm/Yarn         | 6.11.3
| Operating System | OSX - Mojave

**Comment by maddhruv** [comment]
With the recent edition, the `getSelectedValues` accepts an array a param and should now cause any problem. I see you are using formik `rc` which is not supposed to be a stable release, can you try with the latest formik release (probably `2.2.0`)
