### ISSUE TITLE
Introduce Fields For Validation Only

### ISSUE THREAD

**Issue by o-aloqaily** [formium/formik#1862]
### Current Behavior

When a field is added to the form, its value is kept in the values object of the form even if we don't need that value to be maintained

### Desired Behavior

If a field is a temporary field that was created for validation purposes only (like checkboxes for confirmation) or any other purpose that does not require that value to be stored, we should at least have a way to specify that behavior (specifiying which fields to be maintained).

### Suggested Solution

Passing a prop to the field indicating whether this field is stateful (Should its value be maintained?)

### Who does this impact? Who is this for?

This can be useful to make the code scalable.
Sometimes we don't need to keep the state of a field, especially if it was created for validation/confirmation purposes (e.g. a checkbox saying "Agree to Terms of Service?"). And keeping its state might cause problems in certain situations

An example: Using GraphQL API's forces not sending extra fields which were not defined in the GraphQL schema to the backend, we were in a situation where we had to send the values object of formik to the function that calls the api directly and that caused problems since there are values in the object which were not meant to be sent, and deleting values from the object manually will increase the complexity of the code

### Describe alternatives you've considered

Naming the fields as: "temp.fieldName" then deleting the object "temp" from the values object right before submission

**Comment by niksumeiko** [comment]
We also have a use case for this. We have a form with radio inputs at the top. Depending on which is selected, we render some optional fields. We don't wish to pass selected radio input value to an API (as an extra field).

Our current solution is React context API. We store selected radio input value there. This way radio input field doesn't belong to Formik and, therefore, no getting submitted to an API. 
 
This solution introduces another separate state (beyond Formik). Perhaps, it would make sense to think about how this concept could be adapted to Formik API to store temporary values. Even these which doesn't have corresponding fields.

**Comment by johnrom** [comment]
I personally think both of your solutions are the ideal solutions. 1, if you don't want your state in Formik, use Context. 2, if you do want your state in Formik, just remove it at the end via `onSubmit={({discardedValue, ...values}) => doSubmit(values)}`.

I don't think there's any benefit to creating any API based around this use case, since it's probably easier to do it manually than to maintain complicated value-discarding logic in Formik.

**Comment by o-aloqaily** [comment]
@niksumeiko Your approach is viable too. However, the only problem with it is you can't use Yup + Formik validation for fields you keep in context API, I suppose.

My approach was as I mentioned in the thread and exactly what @johnrom mentioned as 2nd approach, you can use Yup + Formik for validation following this approach as the values are still included in Formik state.

I guess he is right, there is no need to create a supported API for this use case. Anyways, maybe someone can land on this page and benefit from this discussion.
