### ISSUE TITLE
Better way to change value of custom input

### ISSUE THREAD

**Issue by nicolas-besnard** [formium/formik#1868]
## 🚀 Feature request

Introduce an easiest way to define the value of a custom field. When your custom input is not using the default `event`, you'll need to call `setValues` on the `form`. What if we could call `setValue` on `field`?

### Current Behaviour

```js
const CustomField = ({ name }) => {
  return (
    <Field name={name}>
      {fieldApi => {
        return <input name={name} onChange={e => fieldApi.form.setValues(name, 'value')} />;
      }}
    </Field>
  );
};
```

### Desired Behaviour

```js
const CustomField = ({ name }) => {
  return (
    <Field name={name}>
      {fieldApi => {
        return <input name={name} onChange={e => fieldApi.field.setValue("VALUE")} />;
      }}
    </Field>
  );
};
```

### Suggested Solution

Add a new function to `FormikBag` that include this new method

### Who does this impact? Who is this for?

It impacts every person creating custom input without using the default `event` and allows them to easily change a field value without duplication the field's name

### Describe alternatives you've considered

Using the `setValues` on the `form` :(

**Comment by maddhruv** [comment]
Hey @nicolas-besnard with the new `setValues` API you can directly pass the value as the first param

If you have not yet migrated to `2.x`, please give it a shot
