### ISSUE TITLE
Clearing individual field throws Warning

### ISSUE THREAD

**Issue by ZeroDarkThirty** [formium/formik#1878]
## ❓Question

Is there a way I can conditionally clear out a field based on two radio button group of 2 items? 

The first item renders the field. Clicking the seond one should remove the field, along with the content of the field. I did the follow formikProps.setFieldValue("FieldName", ""), when the second button is clicked. 

But this is throwing the following warning:
`Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state. `

**Comment by maddhruv** [comment]
closing due to long inactivity. If the problem still persists, we recommend you to use the new hooks API for setFieldValue
