### ISSUE TITLE
How to clear field after field hide?

### ISSUE THREAD

**Issue by wzup** [formium/formik#1912]
## ❓Question

I have conditional input: a radio button and a text area.

If I turn radio button ON, the TextArea appears. And If I turn radio button OFF, the text area disappears.
```
[ ON | x ]
<TextArea>...</TextArea>

[ x | OFF ]
// no TextArea
```

Problem with Formik now is that if I populate a TextArea when radio button is ON, and then I hide a TextArea (click radio button OFF) I expect TextArea to be clear. But it is not. It keeps user input. So how to clear TextArea on hide?

Here is algorithm:

1. Turn radio button ON.
2. <TextArea> appears.
3. Fill in TextArea with text
4. Turn radio button OFF
5. Turn radio button ON
6. BOOM. Text in TextArea remains. Must disappear.

**Comment by maddhruv** [comment]
In formik 2, you can easily use the setValues hook to change the values of certain fields. So, in your case - where you are handling the logic for textarea hide/unhide with radio handler, just try setting the textarea value to null/empty string to achieve your expected behaviour

**Comment by jeevinck** [comment]
onChange={(e)=>{formik.setFieldValue('spouseName',formik.values.maritalStatus === '0' ? "" :e)}}

This is not working
