### ISSUE TITLE
Error at passing Object to HandleChange

### ISSUE THREAD

**Issue by JulioCRFilho** [formium/formik#1973]
## 🐛 Bug report
I'm trying to save an Object on form.values to work with it later on a Query.
The problem is, even I have used it on other project, this time it gives this error: 

[handleChange error](https://i.stack.imgur.com/pqcOD.png)

Anyone has some clue about this?

The specific line I'm inputting this is this one: 
`onChange={form.handleChange('MultipleSelect')({})}`
where "{}" is the object I'm passing to it...

I'm not sure, but I think it is not finding the '_eventOrTextValue' function...

I have tried passing integers, objects, arrays, but the only kind of value it accepts is string... Oddly I used this same mirrored function on other project the exactly same way...

Thanks.

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.0.3
| React            | 16.9.0
| TypeScript       | --
| Browser          | --
| npm/Yarn         | Yarn
| Operating System | Ubuntu 19.10

**Comment by Unforgiven-wanda** [comment]
Having the same issue. This used to work fine on Formik@1.5.2, I am only having this issue on Formik V2.

**Comment by oTodi** [comment]
It seems that this function has changed to only handle events. For values you should you setFieldValue now, it's pretty the same actually

**Comment by johnrom** [comment]
We should accept object values. It's esp. an issue for third parties like React Select that expect an object value (though I question their API choice in this regard)

**Comment by JulianKingman** [comment]
Was this fixed? Why was it closed? I just upgraded from 1x to 2, and `handleChange("fieldName")(true)` gives me the "cannot read property 'type' of undefined" error. Is there a solution or workaround?

**Comment by johnrom** [comment]
@JulianKingman OP closed their own issue. Feel free to open a new issue if one doesn't exist already (check the search!).
