### ISSUE TITLE
Docs incorrectly use placeholder attribute in Field component

### ISSUE THREAD

**Issue by fichorka** [formium/formik#1996]
## 📖 Documentation
There's a [section in the official docs](https://jaredpalmer.com/formik/docs/api/field#as), which I think is incorrect. The Field component is passed an `as='select'` prop, and the `placeholder` attribute, but the placeholder doesn't render because the browsers don't support such attribute on select element.

This is the opening tag of component in question: `<Field name="color" as="select" placeholder="Favorite Color">`

And [here's a link to the sandbox](https://codesandbox.io/s/formik-placeholder-issue-9r46r)

**Comment by RoosterH** [comment]
Any idea how to make it work? I tried many ways but can never put the placeholder value in select field.

**Comment by gamarobert** [comment]
> Any idea how to make it work? I tried many ways but can never put the placeholder value in select field.

did you ever figure this out?

**Comment by RoosterH** [comment]
> > Any idea how to make it work? I tried many ways but can never put the placeholder value in select field.
> 
> did you ever figure this out?

After further investigation, I don't think it's actually supported.
