### ISSUE TITLE
enableReinitialize and Errors

### ISSUE THREAD

**Issue by maganuk** [formium/formik#2026]
My formik component has a enableReinitalize property and my form has initial values set as follows:

    initialValues={{
          firstName: userInfo.firstName || '',
          lastName: userInfo.lastName || '',
          companyName: userInfo.companyName || ''
        }}

userInfo is coming from redux. 

In my handle submit function I'm making an API call. If the call succeeds everything is good, however if the call fails I need to add errors to the fields (these are returned by the API). 

In my catch method I'm trying to do formik.setFieldError, however the form does not show these errors because it is prestine since the userInfo has also changed. Any way to force the form to show these errors?

**Comment by maddhruv** [comment]
Hey @maganuk setting `enableReinitalize` will cause the whole form to reset when the props change. There is no way to keep the errors safely stored somewhere and represent again.

Closing as there is no workaround or way to do this right now, feel free to re-open for further discussions

**Comment by martinhorak** [comment]
Is there some workaround to this problem yet?
