### ISSUE TITLE
resetForm handler doesn't work same at formik 2 version

### ISSUE THREAD

**Issue by krailler** [formium/formik#2034]
## 🐛 Bug report

With formik 1, when we use resetForm handler and we don't pass nextValues, it uses initialValues from props. You can see this behavior in https://github.com/jaredpalmer/formik/blob/version-1.5.8/src/Formik.tsx#L532

But, with formik 2, when we use resetForm handler and we don't pass nextValues, it uses initialValues from a ref and this ref is only updated when the initialValues changes and the variable enableReinitialize is true. You can see this behavior in https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L362

### Current Behavior

resetForm handler uses initialValues from ref using formik 2.

### Expected behavior

Use initialValues from props when we use resetForm handler, same as formik 1.

### Suggested solution(s)

I don't know if this is an issue or the correct behavior. I need to know if the formik 1 resetForm behavior is the correct (And fix it in formik 2) or the actual behavior is correct and it's a bug with formik 1.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.4
| React            | 16.11.0
| TypeScript       | 3.7.2
| Browser          | Google Chrome 78.0.3904.97 (64-bit)
| npm/Yarn         | npm 6.12.0
| Operating System | macOS Catalina 10.15

**Comment by AlberErre** [comment]
up!

**Comment by krailler** [comment]
Hi @jaredpalmer, can you see this, please? 🙏

**Comment by akonyer** [comment]
I'm trying to upgrade to formik v2.0 and I'm having the same error. I think until this is sorted out I have to revert back to v1 for now

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by sw-yx** [comment]
should close since PR merged
