### ISSUE TITLE
How to stop validation on disabled fields upon submit

### ISSUE THREAD

**Issue by mourohi** [formium/formik#2071]
## ❓Question: Formik is displaying errors to field which are disabled on submit. How to avoid that. 
My requirement is I have two radio buttons A and B  and two drop downs A and B. If I click on radio button A, Dropdown B should be disabled and on submit B error message should not be there

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by jaredpalmer** [comment]
I don’t think this is possible at the moment

**Comment by austinpickett** [comment]
also looking for a similar functionality...

To get around this for the time being I've found this case:

Generally if you are making a field disabled you are relying on some form of
```
<Field
  ...
  disabled={isDisabled}
/>
```

Which I have reused in my validationSchema to return true if isDisabled is true
