### ISSUE TITLE
[v2] FormikBag no longer has `props`

### ISSUE THREAD

**Issue by ZachStoltz** [formium/formik#2121]
Looking at the documentation and the code via v1.5.8 the `Formik` component would pass props along side the imperative methods to the action methods ex `onRest`.  Those props were removed in the v2 refactor.

Was this intended?  The documentation still states that a subset of props should be there.

Reason I ask is I currently have a need to when the `onReset` fires, check for `dirty`.  If the form is `dirty` to then pop up a confirmation dialog for the user to accept the changes being reset and ultimately swap states of the form being editable to readonly.

**Comment by maddhruv** [comment]
closing due to long inactivity, feel free to re-open
