### ISSUE TITLE
Formik bad initialValues between 2 forms react native

### ISSUE THREAD

**Issue by anthowm** [formium/formik#2137]
## 🐛 Bug report

The bug is explained well here https://stackoverflow.com/questions/59392023/formik-bad-initialvalues-between-2-forms

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.8
| React            | 16.9.0
| TypeScript       | -
| Browser          | andriod/ios
| npm/Yarn         | npm
| Operating System | macos mojave

**Comment by maddhruv** [comment]
closing due to long in-activity. Feel free to re-open if the problem still persists
