### ISSUE TITLE
version 2 migration guide does not include removal of setError

### ISSUE THREAD

**Issue by isoadam** [formium/formik#2190]
The version 2 migration guide does not document the removal of `setError` from form (not field) actions

Listing this as a breaking change may assist users migrating to version 2

https://github.com/jaredpalmer/formik/blob/master/packages/formik/MIGRATING-v2.md

**Comment by maddhruv** [comment]
Thanks @jcolbyfisher for raising the wonderful PR 🎉 
closing the issue now
