### ISSUE TITLE
Submitting form outside form in react-native is not working

### ISSUE THREAD

**Issue by MakhouT** [formium/formik#2199]
Hi @jaredpalmer 

### Current Behavior
I have a form with 1 textinput and 2 button. The textinput and the search button are being used to trigger a search.
The second button is to open up the camera, scan a QR code and then fill in the textinput with the data found in QR code. The described behavior is currently working as expected.

**The problem** I am having is that when I fill in the textinput with the data from the QR with `setFieldValue`, I also instantly want to trigger a submit of the form. I tried multiple things like calling `handleSubmit`, `await submitForm()` and `setSubmitting(true)`.

The strange part is when I submit the form 2 times in code then my search is being triggered, so I know it's not my validation. I also logged out my validation.

### Expected behavior

I expect that when I call `handleSubmit`, that my form is being submitted.

### Reproducible example

The codesandbox is only for react not for react-native. I'll provide a code snippet.

```js
// Parent component
  const ctaSearch = (query: string) => {
    console.log('got here');
    if (searchedQuery !== query) {
      Keyboard.dismiss();
      searchPart(query);
      setSearchedQuery(query);
    }
  };
...
 <Formik
      initialValues={{ search: searchedQuery }}
      component={SearchPartFormComponent
      onSubmit={values => ctaSearch(values.search)}
      validateOnMount
      validationSchema={validationSchemaSearchPartForm(t)}

/>
...
```

```js
// SearchPartFormComponent
export const SearchPartFormComponent = props => {
  // Get attributes from formik out of the props by destructuring
  const {
    values,
    errors,
    touched,
    isValid,
    handleBlur,
    handleChange,
    handleSubmit,
    setSubmitting,
    submitForm,
    setFieldValue,
  } = props;
  const SEARCH_FIELD = 'search';

  // This is the callback that gets triggered when the QR code gets scanned
  const qrScanned = async (data: string) => {
    setFieldValue(SEARCH_FIELD, data); // Works
    await submitForm(); // Doesn't submit
    popScreen(CONSTANTS.DRAWER_COMPONENT); // Works
  };

  const onPressCameraButton = () => {
    pushScreen(
      CONSTANTS.DRAWER,
      CONSTANTS.CAMERA_COMPONENT,
      'Scan a part number',
      { scan: true, dataScanned },
      false,
    );
  };

  return (
    <>
     // This opens up the camera to scan a QR code
      <TouchableHighlight onPress={onPressCameraButton}>
        <Image source={ICONS_MAP.QR} />
      </TouchableHighlight>

      <Input
        name={SEARCH_FIELD}
        values={values}
        errors={errors}
        touched={touched}
        handleBlur={handleBlur}
        handleChange={handleChange}
        handleSubmit={handleSubmit}
      />

      <Button
        onPress={handleSubmit}
        label='search'
      />
    </>
  );
};
```

### Suggested solution(s)
- Make sure the form is being submitted 👍 

I hope you have enough details for this now?
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.1
| React            | 16.9.0
| React-native  | 0.61.4
| TypeScript       | 3.7.2
| npm/Yarn         | Yarn
| Operating System | Mac Os

**Comment by jaredpalmer** [comment]
Can you make a snack on https://snack.expo.io?

**Comment by MakhouT** [comment]
I was reproducing this issue, then I started looking a bit more into it and I found the issue....
https://github.com/jaredpalmer/formik/issues/529

**Comment by maddhruv** [comment]
Closing due to long inactivity
