### ISSUE TITLE
Warning in console when testing Formik v2 with RTL, 

### ISSUE THREAD

**Issue by lourenci** [formium/formik#2202]
### Current Behavior

The Formik v2 is showing warnings in the console when testing with `react-testing-library`. This is not a thing on Formik v1.

### Expected behavior

The console should be clear.

### Reproducible example

The same component tested in the same way in both versions:
[Formik v1.5.8](https://codesandbox.io/s/formik-158-6veus?expanddevtools=1&fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.spec.js&previewwindow=tests&theme=dark)
[Formik v2.1.1](https://codesandbox.io/s/formik-211-0sdj3?expanddevtools=1&fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.spec.js&previewwindow=tests&theme=dark&view=editor)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.1
| React            | 16.12.0
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by maddhruv** [comment]
Hey @lourenci I ran test in the formik repo, which is using `@testing-library/react`(`react-testing-library`) as testing framework, I am not able to observe any unexpected console warnings.
can you be more specific on what warnings are show, maybe share a screenshot or log snippet?

closing this for now, feel free to re-open
