### ISSUE TITLE
[v2]: Field level asynchronous validation does not work

### ISSUE THREAD

**Issue by kissthom** [formium/formik#2206]
### Current Behavior

From Formik 2.0.1 (with current version 2.1.2 as well) field level asynchronous validation does not work as expected. Although throwing a string in the returned promise formik's errors state will not be updated with thrown error and as a consequence the value recognised as a valid value and form submission is possible.

### Expected behavior

If string is thrown in the asynchronous validation function, formik errors should be updated with the error.

### Reproducible example

I basically copied the example from the documentation and created a codesandbox from it.  (https://jaredpalmer.com/formik/docs/api/field#validate)

https://codesandbox.io/s/formik-v2-field-validation-async-problem-uv3we

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | from 2.0.1 to 2.1.2
| React            |  16.12.0
| TypeScript       | 
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by LrVch** [comment]
You should return error in the validation fucntion.

[](https://codesandbox.io/s/formik-v2-field-validation-async-problem-forked-p8nlr?file=/src/App.js:250-268)

**Comment by kissthom** [comment]
@LrVch: Thank you! It works indeed that way so I'm closing the issue.

And a documentation got also updated several months ago:
https://github.com/formium/formik/commit/fca605e5aa5429c48d5b666aa8146a294307e3c4
