### ISSUE TITLE
Validation on blur for certain <Field>s

### ISSUE THREAD

**Issue by X-Tender** [formium/formik#2261]
Is it possible to tell a `<Field>` that it only validates on blur while all other `<Field`>s are validated by input change? As far as I can read in the documentation you can only specify it in the `<Formik>` element which would change it for all `<Field>`s

**Comment by maddhruv** [comment]
Hey @X-Tender there are currently two ways of handling `onBlur` events and validations:
- add the `validationOnBlur` prop to the `Formik` props - https://formik.org/docs/api/formik#validateonblur-boolean
- and for a particular field specific handling, you can use the `onBlur` handler and call the validation method in the callback, more info here - https://formik.org/docs/api/useField#fieldinputpropsvalue
