### ISSUE TITLE
getComponent()

### ISSUE THREAD

**Issue by ifokeev** [formium/formik#227]
Hello. I noticed if you build Formik with `withFormik` HOC then you have your Formik form wrapped with `C` component – that's why you can't get `ref` of your actual Formik component so you can't call `submitForm()`. That's very strange behaviour and I was forced to build form with Formik component to achieve `ref`  myself. 

I'll come back later with details.

**Comment by jaredpalmer** [comment]
@ifokeev this wrap is how React Router's route works. Can we expose a `getComponent()` like redux-form?

**Comment by daggmano** [comment]
@jaredpalmer I thought I saw a post recently where this issue had been resolved (at least, the ability to get the `Formik` component from a `withFormik` object. Is that correct, or did I misread something?

**Comment by daggmano** [comment]
@jaredpalmer Can you provide any update to this issue?

**Comment by jaredpalmer** [comment]
Yeah let's merge this.

**Comment by prichodko** [comment]
This will be fixed in 2.0  using `React.forwardRef`. @jaredpalmer should this workaround be included in v1 or we can close?

**Comment by jaredpalmer** [comment]
I think we want to lock in 1.0 and move all dev to 2.0 (post React conf)

**Comment by daggmano** [comment]
@jaredpalmer Any update on a possible timeframe for the 2.0 release?

**Comment by jaredpalmer** [comment]
2.0.0 canary is out. `npm i formik@canary`
