### ISSUE TITLE
Field Level validation with useFormik

### ISSUE THREAD

**Issue by gaelbonjour** [formium/formik#2271]
## ❓Question

What is the proper way to iplement field level validation with the `useFormik`hook ?

It feels like it is intended for the `validate` prop passed to `useFormik` to have two params : the values and the currently validating field name. Isn't that so ?
based on this line : https://github.com/jaredpalmer/formik/blob/5e9440230571df1fe1706a6e52a60df2ff711bde/packages/formik/src/Formik.tsx#L187

However i read : 

https://github.com/jaredpalmer/formik/blob/5e9440230571df1fe1706a6e52a60df2ff711bde/packages/formik/src/Formik.tsx#L302

Shouldn't this call to `runValidateHandler` also pass the `field` so the `validate` given as prop to `useFormik` could check what field is being checked ?

**Comment by johnrom** [comment]
I think this is a duplicate of #512 

Currently we validate all Fields and the form itself whenever we validate Formik (using `runAllValidations`).

**Comment by maddhruv** [comment]
Closing as Duplicate
