### ISSUE TITLE
Update Local Setup Tutorial in v2.1.4 Docs

### ISSUE THREAD

**Issue by auginator** [formium/formik#2282]
### Tutorial Local Dev Instructions for v.2.1.4 
I was running through the tutorial, and I noticed that the instructions refer to different source files than the CodeSandbox used in the web-based flow (a tick-tack-toe board).

I forked the repo and took a stab at updating the tutorial's instructions for local setup to create a starter environment based on the [codesandbox used for the rest of the tutorial](https://codesandbox.io/s/formik-v2-tutorial-start-s04yr):
 
- Updated copy and URLs to indicate starter source files should be copied from codesandbox.
- Added NPM/yarn instructions for adding all dependencies used in the tutorial (e.g. `yarn add formik yup @emotion/core @emotion/styled`)

Hope it is helpful! If not, no worries 👍 

*Commit:* 
https://github.com/auginator/formik/commit/9dbb6f8b5d5d4176f873b741215f22906111feaa

*Branch:* 
https://github.com/auginator/formik/tree/fix-docs-local-tutorial

**Comment by maddhruv** [comment]
Hey @auginator would you like to raise a PR for the same? would be really appreciated.

**Comment by auginator** [comment]
Hi @maddhruv - Sure thing. I originally had opened a PR for it back in Feb, but I closed it recently after not seeing any movement on it.

**Comment by jaredpalmer** [comment]
Can you re-open?

**Comment by auginator** [comment]
Yup! Looks like I have to resolve some conflicts with master.

**Comment by jaredpalmer** [comment]
Actually i think this is fixed now. I fixed this when I re-did the docs

**Comment by jaredpalmer** [comment]
Okay, let's fix then

On October 28, 2020, GitHub <notifications@github.com> wrote:
> Hi @maddhruv <https://github.com/maddhruv> - Sure thing. I originally

> had opened a PR for it back in Feb, but I closed it recently after not

> seeing any movement on it.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/formium/formik/issues/2282#issuecomment-718095545>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AA67IG56OT2NGOLEXOE4DPTSNBJAVANCNFSM4KS2VNKQ>.
