### ISSUE TITLE
What is the current way of defining the ref for an innerRef attribute using TypeScript?

### ISSUE THREAD

**Issue by ProteanCode** [formium/formik#2290]
## ❓Question

Currently the innerRef has signature of `(instance: any) => void` which does not fit any type I can remind of, like `FormikProps` or `FormikHelpers`

Before that when I was using the 1.5 version where I could call methods like `setFieldTouched` on the ref therefore an inner Ref should be of type `FormikHelper` or at least inherit it. The `(instance: any) => void` looks broken

**Comment by ProteanCode** [comment]
Since TypeScript is not really helpful i used `as` casting.

`<Formik innerRef={instance=>{formikRef=instance}}` {...otherProps}/>`

This however makes a non-constant `formikRef` variable

`let formikRef = useRef(null) as any;`

I do not think this is correct way with 2.x

**Comment by johnrom** [comment]
We do currently use any. You are free to open a PR to change the innerRef to the signature that I wrote for useRef here: #2222

**Comment by ProteanCode** [comment]
`TypeError: formikRef.setFieldTouched is not a function`

**Comment by johnrom** [comment]
@ProteanCode are you using `innerRef`? My PR using `ref` itself is a draft, but you can take the same types I used to implement `useRef` to open a PR for innerRef, and it might be accepted, which should solve your issue with `any`.

**Comment by TeoTN** [comment]
This is how I define it:

```
export type FormikRef<FormValues> = Ref<FormikProps<FormValues> | undefined>;

import React, { MutableRefObject, useCallback, useImperativeHandle, useRef } from 'react';
import { Formik, FormikConfig, FormikProps } from 'formik';
import { FormikValues } from 'formik/dist/types';
import { FormikRef } from '../models/types';

type FormikWithRefProps<ExtraProps, Values extends FormikValues> = ExtraProps & FormikConfig<Values> & {
  ref?: FormikRef<Values>,
}

export function FormikWithRef<Values extends FormikValues, Props extends object = {}>(
  { ref, ...props }: FormikWithRefProps<Props, Values>,
) {
  const formRef: MutableRefObject<FormikProps<Values> | undefined> = useRef();
  const innerRef = useCallback((formikBag: FormikProps<Values>) => {
    formRef.current = formikBag;
  }, []);
  useImperativeHandle(ref, () => formRef.current);
  return <Formik innerRef={innerRef} {...props} />;
}
```

The above is a wrapper that allows passing any ref (object/callback) to Formik.

**Comment by pierroberto** [comment]
Is there any update on this issue?

**Comment by johnrom** [comment]
@pierroberto https://github.com/formium/formik/pull/2325 ??

seems merged to me. define your innerref like:

```tsx
const myRef = useRef<FormikProps>();

return <Formik innerRef={myRef} {...formikProps} />
```

**Comment by pierroberto** [comment]
That's correct, I missed that release.
Thank you!

**Comment by johnrom** [comment]
Closing as it seems like we're all good here. InnerRef can be implemented as described [here](https://github.com/formium/formik/issues/2290#issuecomment-789045556)

**Comment by Vlad-Shevliakov** [comment]
last solution doesn't work

**Comment by Rubenvdabeele** [comment]
When using typed input:
`
const myRef = React.useRef<FormikProps<YourFormValueType>>(null);

return <Formik<YourFormValueType>
innerRef={myRef}
{...formikProps}
        />
`

**Comment by 1mehdifaraji** [comment]
First of all you need to define a type for `Formik` initial values:
```typescript
interface HelpFormInitialValues {
  destination_city: string;
  cell_phone: string;
}

const initialValues: FormnameInitialValues = {
  cell_phone: "",
  destination_city: "",
};
```
Then define a form type for the `ref` state and set your form initial values type to it:
```typescript
import { FormikProps } from "formik";

const formikRef = useRef<FormikProps<HelpFormInitialValues>>(null);
```
Now you can use all the properties of `Formik` from the `ref` state without any `typescript` errors and also get the benefit of autocomplete.
```typescript
if (formikRef.current) formikRef.current.resetForm();
if (formikRef.current) formikRef.current.isValid();
```
