### ISSUE TITLE
FastField doesn't set initial value with type="checkbox"

### ISSUE THREAD

**Issue by MikeSuiter** [formium/formik#2297]
### Current Behavior

When using FastField and a checkbox's initial value is true the checkbox isn't checked. The code sandbox shows that Field works but FastField doesn't.

### Expected behavior

Checked on true

### Reproducible example

[![Edit Formik FastField checkbox bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formik-codesandbox-template-pwce8?fontsize=14&hidenavigation=1&theme=dark)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4
| React            | 16.12
| TypeScript       |
| Browser          | Safari, Chrome
| npm/Yarn         | yarn 1.22
| Operating System | macOS Catalina

**Comment by pierreneter** [comment]
You must set `checked={props.values.fastField}`

[![Edit Formik FastField checkbox bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formik-fastfield-checkbox-bug-sskte?fontsize=14&hidenavigation=1&theme=dark)

**Comment by MikeSuiter** [comment]
That works but is it a workaround? I thought Field and FastField should act the same other than if the component should update? If you look at my original example Field works just fine without using the `checked=value` but FieldFast doesn't. I would think you could switch FastField and Field have the same functionality (other than if component should update).

**Comment by pierreneter** [comment]
Maybe they forgot to implement for `type="checkbox"`

**Comment by nguyenvantruong17** [comment]
> You must set `checked={props.values.fastField}`
> 
> [![Edit Formik FastField checkbox bug](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/formik-fastfield-checkbox-bug-sskte?fontsize=14&hidenavigation=1&theme=dark)

Thanks for your examples. But could you plz try it on safari? About `touched` with checkboxes. It seems it can not working on safari.

**Comment by pieplu** [comment]
FastField define "field" props in different way than Field, and it's looks lik not complet:

https://github.com/jaredpalmer/formik/blob/c85d85a3b6236a30034e73f8b821a280de8856b0/packages/formik/src/FastField.tsx#L140-L148 

value is set to undefined, but checked is not set for this cases....

**Comment by maddhruv** [comment]
Fixed with https://github.com/formium/formik/pull/2874
