### ISSUE TITLE
FastField not updating Checkbox value on toggle

### ISSUE THREAD

**Issue by simkessy** [formium/formik#2327]
I'm trying to control if my points input is enabled or disabled. When I click on checked, it disabled as expected. When I uncheck it remains disabled. I first tried setting `disabled={isChecked}` then I created it's own state I'd toggle using `useEffect` neither work. Once it's disabled, it won't toggle back to enabled. 
   
      const [isChecked, setIsChecked] = useState(false);
    
      const handleChecked = event => {
        handleChange(event);
        setIsChecked(checked => !checked);
        setFieldValue(`questionData.${idx}.answers.${answer}.point`, 0);
        setFieldTouched(event.target.name);
      };

        <FormControlLabel
            control={
              <Checkbox
                name={`field1`}
                onChange={handleChecked}
                value={isChecked}
              />
            }
            label="Disable points"
            style={{ marginTop: 15, marginLeft: 8 }}
        />
        <FastField
          as={InputField}
          name={`field2`}
          label="Points"
          type="number"
          inputProps={{ min: '0', max: '100', step: '1' }}
          disabled={isChecked}
          handleError={handleError}
        />

```
export const InputField = memo(props => {
  const { handleError = () => {}, name, ...attr } = props;

  const field = name.split('.').pop();
  return (
    <TextField
      size="small"
      fullWidth
      color="secondary"
      error={!!handleError(field)}
      helperText={handleError(field)}
      name={name}
      {...attr}
    />
  );
});
```

I was able to solve this by changing from FastField to Field. I'm not entirely sure why it works now.

**Comment by maddhruv** [comment]
Try the latest formik (`>= 2.2.3`), fixed with https://github.com/formium/formik/pull/2874
