### ISSUE TITLE
resetForm signature is different between v2 migration guide and Formik component documentation

### ISSUE THREAD

**Issue by iraSenthil** [formium/formik#2355]
## 📖 Documentation
In [V2 migration guide](https://jaredpalmer.com/formik/docs/migrating-v2), resetForm method's signature is listed like this.
![image](https://user-images.githubusercontent.com/679076/76333537-ca44bf00-62bf-11ea-85c7-c41ffd77b94c.png)

In Formik component's documentation page, resetForm signature is listed differently. See the following image.

![image](https://user-images.githubusercontent.com/679076/76333722-06781f80-62c0-11ea-9172-7504bb3226f5.png)

I believe migration guide is wrong if [types.tsx](https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/types.tsx) is source of truth. 

I can create a PR to fix this. Please let me know.

**Comment by michaelhayman** [comment]
Thanks for posting this bug (and the solution, i.e. `resetForm({ values: ... })`, was caught up on this for a while.

**Comment by thexpand** [comment]
It's relevant, not stale.

**Comment by sw-yx** [comment]
wow, yup, just ran into this, thanks for the fix @michaelhayman

**Comment by jaredpalmer** [comment]
Send a PR
