### ISSUE TITLE
Yup's test method is triggered when other inputs blur

### ISSUE THREAD

**Issue by zhangking** [formium/formik#2418]
### Current Behavior
this is the `validationSchema` code
when the userName changes, the test method output 1.

```
const schema = Yup.lazy((values) => {
  return Yup.object().shape({
    companyName: Yup.string().required(
      '',
    ).test('companyName',
      '',
      async (value) => {
        console.log(1)
        return value
    }),
    userName: Yup.string().required(
      '',
    ),
  })
})
```

Now I try to cache the validate result to prevent the repeated `test` validate...

```
).test('companyName',
        '',
        async (value) => {
          if (valResult[value]) {
            return valResult[value]
          } else {
            const ret = await checkStatus(value)
            valResult[value] = ret
            return ret
          }
      })


```

Is there a good way?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4
| React            | 16.8
| TypeScript       | 3.8
| Browser          | chrome
| npm/Yarn         |
| Operating System |

**Comment by johnrom** [comment]
There's currently no way to do this. However, this is a duplicate of #512.

**Comment by peter064226** [comment]
i have the same problem and don't know how to solve it , it's very weird , seems yup.test() act different from others .

**Comment by maddhruv** [comment]
Closing as Duplicate
