### ISSUE TITLE
Typing is very slow when having <Select> with many(100-150) options

### ISSUE THREAD

**Issue by Puspendert** [formium/formik#2525]
### Current Behavior
I am using Semantic-ui-react <Form> wrapped inside <Formik>. The moment I add <Select> with ~150 options, the typing gets very slow. It gets hard to type anything.

### Expected behavior
With ~10 options there is not any lag. Expected same with many options.

Though of it to be CSS issue so I removed the CSS package but still the same lag.

### Reproducible example
https://codesandbox.io/s/formik-lag-typing-with-select-rwrdg?file=/src/App.js

**Comment by mattsputnikdigital** [comment]
Make the options a separate component and use React.memo to stop the options redrawing on every key press.

**Comment by jaredpalmer** [comment]
This isn't a Formik problem but one with how you are defining the options. Either wrap in .memo or even better, don't define the options with an inline .map

**Comment by Puspendert** [comment]
> don't define the options with an inline .map
I didn't get this, could you please elaborate how should I define option?

**Comment by mattsputnikdigital** [comment]
@Puspendert you can do this. I keep the options separate from the actual select so it only ever renders if the options change. The select will change, classes etc... to that is also separate from the formik hooks so it only ever renders when its value, error state etc... changes.

```
type SelectPrimitiveOptionsProps = {
  options?: OptionType[];
};

const SelectPrimitiveOptions = React.memo<SelectPrimitiveOptionsProps>(({ options }) => (
  <React.Fragment>
    {options?.map((option, key) => (
      <option key={key} value={option.value}>
        {option.label}
      </option>
    ))}
  </React.Fragment>
));
```


```
export const SelectPrimitive = React.memo<SelectPrimitiveProps>(
  ({ disabled, id, invalid, name, onBlur, onChange, onFocus, options, placeholder, tabIndex, valid, value }) => {
    const [loading, setLoading] = useState(!options?.length);
    useEffect(() => {
      setLoading(!options?.length);
    }, [options]);
    const className = clsx(
      styles["select"],
      disabled && styles["disabled"],
      invalid && styles["invalid"],
      loading && styles["loading"],
      valid && styles["valid"],
      !value && styles["placeholder"]
    );
    return (
      <div className={className}>
        <select
          disabled={disabled}
          id={id}
          name={name}
          onBlur={onBlur}
          onChange={onChange}
          onFocus={onFocus}
          tabIndex={disabled ? -1 : tabIndex ? tabIndex : 0}
          value={value}
        >
          <option value="">{loading ? "Loading..." : placeholder ? placeholder : "Please select"}</option>
          <SelectPrimitiveOptions options={options} />
        </select>
      </div>
    );
  }
);
```

```
const Select: React.FunctionComponent<SelectProps> = (props) => {
  const [field] = useField(props.name);
  return <SelectPrimitive {...props} {...field} />;
};
```

**Comment by Puspendert** [comment]
@mattsputnikdigital could you please remove the Typescript from it? I am not known to it.

**Comment by mattsputnikdigital** [comment]
@Puspendert I have cleaned up the code a bit

You should get Visual Studio Code and start using React with Typescript, it can help predict many different errors in your code and help you write much better apps.

**Comment by Puspendert** [comment]
> Instead define the array of options outside the form .... pass the options array to the component by props

Did this. Declared the data outside the component and passed it as a prop to App component, still same issue.
https://codesandbox.io/s/formik-lag-typing-with-select-rwrdg?file=/src/index.js

**Comment by mattsputnikdigital** [comment]
`>
        {({ values, handleSubmit, handleChange }) => (`

This means you are inside Formiks render function, each key press will render everything inside again as it calculates a new state, values.

You need to memorise all the components, by making a wrapper component, or as I have shown above, use the useField hook and build a memorised components of the <Form> and <Select> components.

**Comment by Puspendert** [comment]
@mattsputnikdigital the `onChange` handler causing the .memo component to re-render on each keypress. If it's `onChange={handleCategoryChange}` it works fine but with onChange={(e, data) => handleCategoryChange(data, setFieldValue)} I am facing the same issue. You can notice the re-render into the console.

**Comment by mattsputnikdigital** [comment]
@Puspendert you need to wrap them in a useCallback if you are looking to do something like this...

```
const Component: React.FunctionComponent = ({ name, ...props }) => {
  const { setFieldTouched, setFieldValue } = useFormikContext();
  
  const [field] = useField(name);
  
  const onBlur = useCallback(
    (event: React.FocusEvent) => {
      const currentTarget = event.currentTarget;
      setTimeout(() => {
        if (!currentTarget.contains(document.activeElement)) {
          setFieldTouched(name, true);
        }
      }, 0);
    },
    [name, setFieldTouched]
  );
 

  const onClick = useCallback(
    (value) => {
      setFieldValue(name, value);
      setFieldTouched(name, true);
    },
    [name, setFieldTouched, setFieldValue]
  );
  return <ComponentMemorized onBlur={onBlur} onClick={onClick} value={field.value} {...props} />;
};
```

**Comment by Puspendert** [comment]
https://codesandbox.io/s/formik-lag-typing-with-select-rwrdg?file=/src/App.js:1300-1718

**Comment by mattsputnikdigital** [comment]
@Puspendert try not to define functions as props as they are recreated every render causing component to render, the below is bad...

```
onChange={(e, data) =>
                  handleCategoryChange(data, setFieldValue)
                }
```

**Comment by Puspendert** [comment]
@mattsputnikdigital thanku so much. `useFormikContext` did the wonders for me. I have achieved what I wanted to, but can you please check again if I am doing it the right way, on same link?

**Comment by mattsputnikdigital** [comment]
@Puspendert had a look, yeah I think you got it. The useFormikContext doesn't change between renders so it is safe to put inside a useCallback and won't cause renders. The useField hook does change every render if you were to access the helper functions, these currently don't work in useCallback.

I had a look at your code and I think you need to add the props.name to the useCallback. name won't change so its fine, but that's how React likes it.

```
const handleChange = useCallback((e, data) => {
    setFieldValue(props.name, data.value);
  }, [props.name]);
```

**Comment by Puspendert** [comment]
@mattsputnikdigital I found a more better way, where we don't even require `useFormikContext `.  Pass a `onChange` prop and pass `setFieldValue` to it.
```
<SelectC
        name="country"
         options={options}
         onChange={setFieldValue}
/>
```
Now change `handleChange` to 
```
const handleChange = useCallback((e, data) => {
    props.onChange.(props.name, data.value);
  }, [props.name]);
```
https://codesandbox.io/s/formik-lag-typing-with-select-rwrdg?file=/src/App2.js
