### ISSUE TITLE
Docs Web Page is not working on https://formik.org/docs/overview

### ISSUE THREAD

**Issue by cdesch** [formium/formik#2582]
## 🐛 Bug report

Just as the title says. going to https://formik.org/docs/overview returns a 404.

<img width="1476" alt="Screen Shot 2020-07-02 at 12 18 25 PM" src="https://user-images.githubusercontent.com/1207795/86385436-46dc1e80-bc5e-11ea-8584-4846882d143c.png">

**Comment by sudkumar** [comment]
Looks like it's up and running now.

**Comment by cdesch** [comment]
looks better than ever 👍
