### ISSUE TITLE
How do I prevent a `@typescript-eslint/unbound-method` error when using `useFormikContent()`?

### ISSUE THREAD

**Issue by brendangibson** [formium/formik#2589]
I have just updated some @typescript-eslint modules to the latest versions:

"@typescript-eslint/eslint-plugin": "3.4.0",
"@typescript-eslint/parser": "3.4.0",
and am now getting the following error

  22:9  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`  @typescript-eslint/unbound-method
for the code

const { setFieldTouched } = useFormikContext();
which is in the same form as in the Formik docs

How do I get around this error?

**Comment by Tigge** [comment]
The function is defined as `export function useFormikContext<Values>()` which means it could potentially hold some sort of `this` object. It doesn't though, of course.

If it was declared as follows, the rule would not tigger:

```typescript
export const useFormikContext = <Values,>() => {
  const formik = React.useContext<FormikContextType<Values>>(FormikContext);

  invariant(
    !!formik,
    `Formik context is undefined, please verify you are calling useFormikContext() as child of a <Formik> component.`
  );

  return formik;
};
```

**Comment by krailler** [comment]
Same here with this error ✋

When I use any function from formikbag eslint throw @typescript-eslint/unbound-method

**Comment by umidbekkarimov** [comment]
Related to the https://github.com/typescript-eslint/typescript-eslint/issues/2245#issuecomment-648712540
Long story short:  all formik methods should be declared as an arrow functions

```diff
export interface FormikHelpers<Values> {
  /** Manually set top level status. */
- setStatus(status?: any): void;
+ setStatus: (status?: any) => void;
  /** Manually set errors object */
- setErrors(errors: FormikErrors<Values>): void;
+ setErrors: (errors: FormikErrors<Values>) => void;
```

**Comment by brendangibson** [comment]
Are you saying that this is something that needs to be fixed in Formik? And not something we can work around in our own code?

**Comment by krailler** [comment]
> Are you saying that this is something that needs to be fixed in Formik? And not something we can work around in our own code?

I think that

**Comment by krailler** [comment]
Can you submit a PR with fixed types? @umidbekkarimov

**Comment by umidbekkarimov** [comment]
@krailler sorry, I had a busy week. Thanks for the PR tho!

**Comment by krailler** [comment]
> @krailler sorry, I had a busy week. Thanks for the PR tho!

Don't worry :)

**Comment by krailler** [comment]
Merged 🙌

**Comment by krailler** [comment]
This ticker can be closed @jaredpalmer

**Comment by m-haketa** [comment]
The same error occurs with handleBlur and handleChange.

package.json
```
"dependencies": {
  "formik": "^2.2.0",
}
```

source code
```
const { handleChange, handleBlur } = useFormikContext();
```

**Comment by maddhruv** [comment]
Closing as should be fixed with the latest release

**Comment by bom124** [comment]
The same error occurs with push and replace in FieldArrayRenderProps.
```
"dependencies": {
  "formik": "^2.4.5",
}
```

source code
```
(props: FieldArrayRenderProps) => {
    const { push } = props; 
}
```
