### ISSUE TITLE
Formik prop "initialValues" - TS error

### ISSUE THREAD

**Issue by Manimall** [formium/formik#2608]
## 🐛 Bug report

Hi, I using Formik in my company's main project. and i faced this problem

### Current Behavior

```
Type '{ FIO: string; email: string; phone: string; dob: string; country: string; city: string; }' 
is not assignable to type 'FormEvent<Element> & 
{ FIO: string; email: string; phone: string; dob: string; country: string; city: string; }'.
  Type '{ FIO: string; email: string; phone: string; dob: string; country: string; city: string; }' 
is missing the following properties from 
type 'FormEvent<Element>': nativeEvent, currentTarget, target, bubbles, and 11 more.
```

![2020-07-14_11-20-05](https://user-images.githubusercontent.com/2580719/87402626-868ef880-c5c4-11ea-9841-7ef693f61a72.png)

### Expected behavior

https://codesandbox.io/s/formik-boilerplateexample-64ugl?file=/src/App.tsx 
I expect no TS errors

### Suggested solution(s)

How could I solve this bug? Why this happended?

### Additional context

VSCode said that initialValues should be that kind of type
```
(property) initialValues: React.FormEvent<Element> & {
    FIO: string;
    email: string;
    phone: string;
    dob: string;
    country: string;
    city: string;
}
```
The expected type comes from property 'initialValues' which is declared here - types.d.ts(143, 5)

### Your environment

| Software         | windows 64-x
| ---------------- | ---------- |
| Formik           |  2.1.4
| React           | 16.13.1
| TypeScript       | 3.8.2
| Browser          | Chrome
| npm/Yarn        | yarn
| Operating System | windows

**Comment by Manimall** [comment]
I really can't move on cause i stuck with this problem(((

**Comment by HipsterBrown** [comment]
@Manimall What is the type signature of your `onSubmit` function? Formik will infer the generic type for `Values` in the form from the `onSubmit` prop if a generic is not passed directly:

Shortened version of the interface for `<Formik>` prop: 
```ts
interface FormikConfig<Values> {
  /**
   * Submission handler
   */
  onSubmit: (
    values: Values,
    formikHelpers: FormikHelpers<Values>
  ) => void | Promise<any>;
}
```

If your `onSubmit` function's type signature is updated to not include `FormEvent<Element>`, then the type issue should be resolved.

**Comment by Manimall** [comment]
@HipsterBrown thank you so much!
