### ISSUE TITLE
no docs for Form Submission

### ISSUE THREAD

**Issue by Manimall** [formium/formik#2611]
## 📖 Documentation
Hi there!

![2020-07-14_16-57-57](https://user-images.githubusercontent.com/2580719/87434618-5dd22780-c5f3-11ea-9d08-6c51080e1569.png)

I wanna know as much as possible about submitting the From via handleSubmit function - but - then i go to the link - there is no page here(((( 😞 

![2020-07-14_17-01-01](https://user-images.githubusercontent.com/2580719/87434858-a984d100-c5f3-11ea-8ebe-44b86e16dfff.png)

so How will i know about Form submitting???

You guys, have 23k stars and no info about submitting the Form - really???

**Comment by HipsterBrown** [comment]
This link appears to be working now. 

![form-submission-link](https://user-images.githubusercontent.com/3051193/87588585-e911f280-c6b1-11ea-9808-c2b7dbd84ede.gif)
