### ISSUE TITLE
isValid prop returns true on mount with validationSchema

### ISSUE THREAD

**Issue by b3coded** [formium/formik#2647]
### Current Behavior

When I create a simple login form with Yup validationSchema the `isValid` prop returns true, I tried to set `validateOnMount={true}` but got same result

### Expected behavior

`isValid` prop should return false

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-w8wkx?file=/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4
| React            | 16.13.1
| TypeScript       | 3.9.7
| Browser          | Google Chrome v83
| npm/Yarn         | npm: 6.14.6 and Yarn: 1.22.4
| Operating System | Windows 10

**Comment by known-as-bmf** [comment]
This issue is present in 2.1.5 as well. This is a regression (worked well in 2.1.3).

**Comment by andycarrell** [comment]
Is this related to https://github.com/formium/formik/issues/2172 ?

**Comment by maddhruv** [comment]
Closing in favour of https://github.com/formium/formik/issues/2172
