### ISSUE TITLE
How to set state of other component from Formik's Error component

### ISSUE THREAD

**Issue by Med-All** [formium/formik#2664]
I have a code which overrides Formik's Error component which looks like:

```
    const [ message, setMessage ] = useState("");    
    
    const Error = props => {
            const fieldSelected = props.field;
            if ((errors[fieldSelected] && touched[fieldSelected])) {
                setMessage("");
                return (
                    <span className={props.class ? props.class : "error-msg"}>
                        {errors[fieldSelected]}
                    </span>
                );
            } else {
                return <span />;
            }
        };
```

Which should to set state of successful massage as `setMessage("")`. It works as expected but throws a warning:

> cannot update a component from inside the function body of a different component

I thought I can do callbacks but looks like I have done it wrong way.

Any tips on that?

**Comment by viniciusdacal** [comment]
It's wrong to call a setState on the "render phase". 
By calling it directly inside the function's body, you are calling on the render phase.

By just looking at the code above, it's hard to come with a solution for what you want.

If you can provide the full code for the component which holds the `message state`, to understand how it relates with the Error component, I can try to help with a solution.

**Comment by Med-All** [comment]
First thanks for your offer! I will try to provide all what is necessary to get some kind of solution for it.

The render part for both looks like:

```
<form className="password-form" onSubmit={(e) => handler(e, resetAPl, props, setMessage)}>

                ....

                <Message message={message}/>
                <Error field="systemErr" />

                 ...
</form>
```

the idea is that in case of an error a message (about success etc) should not to be displayed.

Message component looks like:

```
const Message = props => { 
    return (
        <span className={props.class ? props.class : "system-msg"}>
            {props.message}
        </span>
    );
};
```

and the `resetAPI` part looks like:

```
function resetAPI(url, values, props, setMessage) {
    const {setErrors} = props;
    axios.post(url)
    .then(response => {
        setMessage("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
    })
    .catch((error) => {
        if (error.response) {
            setErrors({
                systemErr: error.response.data
            });
        } else {
            console.log(`System error : " + ${error}`);
            setErrors({
                systemErr: `General System Error: ${error}`
            });
        }
    });
}
```

**Comment by viniciusdacal** [comment]
So, if I got it right, you don't want to display the message in case you have errors, right?
You could do one of the two things:

In this case, you don't display the message component if you have errors.
```jsx
{!Object.keys(errors).length &&  <Message message={message}/>}
```

Other possibility is to reset the message exactly when you get the errors

```js
function resetAPI(url, props, setMessage) {
    const {setErrors} = props;
    axios.post(url)

    .then(response => {
        setMessage("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
    })
    .catch((error) => {
       setMessage('');
        if (error.response) {
            setErrors({
                systemErr: error.response.data
            });
        } else {
            console.log(`System error : " + ${error}`);
            setErrors({
                systemErr: `General System Error: ${error}`
            });
        }
    });
}
```

Hope that solves the issue.

**Comment by Med-All** [comment]
Yes - both options make sense and I think second one should to be the one I should to do but overlooked it going down the rabbit hole. 

Thanks for your help!
