### ISSUE TITLE
Add prevStatus to setStatus method

### ISSUE THREAD

**Issue by andresmechali** [formium/formik#2666]
### Current Behavior

When using setStatus, from useFormikContext(), it just accepts values, and not functions. This makes it inconvenient for updating the status value inside the useEffect hook, as status has to be included as a dependency, leading to an infinite loop.

### Desired Behavior

setStatus should also accept a function as argument, which would have prevStatus as its argument.

### Suggested Solution

This could work as the setter of the useState hook. I can try to emulate what they do and make a PR.

### Who does this impact? Who is this for?

Users trying to update the status based on the previous status, inside a useEffect hook.

### Describe alternatives you've considered

A method like _addToStatus(key, value)_ and _removeFromStatus(key)_ could be implemented too.

**Comment by 3runoDesign** [comment]
I am also going through this!

**Comment by pavelspichonak** [comment]
Me too!

**Comment by pavelspichonak** [comment]
Are you planning to fix it?
