### ISSUE TITLE
Cannot resetForm with new values in V2 (but can in V1)

### ISSUE THREAD

**Issue by josepdominguez** [formium/formik#2689]
## ❓Question

Hello everyone,
I'm spinning around the "dirty" topic. **resetForm** doesn't work for me in V2:
https://github.com/formium/formik/issues/2129
**resetForm** keeps putting the values that I have in "mapPropsToValues", instead of the new ones. By the way I have "enableReinitialize: true".
This is stopping me from going to V.2! In V.1 I just use:
`resetForm(values)`
and all goes well.

Could you please give me some indication?

**Comment by kendallroth** [comment]
I can verify that this is not working as expected. Calling `resetForm({ ... })` with new values does not properly update the intial state and set the form values!

**Comment by josepdominguez** [comment]
I believe this is quite critical, since the Form cannot be sent back to "clean" after it has been submitted, unless page is refreshed.

**Comment by kicsigabszi** [comment]
Same here. Any solution?

**Comment by guilherme-adesouza** [comment]
For v2, you need to resetForm like `resetForm({values: myNewValues})`
Check the docs for migrate to v2: https://formik.org/docs/migrating-v2#resetform

**Comment by josepdominguez** [comment]
Yes, and that's exactly what we say is not working.
Is it working in a project of yours?
Can you share code?

**Comment by kendallroth** [comment]
Ah, I believe that there is a subtle difference in how the pattern is being applied; we have been missing the nested object!

```js
// CORRECT
resetForm({ values: newValues })
```

```js
// INCORRECT
resetForm(newValues)
```

**Comment by josepdominguez** [comment]
Not me, I am using in the "correct" way.
I just indicated that in V1 this works fine:
resetForm(newValues)

And I implicitly say that this for V2 doesn't work:
resetForm({ values: newValues })

**Comment by kendallroth** [comment]
Ah, I apologize, I didn't catch the implicit reference, but rather understood it to mean that what worked in v1 was no longer working in v2.
