### ISSUE TITLE
FastField doesn't set initial value with type="checkbox" and type="radio" with material-ui

### ISSUE THREAD

**Issue by LeamonLee** [formium/formik#2697]
## ❓Question

**Current Behavior**
I'm trying to use FastField with material-ui to avoid unnecessary re-render. A checkbox's and a radio button's initial value are being set, but neither the checkbox nor the radio button display the correct initial status. The following code sandbox link shows that Field works but FastField doesn't. Is there something I miss?

**Expected behavior**
The checkbox and radio button are supposed to display correctly with corresponding initial value.

**Reproducible example**
https://codesandbox.io/s/focused-currying-83dbw?file=/src/App.js

Software | Version(s)
-- | --
React | 16.12
Formik | 2.1.5
Material-ui | 4.11.0
Browser | Chrome 84.0.4147.125

**Comment by LeamonLee** [comment]
I kinda figured out myself. The field that FastField provides doesn't contain 'checked' property, however, the regular Field does.
So my workaround is calculate the value of 'checked' property on my own. Here's the sample code:
<FastField type="radio" name={props.name} value={props.value}>
      {({ field, form }) => {
        console.log("FastField radio");
        const checked = form.values[props.name] === props.value ? true : false;
        return (
          <FormControlLabel
            checked={checked}
            {...field}
            control={<Radio />}
            label={label}
          />
        );
      }}
</FastField>
========================
<FastField type="checkbox" name={props.name} value={props.value}>
      {({ field, form }) => {
        console.log("FastField checkbox");
        // console.log("field:", field);
        // console.log("form:", form);
        const checked = form.values[props.name].includes(props.value)
          ? true
          : false;
        return (
          <FormControlLabel
            checked={checked}
            {...props}
            {...field}
            control={<Checkbox size="small" color="primary" />}
          />
        );
      }}
</FastField>

**Comment by maddhruv** [comment]
Fixed with https://github.com/formium/formik/pull/2874

Try using the latest version
