### ISSUE TITLE
Best way of using Formik with Redux Saga

### ISSUE THREAD

**Issue by jahicDario** [formium/formik#2700]
Hello!

I am wondering what is the best way of using Formik with Redux Saga. 
For example: If I trigger action creator in onSubmit function which will be caught by one of SagasWatchers, and triggers some async call inside Saga action, how would you tell Formik when submitting form is finished? 

As you probably know action creator is not async function when you are using Saga.

Here is some dummy code example:

`
 <Formik
      initialValues={{
        firstName: '',
        lastName: '',
        email: '',
      }}
      onSubmit={(values) => {
      this.props.loginAction(values)
}} >
`

It triggers saga 

`
function* loginUser(action) {
   try {
    const result = yield Api.call('login', 'POST', {
      ...action.userData
    });
    if (result.token) {
      yield put({ type: SET_TOKEN, token: result.token });
    }
  } catch (error) {
    console.log('error:', error);
  }
}
`

In this example, Formik will not wait for Saga to finish, and _isSubmitting_ will be false immediately after action is dispatched. Wanted behavior would be to set _isSubmitting_  to false after saga action gets finished.

**Comment by ThanhNghia944** [comment]
after saga fetch api , you can set success or faild and  
 if (typeUser && typeUser === ActionsType.LOGIN_SUCCESS) {
      setSubmitting(false);
      MyPopUp.hideLoading();
    ...
    }

**Comment by ProteanCode** [comment]
Do you know now what works best for you when it comes to separating the concern of these two libraries?

I am in the project where mixing the Formik with Redux Saga gives more pain than profits, and I am looking into finding the way these two libraries may cooperate rather than collide

**Comment by jaredpalmer** [comment]
In v2, you should make your submission handler async and isSubmitting will be set for you.
