### ISSUE TITLE
Should I use Formik for non-input fields

### ISSUE THREAD

**Issue by gadzhimari** [formium/formik#2704]
## ❓Question

Let say we have filter screen, where each field doesn't have any input component(screen bellow). I've done lot of boilerplate code that I think it can be part of Formik duty to resolve state management. The only difference we don't have any text area, where we attach some of the properties(such as onChange, onFocus and etc.). Please, correct me, if I wrong about idea to use Formik for such cases

![2020-08-17_10-05-33](https://user-images.githubusercontent.com/1849608/90367986-0a2f7f80-e072-11ea-8184-42a50b2fc873.png)

**Comment by WazzaJB** [comment]
We use Formik for handling the entirety of the form data, with validation handled by Yup. This is a perfectly acceptable use case.

You can add [useField](https://formik.org/docs/api/useField) to your custom inputs, or render them using the function render approach like:

```
<Field>
    {({form, field}) => <CustomInput value={field.value} onClick={() => form.setFieldValue('fieldName', 'custom value')} />}
</Field>
```

[See the children option of Field](https://formik.org/docs/api/field#children)

**Comment by flora8984461** [comment]
Have the same use case like chips or just use buttons to make selections, gonna have a try.
