### ISSUE TITLE
Manually Triggered Validation is not working

### ISSUE THREAD

**Issue by iddan** [formium/formik#2712]
### Current Behavior
When calling `submitForm()` or `validateForm()` manually validation doesn't work.

### Expected behavior
Validation to work correctly.

### Reproducible example

Code is based on https://github.com/dawidjaniga/formik/blob/master/docs/guides/validation.md#manually-triggering-validation
https://codesandbox.io/s/form-validation-error-wgj0o

**Comment by WazzaJB** [comment]
Hey @iddan,

I tried reproducing your issue, but everything seems to work as expected?

If you change your logging to `onClick={() => validateForm().then((errors) => console.log(errors))}` you can see that the promises resolution contains the expected errors.

**Comment by iddan** [comment]
I updated the example. You can see the manual submission is working even though there are errors in the form

**Comment by adampatterson** [comment]
I will give a bit of context to what I am doing and what I expected to have happen.

I have a multi-step form, I am using React Router for each step and Yup for my form validation.

**Step 1:**
First Name - Required
Last Name - Optional

_**Next Step ( I want to validate step one before continuing on to step 2)**_

**Step 2:**
Email - Validate Format
Password - Min / Max / Alphanumeric

_**Submit ( Validate the entire form OR Step 1 and 2 )**_

I trying to validate **Step 1** before I continue onto **Step 2**

I was hoping that by calling `validateForm()` I could use the `validationSchema` and validate the form.

The ultimate goal is to use the schema as an array and call something like `validationSchema['step1']`,

I tried `validateField('firstName')` as in the example and didn't notice anything then after I read @WazzaJB and saw that they are validated when you add `validate` to the input but `validationSchema` doesn't appear to be used.

`validateForm()` with or without the `validate` property on the input returns an empty error response 

I would also like to know how I can pass the error to the `<ErrorMessage>` component and I feel like if anything returns an error it should be displayed in the `<ErrorMessage>` component.

**Comment by WazzaJB** [comment]
Hey @adampatterson,

There are quite a few approaches to multi step forms that have been well covered.

https://www.reddit.com/r/reactjs/comments/dysw9i/i_built_a_simple_multistep_form_with_react_formik/

https://github.com/formium/formik/issues/122

https://medium.com/@nphivu414/build-a-multi-step-form-with-react-hooks-formik-yup-and-materialui-fa4f73545598

Hope this helps somewhat?

**Comment by Rafcin** [comment]
@adampatterson 
I was struggling with this multistep issue in my head for a bit, my approach to this was to use react-albus with formik and on each step press it would call checkErrors. The function takes the returned errors, puts the keys in an array and compares it to the array you pass of the items you want validated. I feel like this can get the job done.
```
  checkErrors(e, target_errors) {
    //maps the given errors from validate (object) to (array)
    let errors = []
    for (const [key, value] of Object.entries(e)) {
      errors.push(key)
      console.log(`${key}: ${value}`);
    }
    //Checks if values from our target array exist inside our given errors.
    // We can pick what errors we want validated by this per ablus step.
    return target_errors.every(i => errors.includes(i));
  }
```
```
      <div style={{ paddingTop: "80px" }}>
        <Formik
          initialValues={{ firstName: '', lastName: '', email: '' }}
          validationSchema={Yup.object({
            firstName: Yup.string()
              .max(15, 'Must be 15 characters or less')
              .required('Required'),
            lastName: Yup.string()
              .max(20, 'Must be 20 characters or less')
              .required('Required'),
            email: Yup.string().email('Invalid email address').required('Required'),
          })}
          onSubmit={(values, { setSubmitting }) => {
            setTimeout(() => {
              alert(JSON.stringify(values, null, 2));
              setSubmitting(false);
            }, 400);
          }}
        >
          {({
            values,
            errors,
            touched,
            handleChange,
            handleBlur,
            handleSubmit,
            isSubmitting,
            isValid,
            validateForm
          }) => (
              <Form>
                <Wizard>
                  <Steps>
                    <Step
                      id="merlin"
                      render={({ next }) => (
                        <div>
                          <h1>Merlin</h1>
                          <label htmlFor="firstName">First Name</label>
                          <Field name="firstName" type="text" />
                          <ErrorMessage name="firstName" />
                          <label htmlFor="lastName">Last Name</label>
                          <Field name="lastName" type="text" />
                          <ErrorMessage name="lastName" />
                          <button className="FC_button" onClick={() => validateForm().then((e) => {
                            this.checkErrors(e, ['firstName', 'lastName']) ? console.log("Items not valid") : next()
                          })}>Next</button>
                        </div>
                      )}
                    />
                    <Step
                      id="gandalf"
                      render={({ next, previous }) => (
                        <div>
                          <h1>Gandalf</h1>
                          <label htmlFor="email">Email Address</label>
                          <Field name="email" type="email" />
                          <ErrorMessage name="email" />
                          <button className="FC_button" onClick={() => validateForm().then((e) => {
                            this.checkErrors(e, ['email']) ? console.log("Items not valid") : next()
                          })}>Next</button>
                          <button onClick={previous}>Previous</button>
                        </div>
                      )}
                    />
                  </Steps>
                </Wizard>
              </Form>
            )}
        </Formik>
      </div>
```

**Comment by adampatterson** [comment]
@Rafcin I ended up using a solution like this which looks close to yours. Except it did not use the Wizard.

Each step is a form, 
on each step progress, 
the form is validated and updates the state.

https://github.com/trujic1000/react-formik-form/blob/master/src/components/UserForm.js

**Comment by Rafcin** [comment]
That's how I had originally done it. However I wanted to reduce the size and I end up having 1 GraphQL statement at the end of it all neat
