### ISSUE TITLE
I downloaded this repo... now what?

### ISSUE THREAD

**Issue by adampatterson** [formium/formik#2714]
## ❓ Question

I created my form, checked out the `formik` repo... and now what?

I don't see a setup guide so I ran `npm install` which results in a bunch of warnings and eventually an error, so then I ran ran `yarn install`, looks like it installed.

But after running a few of the scripts and nothing obvious about me seeing how it works I gave up.

I would love to evaluate Formium but I'm not going to spend a bunch of time trying to get this working.

Building the form made me happy, but this made me sad.

**Comment by nickmccurdy** [comment]
I'm not sure how you're supposed to do this with Formium. You may be better off contacting support, as collaborators to Formik aren't necessarily familiar with Formium.

**Comment by jaredpalmer** [comment]
Formium (formerly Formik Cloud) will be generally be available by next week, if not sooner. Sorry for the confusion and lack/outdated of docs, but we had to ship updates to the platform with links to the private GitHub repo to test things out/dogfood the app _before_ launch.

**Comment by adampatterson** [comment]
@jaredpalmer yea I was confused as he difference between Formium and Formik.
