### ISSUE TITLE
TypeError: this.props.formik.unregisterField is not a function

### ISSUE THREAD

**Issue by Mikeks81** [formium/formik#2723]
## ❓Question

Hey guys I have a weird question... So here are work I have an application that works and all the forms are using Formik. Works great, thank you formik community! So I have a tech lead who decided the package up an entire application ( that also uses formik ) in an npm package so that we could just set a route in any other application ( like the one I work on ) and then render that route. However I'm having some ( what seems to me are context issues ). 

So when the npm package/application is introduced into our app whenever you would navigate to the npm package and opened a form you would get "TypeError: this.props.formik.unregisterField is not a function". So i did some research and nothing really helped... except wrapping that npm package in a react component within the application. Great.... however, now the npm package forms work but he application forms ( that used to work just fine ) break with the same errr "TypeError: this.props.formik.unregisterField is not a function".

funny thing is that when you build the application everything works fine... it's just the local dev env that breaks. 

I've tried moving formik and any of our internal components that use formik as peer dependencies with no avail

npm package.json 
`"dependencies": {
    "@blah/components-alerts": "^1.2.28",
    "@blah/components-buttons": "^1.3.17",
    "@blah/components-cards": "^2.0.30",
    "@blah/components-dropdown": "^1.4.15",
    "@blah/components-grid": "0.0.6",
    "@blah/components-modal": "^1.5.6",
    "@blah/components-navigation": "^1.5.9",
    "@blah/components-typography": "^1.3.0",
    "@blah/components-upload": "^1.2.54",
    "@blah/sass-base": "^1.0.6",
    "animatewithsass": "^3.2.1",
    "attr-accept": "^2.0.0",
    "autoprefixer": "^9.6.5",
    "aws-amplify": "^1.1.10",
    "axios": "^0.19.0",
    "classnames": "^2.2.6",
    "downshift": "^3.4.0",
    "immutability-helper": "^3.0.1",
    "match-sorter": "^4.0.2",
    "prop-types": "^15.7.2",
    "query-string": "^6.8.3",
    "react-css-modules": "^4.7.11",
    "react-dropzone": "^10.2.1",
    "react-hot-loader": "^4.12.15",
    "react-redux": "^7.1.1",
    "react-router-dom": "^5.1.2",
    "react-transition-group": "^2.5.1",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.1",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@blah/blah-npm-package": "^0.2.0",
    "@blah/sass-root": "^1.3.3",
    "auto-changelog": "^1.16.2",
    "core-js": "^2.6.9",
    "react": "^16.10.2",
    "react-dom": "^16.10.2"
  },
"peerDependencies": {
    "react-dom": "^16.*",
    "react": "^16.*",
    "formik": "^1.*",
    "@blah/components-forms": "^3.*",
    "@blah/components-inputs": "^3.*"
  }
`

Anyone have any ideas here - I'm at my wits end and the author really isn't any help. And i know i know... its core-js v2...

**Comment by danpantry** [comment]
Hey @Mikeks81 , do you see any warnings in the console when you try this in your local dev environment?

**Comment by Mikeks81** [comment]
Hi @danpantry , I don't see any warnings. I know in v2.x they have a context warning if it's not found but I'm on v1.x. It def seems like there is some sort of context issue happening here... Independently they both work great... Package one up and they don't play well.

**Comment by danpantry** [comment]
is there any chance you could provide a repro for this in codesandbox? I am unable to replicate it myself in codesandbox with the versions listed
