### ISSUE TITLE
Form is reset but error still shows when we touch the screen

### ISSUE THREAD

**Issue by johnneuland** [formium/formik#2725]
### Current Behavior

In my formik form, I take an input & run a graphql query after submitting the form. If the query returns some data, I render a list accordingly. Then, I reset the form. However, as soon as I touch the screen or scroll to view the list, the ErrorMessage starts showing up.

For instance, the error suggests that the input field should not be empty. 

### Expected behavior

The error should only show up when we are trying to resubmit the form without an input. Right now, only the list should be rendered and there should be no error on the field. 

### Reproducible example

```
export const AddFriendScreen: React.FunctionComponent = () => {
  const initialValues: FormValues = {
    input: '',
  };

  const [showFlatList, setShowFlatList] = useState<UsersLazyQueryHookResult>(
    '',
  );

  const [loadUsers, { data }] = useUsersLazyQuery({
    onCompleted: () => {
      setShowFlatList(data);
 },
  });

  const handleSubmitForm = (
    values: FormValues,
    helpers: FormikHelpers<FormValues>,
  ) => {

    loadUsers({
      variables: {
        where: {
          OR: [
            { phoneNumber: newPhoneNumber },],
        },
      },
    });
    helpers.resetForm();
 };

  return (
    <SafeAreaView style={styles.safeAreaViewContainer}>
      <View style={styles.searchTopContainer}>
        <View style={styles.formContainer}>
          <Formik
            initialValues={initialValues}
            onSubmit={handleSubmitForm}
            validationSchema={validationSchema}>
            {({ handleChange, handleBlur, handleSubmit, values }) => (
              <View style={styles.searchFieldContainer}>
                <View style={styles.form}>
                  <FieldInput
                    handleChange={handleChange}
                    handleBlur={handleBlur}
                    value={values.input}
                    fieldType="input"
                    icon="user"
                    placeholderText="E-Mail oder Telefonnummer oder Name"
                  />
                  <ErrorMessage
                    name="input"
                    render={(msg) => <ErrorText errorMessage={msg} />}
                  />
                </View>
                <View style={styles.buttonContainer}>
                  <ActionButton buttonText="Suchen" onPress={handleSubmit} />
                </View>
              </View>
            )}
          </Formik>
        </View>
        <View style={styles.listHolder}>
          {data && showFlatList !== null && (
            <UsersFoundList
              data={data}/>
          )}
        </View>
      </View>
    </SafeAreaView>
  );
};
```
### Additional context

In my rendered list items, there's a button. Whenever I click on the button for the first time, instead of the button working, the error message shows up. If I click on the button the second time then the button usually works. But on the first time, It just brings in the error message.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.1.5
| React Native  | 3.0.4
| TypeScript       | 3.7.5
| yarn         | v1.21.1
| Operating System | macOS

SO: https://stackoverflow.com/questions/63669773/unable-to-click-on-button-with-formik-form
Codesandbox: https://snack.expo.io/@nhammad/jealous-beef-jerky
Issue faced in Android.

**Comment by johnneuland** [comment]
added a codesandbox @jaredpalmer

**Comment by johnneuland** [comment]
Would someone be willing to look into this? @jaredpalmer I added a codesandbox too.

**Comment by dagda1** [comment]
I have this problem too

**Comment by pniby** [comment]
I'm also facing this issue. Any solution?
