### ISSUE TITLE
Manual validation should have a flag to touch all fields

### ISSUE THREAD

**Issue by PatoBeltran** [formium/formik#2734]
### Current Behavior

When submitting a form today, formik's handleSubmit will run manual validation and then touch all fields to show the validation errors to the user.

If you run manual validation this behavior is not there, you have to manually check the results of the validation and touch all fields using `setNestedObjectValues` (basically mimic what handleSubmit does)

### Desired Behavior

formik's validate form should have a flag that lets the user have the exact same behavior as handleSubmit to avoid having to use `setNestedObjectValues` every time you trigger manual validation.

### Suggested Solution

Adding an optional `setTouched?: boolean` parameter to `validateForm` to do this behavior.

I'll be willing to do a PR for this! Let me know if you agree with the approach or if this has been considered but there's a reason not to add it. Thanks!

**Comment by ioev** [comment]
I just found this looking for the same thing.  My use case is I have a 5 step form, with a validation schema for each step.  When the user clicks "next", I want to manually validate against the schema, and display messages, that will disappear once that field has been corrected.  Ideally running the manual validation should just touch any of the fields it validated against.

**Comment by CristianoYL** [comment]
It would be nice to expose a `touchAllFields` method.

**Comment by PatoBeltran** [comment]
@CristianoYL I've found that there is, if you run `formik.setTouched(setNestedObjectValues(errors, true))` where `errors` is the result of `formik.validateForm()` you get all the fields touched.... the problem is that you have to do it manually, instead of having an option to do it within `validateForm`... this is the code I have, which is basically a copy of what `handleSubmit` inside formik does.


```
const errors = await form.validateForm();
if (Object.keys(errors).length === 0) {
  // Form is valid, do any success call
} else {
  form.setTouched(setNestedObjectValues<FormikTouched<FormValues>>(errors, true));
}
```

The problem is that if you want to touch all the fields every time you run manual validation you have to do this code all the time

**Comment by CristianoYL** [comment]
@PatoBeltran Thank you very much. I wasn't aware of this `setNestedObjectValues` method, it's really useful. I still agree that it would be nice to have an additional config to touch all fields on `validateForm`.

**Comment by PTanwarCS** [comment]
@CristianoYL @PatoBeltran I am getting `Attempted import error: 'FormikTouched' is not exported from 'formik'`.
This is my import statement `import {setNestedObjectValues, useFormikContext, FormikTouched, FormikValues} from "formik";`

From where these get exported?

**Comment by RichardsonWTR** [comment]
FTR @PTanwarCS, this seems to be enough. 

```javascript 
import { setNestedObjectValues } from "formik";

const validationErrors = await formikHelpers.validateForm()
    if (Object.keys(validationErrors).length > 0){ 
      formikHelpers.setTouched(setNestedObjectValues(validationErrors, true));
      return;
    }

**Comment by jarrodmedrano** [comment]
> ```js
> ormikHelpers
> ```

what is formikHelpers and where does it come from?

**Comment by jarrodmedrano** [comment]
> FTR @PTanwarCS, this seems to be enough.
> 
> ```js
> import { setNestedObjectValues } from "formik";
> 
> const validationErrors = await formikHelpers.validateForm()
>     if (Object.keys(validationErrors).length > 0){ 
>       formikHelpers.setTouched(setNestedObjectValues(validationErrors, true));
>       return;
>     }
> ```

What is formikHelpers? Where is it imported from?

**Comment by Kestutis** [comment]
> > FTR @PTanwarCS, this seems to be enough.
> > ```js
> > import { setNestedObjectValues } from "formik";
> > 
> > const validationErrors = await formikHelpers.validateForm()
> >     if (Object.keys(validationErrors).length > 0){ 
> >       formikHelpers.setTouched(setNestedObjectValues(validationErrors, true));
> >       return;
> >     }
> > ```
> 
> What is formikHelpers? Where is it imported from?

formikHelpers usually comes as second param is submit function:
https://formik.org/docs/api/withFormik#handlesubmit-values-values-formikbag-formikbag--void--promiseany
