### ISSUE TITLE
One onPress button for handling 2 function

### ISSUE THREAD

**Issue by sokvebolkol** [formium/formik#2739]
## ❓Question

I have used one Formik for two screens. For the first screen show, only state is true and second screen show when state is false. I want to use method onPress in formik button to check this condition. Does someone have any idea, please kindly to help? Thank in advance:)

**Comment by johnrom** [comment]
This is easy to accomplish with hooks.

```jsx
const MyForm = () => {
   const [isStateTrue, setIsStateTrue] = React.useState(false);

  // note this is subject to race conditions. If the user clicks _between render commits_, they may not get the latest `isStateTrue`
  // if that's the case, you should `useRef`.
  const onPress = React.useCallback(
    () => console.log(isStateTrue ? 'true' : 'false'),
    [isStateTrue]
  );

  return <Formik {...formikProps}>
    <Button onPress={onPress}>Press Me</Button>
  </Formik>;
}
```

**Comment by sokvebolkol** [comment]
@johnrom  Thank for your idea:)

**Comment by sokvebolkol** [comment]
@johnrom Now I can use two buttons to solve this problem. The first button just only changes state to false and Second is about handleSubmit form. But the problem is that I can't get values from the first screen. **Note : Theses two screens are in the same formik.

Thank in advance:)
