### ISSUE TITLE
On a Field, how do I make the name property type-safe?

### ISSUE THREAD

**Issue by nickraphael** [formium/formik#2745]
I'm using the Field component shown below...

`<Field component={TextField} type="text" id="surname" name="surname" label="surname" variant="outlined" fullWidth={true} />`

Seems to me that anyone could change the value in 'name' and it would still compile.  How do I make it type-safe so that only names from the bound model can be used?

**Comment by fxh1357** [comment]
Use an enum/object to name your fields:

```javascript
const fieldNames = {
    surname: "surname"
}
```

```jsx
<Field name={fieldNames.surname} />
```

```jsx
<Formik initialValues={
  [fieldNames.surname]: 'Initial Surname'
}>
  // ...
</Formik>
```

Or define a 'proxy-field-component' that declares name to be something like ```keyof typeof fieldNames```
