### ISSUE TITLE
Formik with EXPO SDK 39

### ISSUE THREAD

**Issue by ph-sw** [formium/formik#2763]
### Current Behavior

Just updated to SDK 39 - and updated Formik also to 2.1.5. This gives me a warning ("Reacy.createElement: type is invalid") and two Component Exceptions (both "Element type is invalid") from Formik's code. This is just a small formik test program that worked in SDK37/2.1.4. Anybody with SDK39/Formik experiences?

![image](https://user-images.githubusercontent.com/59928201/93930267-164ed280-fceb-11ea-8e19-9954eff2fe69.png)
![image](https://user-images.githubusercontent.com/59928201/93930296-21a1fe00-fceb-11ea-9634-07ea6fd9e3da.png)
![image](https://user-images.githubusercontent.com/59928201/93930317-2b2b6600-fceb-11ea-98c5-9e430c43a4ea.png)

### Expected behavior

This should show a minimal login screen with a submit button made just for testing. This worked with SDK 37 and Formik 2.1.4.

### Reproducible example

![image](https://user-images.githubusercontent.com/59928201/93934975-e7882a80-fcf1-11ea-8932-51704abba3c6.png)

### Suggested solution(s)

No solution or workaround found

### Additional context

None

### Your environment

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^39.0.0",
    "expo-status-bar": "~1.0.2",
    "formik": "^2.1.5",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-web": "~0.13.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.3.0"
  },
  "private": true
}

**Comment by ph-sw** [comment]
A different example seems to work, so I am closing this for now.

**Comment by samcambridge** [comment]
@ph-sw what different example? what was different? I am having the same issue.
