### ISSUE TITLE
Automatically handle form submit on field change

### ISSUE THREAD

**Issue by k4st0r42** [formium/formik#2769]
I want to handle form submit automatically on field change.

I tried to call form.submitForm() in my change function of my field but there are no effect.
The onSubmit() function of Formik component is not handled...

Thank you

**Comment by fxh1357** [comment]
Works for me, but I'm not sure if it's a good idea 🤔 

```javscript
      <Formik
        onSubmit={(args) => {
          console.log("Formik#onSubmit", args);
        }}
        initialValues={{
          value: true
        }}
      >
        <>
          <Field name={"value"}>
            {({ field, form }) => {
              return (
                <input
                  {...field}
                  checked={field.value}
                  type={"checkbox"}
                  onChange={(e) => {
                    field.onChange(e);
                    form.submitForm();
                  }}
                />
              );
            }}
          </Field>
        </>
      </Formik>
```

**Comment by k4st0r42** [comment]
I have investigate and the issue is that the isValid condition is false in formik, because of combinedErrors which contains isCanceled:true. So the submit process is canceled.

But I don't know why I have this error isCanceled:true...

**Comment by johnrom** [comment]
This is best done with an effect. Basically, formik.handleChange does a bunch of things that _eventually and asynchronously_ update Formik's internal state with the latest values and validation. Doing submitForm immediately after calling field.onChange won't have access to that future state, meaning it cannot submit properly. Instead, you want to listen for the exact set of conditions within Formik's state which should cause a Form Submit Attempt.

The API is definitely in need of improvement.

```
export const SubmitListener = <TFormValues extends any>(
    props: InventoryFiltersFormListenerProps<TFormValues>
) => {
    const [lastValues, updateState] = React.useState(props.formik.values);

    React.useEffect(() => {
        const valuesEqualLastValues = isEqual(lastValues, props.formik.values);
        const valuesEqualInitialValues =
            props.formik.values === props.formik.initialValues;

        if (!valuesEqualLastValues) {
            updateState(props.formik.values);
        }

        if (!valuesEqualLastValues && !valuesEqualInitialValues) {
            props.formik.submitForm();
        }
    }, [
        lastValues,
        props.formik.values,
        props.formik.initialValues,
        props.onChange,
        props.formik,
    ]);

    return null;
};

export const MyForm = () => {
  return <Formik 
    // etc...
    onSubmit={(values) => console.log(values)}
  >
    {formik => 
     <SubmitListener formik={formik} />
    }
  </Formik>
}
```

**Comment by erdemkeren** [comment]
Is there any update or plan to fix this?

**Comment by johnrom** [comment]
@erdemkeren this can be accomplished via https://github.com/formium/formik/issues/2769#issuecomment-698494400

**Comment by erdemkeren** [comment]
@johnrom thanks for the reply.

You are right. I leave another sandbox here just for ref (also does validation on submit). 

https://codesandbox.io/s/formik-submit-listener-with-validation-dd0c4?file=/index.js

That was a little bit tearful. Let's repeat what you said:
The API is definitely in need of improvement.

**Comment by trohr** [comment]
This feature is a must have if you don't want people to be forced to create a 'SubmitListener' component of their own, where there will be the generic logic.

I imagine -- if we in our company will still be using formik -- that after a while, I will be forced to create a library for our usage, where this component will be located. We will have to support it throughout maintenance of our apps during upgrades to newer versions of formik. Not something I wish for my future.

Please implement the component built-in.
Everybody vote!

Thanks

Sincerely yours,
Tomas Rohrbacher

**Comment by leonardo-felix** [comment]
```typescript
const AutoSubmit = () => {
  /*
    This component is used to automatically submit the form when the form is valid
    and has been changed(dirty).
   */
  const {isValid, values, dirty, submitForm} = useFormikContext()

  useEffect(() => {
    if(isValid && dirty){
      void submitForm()
    }
  }, [isValid, values, dirty, submitForm])

  return null
}
``` 

Just put it on your formik form and it will autosubmit:
```typescript
  return (
    <Formik<FormValues>
      initialValues={initialValues}
      validationSchema={validationSchema}
      enableReinitialize
      onSubmit={noop}
    >
      <>
      <AutoSubmit />
      <Field name="name" label="Name" />
      </>
    </Formik>
  )
```

**Comment by LeonMueller-OneAndOnly** [comment]
There is a way to synchronously update formik field values: 

Relying on useEffect to submit your form after the actual event has happended is an anti-pattern inside React. It spreads your logic across different places and brings in all of the life-cycle-headaches of react.

I recommend to use the flushSync method of react-dom to update formik's state synchronously. It is really useful for situations like this.

Here is a simple example of an email input inside a popover with a cancel button, pressing the cancel button should clear the field value and then directly submit the form to close the popover.


``` .tsx
 <Formik>
            {(form) => (
              <div
                className="flex min-w-[300px] items-start p-2"
              >
                <div className="w-0 grow">
                  <TextInput name="email" label={t`E-Mail`} variant="outlined" autoFocus nullable />
                </div>

                <div className="h-[56px]">
                  <Button
                    className="h-full p-2"
                    variant="ghost"
                    onClick={() => {
                      flushSync(() => {
                        form.setFieldValue("email", null)
                      })
                      void form.submitForm()
                    }}
                  >
                    <Clear />
                  </Button>
                </div>
              </div>
            )}
</Formik>
```
