### ISSUE TITLE
Checkboxes broken with numeric values

### ISSUE THREAD

**Issue by simoneconti** [formium/formik#2775]
### Current Behavior

When using checkboxes (multiple checkboxes with the same name attribute) everything works fine if the values are string types, but not if the values are numbers.
It seems the values are stored as strings and this breaks the render of the checkbox itself  because it results always turned off, since string in not a number.
For example if a checkbox has a value of 3, it is stored as ['3'], so it is always turned of because 3 !== '3'.

![image](https://user-images.githubusercontent.com/44508641/94280329-8d83a100-ff4d-11ea-8a29-9154b5ff3851.png)

Example:
https://codesandbox.io/s/young-wind-0z13y

**Comment by johnrom** [comment]
Duplicate of #2044

**Comment by johnrom** [comment]
This will be solved in userland in v3 via the `parse` prop. You'll be able to do `parse={value => parseInt(value, 10)}`.

**Comment by jhackett1** [comment]
what's the best way to handle this right now?

i imagine this is a common issue, since most immutable ids you'll want to use as values are numbers.

i can imagine manually taking the form's values object and overriding the selected attribute somehow?
