### ISSUE TITLE
useFormik initialValues pass object props

### ISSUE THREAD

**Issue by giladrozmarin** [formium/formik#2776]
## ❓Question

I build a simple project  to explain my problem  
here  the full code 
https://codesandbox.io/s/check-it-4d2g1?file=/src/App.tsx:585-598

I want to pass initialValues from App component to Step1 component and after that show the firstName in Step2 component

here my initialValues in useFormik hooks
`  const formik = useFormik({
    initialValues: {
      firstName: "",
      lastName: ""
    }
  });`

This is step 1 
here the user fill the firstName input 
![image](https://user-images.githubusercontent.com/33815204/94292091-2bcf3100-ff65-11ea-8cba-6cc743c0391d.png)

here the firstName field 

![image](https://user-images.githubusercontent.com/33815204/94294173-1c051c00-ff68-11ea-8041-0b71c353852f.png)

This is step 2

![image](https://user-images.githubusercontent.com/33815204/94292879-350ccd80-ff66-11ea-965e-c5f85a14682b.png)
 
So how can I displat firstName at Step2 ?

**How I try is the right way?**

I know there is 3 way for that 
1.Passing a component to the component prop of Formik
2.Using the render method and passing your forms markup in JSX
3.Wrap your form with Formik and add your form as JSX

What is the fit way can you fill my codesandbox example according this way...?

https://codesandbox.io/s/check-it-4d2g1?file=/src/App.tsx:585-598

**Comment by fxh1357** [comment]
I don't get your three options and I think you could've found a solution to that on your own - e.g. by having a look at the examples folder on github [MultistepWizard](https://github.com/formium/formik/blob/master/examples/MultistepWizard.js).
 
But I had a good laugh about your "I want it will show here" illustration - so here you go: 

https://codesandbox.io/s/check-it-forked-mp3ux

You only need one Formik instance at the top. Every single field is connected via Formik's React.Context. For further detail on spreading individual fields on multiple steps study the linked example

cheers
