### ISSUE TITLE
isSubmitting is set to false after onSubmit is finished

### ISSUE THREAD

**Issue by blueberry6401** [formium/formik#2782]
## ❓Question

Hi,
I've switched to v2 and notice that when onSubmit handler finished, isSubmitting is immediately set to false.
This behavior is different from v1 and I didn't notice anything that mentions it in the docs: https://formik.org/docs/migrating-v2
And this one still tells me to call setSubmitting(false) manually in my handler: https://formik.org/docs/guides/form-submission
So is this behavios on purpose, or it's a bug?

**Comment by jaredpalmer** [comment]
If you're callback is a promise it is set for you. Otherwise, you have to do it manually.

**Comment by blueberry6401** [comment]
Thanks. If this is by design, I think it should be mention in the docs (2 links above).
