### ISSUE TITLE
Compare form values before submit

### ISSUE THREAD

**Issue by pt-bhavsar** [formium/formik#2788]
## ❓Question

I have form where I populate the fields with initial values and then user updates the fields. I want to prevent user from submitting the form unless at least one form field is updated. I am looking for ways to achieve this. Can someone please help on this?

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by johnrom** [comment]
Here's a quick solution:

```js
// this is a dependency of Formik, so you shouldn't need to install
import isEqual from 'react-fast-compare';

const initialValues = {
  firstName: "john",
  lastName: "rom",
};

const MyForm = () => {
  // values start off equal when using initialValues as values
  const [areValuesEqual, setAreValuesEqual] = React.useState(true);
  const onSubmit = React.useCallback((values) => {
    // areValuesEqual might be stale, so calculate based on values passed to submission
    if (!isEqual(initialValues, values)) {
      return console.log('submitted.');
    }

    console.log('didn't submit.');
  }, []);
  const formik = useFormik({
    initialValues,
    onSubmit,
  });

  useEffect(() => setAreValuesEqual(isEqual(initialValues, formik.values)), [formik.values]);

  return <FormikProvider value={formik}>
    <Form>
      <Field name="firstName" />
      <Field name="lastName" />
      <button type="submit" disabled={areValuesEqual}>Submit</button>
    </Form>
  </FormikProvider>;
}
```

**Comment by pt-bhavsar** [comment]
@johnrom thanks for your reply. I am setting the formik values dynamically. I have different onChange triggers based on different menu selection. When I pass "formik" to a function and within the function I am setting formik values using formik.setFieldValue, I still not able to access them using formik.values, maybe cause form is not rendered still. Your solution is gonna work I think, but I will first have to create JSON object for later comparison on submit.

**Comment by johnrom** [comment]
initialValues is a required property on both Formik and useFormik, so you should build the object dynamically beforehand. You can get away with it sometimes, but Formik's architecture doesn't support arbitrary values shapes (yet). Formik.values should always match <Formik initialValues /> object signature.

**Comment by pt-bhavsar** [comment]
@johnrom I changed my form, from using <Formik /> to <FormikProvider /> per your solution. It works for me really well. I am not able to go to next step however upon pressing submit button. Maybe onSubmit is not receiving form field "values". Any idea why?

**Comment by pt-bhavsar** [comment]
@johnrom I changed my form, from using <Formik /> to <FormikProvider /> per your solution. It works for me really well. I am not able to go to next step however, upon pressing submit button. Maybe onSubmit is not receiving form field "values". Any idea why?

**Comment by pt-bhavsar** [comment]
It seems like yup validation is causing some problem form, after removing validation, it worked beautifully. All my fields as per validation defined. Not sure why it's giving me trouble. Will have to look.

**Comment by johnrom** [comment]
Awesome, feel free to close the issue if your issue is solved.

**Comment by pt-bhavsar** [comment]
All my issues resolved. Thanks @johnrom again for your help. Closing the issue.
