### ISSUE TITLE
Issue with select default selection

### ISSUE THREAD

**Issue by Cubid** [formium/formik#2792]
### Current Behavior

When I fill a select with values, the form automatically select the first item (standard behavior).  
With plain JS, the form value for the select is the first value.  

With Formik, the browser selects automatically the first value, but Formik does not consider it.  

Please consider this example:  
https://codesandbox.io/embed/n102qqq0nl

After selecting commodity1, Plant1 is automatically selected. Formik does not take it into account.

![image](https://user-images.githubusercontent.com/37664014/94838073-57df2c00-0415-11eb-8ed3-33cbe57b6031.png)

### Expected behavior

Formik should have the same behavior as a plain form and have the selected value in its values.

### Reproducible example

https://codesandbox.io/embed/n102qqq0nl

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by johnrom** [comment]
initialValues is a required property of Formik and must be populated with the default value of every field in your form, including your `select`. If your initialValues matches the first select option, it will work as you expect.

**Comment by Cubid** [comment]
So, the option is to update initialValues when the select options are modified?  
And use enableReinitialize={true} on the form ?

**Comment by johnrom** [comment]
That's correct, updating initialValues with enableReinitialize will be more semantically correct than updating Formik's value, but it will be more expensive. If you are testing against `isDirty` or `touched`, `initialValues` is the way to go. If you're not using either of these, just updating the value could work.

**Comment by Cubid** [comment]
Thanks, i will do it this way.
