### ISSUE TITLE
submitError field on FormikProps

### ISSUE THREAD

**Issue by mateja176** [formium/formik#2804]
### Current Behavior

Formik handles all of the state relating to a form, including values, errors, touched, isSubmitting etc. Which is amazing since it helps developers focus on business logic styling and so on.

Expect there is one state missing and that is the `submissionError`.

### Desired Behavior

`submissionError: string | null` or `submissionError: Error | null // where error may also be generic, extending the Error class`, would be in line with formik's philosophy of managing form related state and keeping developer tears away.  

### Suggested Solution

The `submissionError` field would be part of FormikProps.
It's value would be null initially and it would be automatically set in case `onSubmit` returns a Promise which rejects. The error would be handled to set the internal state and rethrown.
The `submissionError` would be set to its initial value, right before onSubmit is called.  

### Who does this impact? Who is this for?

If the server error is tied to specific field like a non-unique username it may be preferable to display the error beneath the username field. Whoever, in case of a network error, a 500 level error, a general 400 level error or similar, it is preferable to display a snackbar, alert, dialog or similar which is generally not tied to any field but the form itself. So yes, this impacts the majority of users.

### Describe alternatives you've considered

An alternative solution would be to manage the state yourself using a `useState` hook, however this almost became boilerplate for me, signaling that it's a common use case.

**Comment by kobeaerts** [comment]
I'm having the same issue, coming from Final Form I don't really see how I can show a general form error..
