### ISSUE TITLE
Set Field to autocomplete=off like for normal input

### ISSUE THREAD

**Issue by raresmigea** [formium/formik#2808]
To set the autocomplete off for a simple input it must be done like this: `<input type="text" autocomplete="off">`

But it seems this doesn't work for [Field from Formik](https://formik.org/docs/api/field).

I tried like that but has no effect:

```
<Field
  className="my-class"
  name="myValues"
  as={Input}
  placeholder="Write something"
  autocomplete="off"
/>
```

Is there a feature to do this or should be created a new one?

**Comment by raresmigea** [comment]
One solution is to remove `Input` which in this case is imported from [Semantic UI](https://react.semantic-ui.com/elements/input/) and it seems that Field doesn't work fine using that input type and autocomplete set off at the same time.

**Comment by tripolskypetr** [comment]
Looks like all these methods with `autofill` prop are simple ignored by Google Chrome since 2022. I suggest a different method: using `readOnly={true}` until focus event

> Keep in mind that on mobile safari keyboard will not shown if input field change readonly state after focus event, so you need to process `onTouchStart` too. Heres the link to [the source code of `usePreventAutofill` hook](https://github.com/react-declarative/react-declarative/blob/51f4c29897297233e5c958de782b6af4e7b41cf5/src/hooks/usePreventAutofill.ts#L19)

```tsx
import { usePreventAutofill } from 'react-declarative';

...

const preventAutofill = usePreventAutofill();

...

return (
  <Input

      ...

      {...preventAutofill}
  />   
);
 
```
