### ISSUE TITLE
Data leak in case of JS error

### ISSUE THREAD

**Issue by Wendenburg** [formium/formik#2811]
## 📖 Documentation

Checking our logs i just run into a data-leak issue. The setup is a Formik-form sending data via axios-post request. Formik is using a submit button to trigger validation and executing the onSubmit-handling. However, if a JS error occurs (old browser, whatever...), the JS-handling is interrupted and the form data are send natively as a get request to the same page. Now they are shown in the url and will be logged as a referrer.

The simple fix is always to add the post method to the form tag, which should maybe be a recommendation in the docs...

**Comment by jaredpalmer** [comment]
Yeah, I’ve ran into this once. It can be solved this by adding a method=“post” as you described to form. We probably should by default.

**Comment by zidian257** [comment]
ran into this when using in Gatsby, and js dependency is somehow not loaded due to network issue, then saw in our logs the data leaking.
can I take this one btw ?
