### ISSUE TITLE
How to add a new field in useEffect hook?

### ISSUE THREAD

**Issue by ProteanCode** [formium/formik#2816]
## How to add a new field in useEffect hook

I am trying to add a field to initial values inside a component

```
const RandomComponent = () => {
    const formik = useFormikContext<any>();
    useEffect(() => formik.resetForm({ ...formik.values, aNewField: {} }), []);
}
```

No error has been thrown, the form is not dirty, but console logging the `formik.values` does not show a new value.

I ve used this on codesandbox without success

```
import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import { Formik, Form, useFormikContext } from "formik";

const RandomComponent = () => {
  const formik = useFormikContext();
  useEffect(() => formik.resetForm({ ...formik.values, aNewField: {} }), []);

  return <div>{JSON.stringify(formik.values)}</div>;
};

const Basic = () => (
  <Formik
    initialValues={{
      firstName: "",
      lastName: "",
      email: ""
    }}
  >
    <Form>
      <RandomComponent />
    </Form>
  </Formik>
);

ReactDOM.render(<Basic />, document.getElementById("root"));
```

**Comment by clflowers5** [comment]
Thanks for the code sample, you've just got the resetForm syntax off - should be an object with the key `values`:

```  
useEffect(() => formik.resetForm({ values: { ...formik.values, aNewField: {} } }), [formik]);
```

https://formik.org/docs/api/formik#resetform-nextstate-partialformikstatevalues--void

https://codesandbox.io/s/laughing-shockley-v65ht?file=/src/App.js

**Comment by ProteanCode** [comment]
> Thanks for the code sample, you've just got the resetForm syntax off - should be an object with the key `values`:
> 
> ```
> useEffect(() => formik.resetForm({ values: { ...formik.values, aNewField: {} } }), [formik]);
> ```
> 
> https://formik.org/docs/api/formik#resetform-nextstate-partialformikstatevalues--void
> 
> https://codesandbox.io/s/laughing-shockley-v65ht?file=/src/App.js

Lesson #1: Do not trust Typescript too much
