### ISSUE TITLE
'FormikContext' refers to a value, but is being used as a type here. Did you mean 'typeof FormikContext'?ts(2749)

### ISSUE THREAD

**Issue by tomaszs** [formium/formik#2817]
After updating Formik from 1.5.8 to 2.2.0 an error occurs on line:

formik: FormikContext<IMyCustomInterface>;

Stating: 'FormikContext' refers to a value, but is being used as a type here. Did you mean 'typeof FormikContext'?ts(2749)

I have reviewed all change logs since 1.5.8 to 2.2.0 and can not find any breaking change causing this behaviour,

How to fix it?

**Comment by maddhruv** [comment]
Hey @tomaszs the `FormikContext` type that you are using here - `formik: FormikContext;` is being renamed to `FormikContextType` and the `FormikContext` actually refers to the React.Context for the form and is not a type/interface anymore.

Please migrate `formik: FormikContext;` to `formik: FormikContextType;`
