### ISSUE TITLE
a type mismatch between FormikHandlers.handleSubmit and onSubmit in types.d.ts of formik 

### ISSUE THREAD

**Issue by BrutalHex** [formium/formik#2818]
### Current Behavior
Type '(e?: FormEvent<HTMLFormElement> | undefined) => void' is not assignable to type '(event: FormEvent<HTMLElement>) => void'

 
### Expected behavior
it should work with this syntax on forms onSubmit={handleSubmit} but
at current condition we need to rewrite it as 

          onSubmit={(event: React.FormEvent<HTMLFormElement>): void => {
                            handleSubmit(event);
                          }}

 
### Suggested solution(s)

in Types.ts we should change :
interface FormikHandlers {
 handleSubmit: (e?: React.FormEvent<HTMLFormElement>) => void;
}
to:
 interface FormikHandlers {
 handleSubmit: (e?: React.FormEvent<HTMLElement>) => void;
}

 
### Your environment

| Software         | Version(s) |
| --------------- | ----------  |
| Formik            |     2.2.0     |
| React              |     16.9      |
| TypeScript      |     4.0.3     |
 ------------------------------

**Comment by maddhruv** [comment]
Hey @BrutalHex ideally you don't even need to declare type for the `onSubmit` handler function.

I've created a basic sandbox to show that without declaring the type for `onSubmit`, it can still work fine - https://codesandbox.io/s/serene-bhabha-b9h77?file=/src/App.tsx:236-291

> onSubmit={handleSubmit} 

although, can you check the type of the `handleSubmit` function that you declared here.
And, when you are adding a `?` in front of a property, you don't need to explicitly define `undefined` as a type value
