### ISSUE TITLE
MultiStep Form Item

### ISSUE THREAD

**Issue by mossa-Sammer** [formium/formik#2823]
can you explain this please, I don't see if it's using any component from Formik, as it takes Formik component props, 
also, typescript blaming me when I pass these props
https://github.com/formium/formik/blob/559667c823331e8be85a50e8240e45f7c782fa3c/examples/MultistepWizard.js#L76

**Comment by maddhruv** [comment]
Hey @mossa-Sammer it feels like the `MultistepWizard` example is not complete yet, the intention behind this component viz. `WizardStep` seems to be handling form submission - validation and error handling at each step, but is not fully implemented.

I would cc @jaredpalmer to know, if there was an intention on leaving this like this or is it in TODO

**Comment by maddhruv** [comment]
Closing as being tracked in https://github.com/formium/formik/issues/1315
