### ISSUE TITLE
Form does not reinitialize when new initialValues are passed 

### ISSUE THREAD

**Issue by mattleonowicz** [formium/formik#2829]
### Current Behavior

When `enableReinitialize` is `true`, and new `initialValues` are passed, but they differ only in one property which is boolean, `values` don't change to be the same as newly passed `initialValues`.

This boolean value important here. For some reason Formik seems to ignore changes in properties of type boolean and doesnt reinitialize the form.

### Expected behavior

`values` should always equal to newly passed `initialValues` after reinitialization when `enableReinitialize` is set to `true`.

### Reproducible example

https://codesandbox.io/s/confident-leaf-w50g3?file=/index.js

To reproduce:
 1. Click button "Set to false"
 2. Click second button (which simiulates some request and reinitializing form with new values
 3. Since enableReinitialize is set to true, `values` of form should change (booleanVal -> true) but they don't

A workaround that I use currently is to always add some other unused property which has a random value each time initialValues need to be new

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.0
| React            | 16.14.0
| TypeScript       | 3.9.7
| Browser          | Chrome
| npm/Yarn         | not relevant
| Operating System | not relevant

**Comment by krvajal** [comment]
I dont see in your example that the initial values are changing. When you initialize the form the initial values are the ones from 
the `useState` initialization
```
useState(() => ({
    stringVal: "someVal",
    booleanVal: true
}));
```
and then in your submit handler you are setting it to the same initial values

```
 setInitialValues({
      stringVal: "someVal",
      booleanVal: true
    });
```
so 
> For some reason Formik seems to ignore changes in properties of type boolean

there is no change in the property ` booleanVal` for Formik to reinitialize the form.
You can call the `resetForm` method to reinitialize the form again if that is what you want.

**Comment by StuartMorris0** [comment]
Here I am with the exact same issue, with high hope scrolling down, to see its been closed for inactivity :( 

This still exists, updating boolean values does not make the fields that use the boolean values rerender and therefore makes the values stale. 

I.e. 
load with initial value of false
async api call, update the initial values (or even setFieldValue) 
the updated value is picked up in the field but does not cause it to change value/rerender
