### ISSUE TITLE
Initial values are not getting stored in textfield component while writing code with formik-autocomplete can anyone help me?

### ISSUE THREAD

**Issue by revanth371** [formium/formik#2830]
## ❓Question

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by maddhruv** [comment]
Hey @revanth371 can you brief a little bit more on the issue or maybe create an issue as a [Bug](https://github.com/formium/formik/issues/new?template=Bug_report.md), helping us understand better with reproduce-able code.

Also, I am not sure what `formik-autocomplete` is??

**Comment by revanth371** [comment]
Hii,
Actually, I have a search API i.e., while searching API has to be hit. This
one we do. and we are sending that data to the API(POST) it is successful,
But while we are trying to edit data we want the default value which needs
to be stored in Autocomplete inside formik, for that, I am unable to
display the default value.
Thank you

Below i am attaching code
<Field
name="autocomplete"
options={medicalListData}
getOptionLabel={(option) => option.name}
component={Autocomplete}
onSelect={handleAutocompleteChange}
// value={values.drug_name}
defaultValue={medicationName.name}
renderInput={(params) => (
<TextField
{...params}
type="text"
className={classes.Input}
label="Drug Name"
name={"drugName"}
value={values.drugName}
error={isError(errors.drugName, touched.drugName)}
helperText={
isError(errors.drugName, touched.drugName)
? errors.drugName
: null
}
onChange={MedicalChange}
/>

**Comment by maddhruv** [comment]
Hey @revanth371 can you also confirm me the exact formik version, for better debugging, AFAIK the component `Field` doesn't has a prop called `renderInput`

**Comment by revanth371** [comment]
Formik version - 2.1.4
And also is it possible to write date picker code inside for formik?
Thanks 👍

**Comment by maddhruv** [comment]
yes @revanth371 you can use any custom react component in formik Field by using the `component` prop

**Comment by revanth371** [comment]
Good morning,
will check in google if possible will you able to send the code
