### ISSUE TITLE
Calling formik.submitForm() resolves with undefined

### ISSUE THREAD

**Issue by oleksii-ivanov** [formium/formik#2831]
### Current Behavior

Calling formik.submitForm() promise manually resolves always with undefined regardless of what my handler returns.

### Expected behavior

Promise throw reject in case of validation error

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-forked-yrdh4?file=/index.js

### Suggested solution(s)
it happens because combinedErrors is not an Error and it doesn't throw it.

### Additional context
temp workaround:
use validateForm to check if there are any errors.

the issue discussed more there https://github.com/formium/formik/issues/2057

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |2.2
| React            |16.13.1
| Browser          |chrome 86

**Comment by maddhruv** [comment]
Closing in favour of - https://github.com/formium/formik/issues/2057
