### ISSUE TITLE
Right sub-navigation not fully responsive

### ISSUE THREAD

**Issue by benjaminsuch** [formium/formik#2834]
## 📖 Documentation

Hey guys, awesome work with Formik! There is just one tiny bug in the documentation I want to mention: The submenu does is not scrollable and ends too soon. I attached a screenshot.

**Resolution**: 1920x1080
**Browser**: Chrome
**Browser Zoom**: 100% (default)

Temporary fix is by just zoom out until you see every menu-item. Overall not a big deal, but better report than not to report I guess.

<img width="1678" alt="Formik-Docs-Submenu-Bug" src="https://user-images.githubusercontent.com/706852/96859877-562be580-1462-11eb-9934-422301183ef0.png">

**Comment by maddhruv** [comment]
Hey, @benjaminsuch thanks for raising this issue.
Would love if you can raise a PR fixing this

**Comment by benjaminsuch** [comment]
Sure will do, expect it on the weekend! 😄
