### ISSUE TITLE
Error message not showing in case of 'Select' component

### ISSUE THREAD

**Issue by dardar4** [formium/formik#2842]
Hi
not sure if this is a bug or I'm doing something wrong :)

https://codesandbox.io/s/summer-wave-n62je?file=/src/index.js

the email validation is working ok.

but I have a problem with the 'Select' element validation
I have an array named 'tags' and it holds all the selected values.
in the validation I'm checking the array is not empty (i.e. at least one item is selected)
the problem is the error message ('Required') is not showing when trying to submit.
in fact, the validation occurs since nothing happens if no values were selected but the message is not showing

the expected result should be that the error message is rendered to the from, but the current behavior is that nothing happens

**Comment by ar4hc** [comment]
similar problem here, with Arrays, i think some of the checks in ErrorMessage doesn't work well with arrays, so the component always believes there are no errors. :/

e.g. for arrays the formik.touched  is never set. 

checked using                        
```
 <pre>{JSON.stringify(formik.touched.mylist, null, 2)}</pre>
```

**Comment by sukesh-s** [comment]
> Hi
> not sure if this is a bug or I'm doing something wrong :)
> 
> https://codesandbox.io/s/summer-wave-n62je?file=/src/index.js
> 
> the email validation is working ok.
> 
> but I have a problem with the 'Select' element validation
> I have an array named 'tags' and it holds all the selected values.
> in the validation I'm checking the array is not empty (i.e. at least one item is selected)
> the problem is the error message ('Required') is not showing when trying to submit.
> in fact, the validation occurs since nothing happens if no values were selected but the message is not showing
> 
> the expected result should be that the error message is rendered to the from, but the current behavior is that nothing happens

Hi @dardar4  
To show error messages in select you can use  formik [ErrorMessage](https://formik.org/docs/api/errormessage) or  [FormHelperText](https://material-ui.com/api/form-helper-text/) 

hope its helps
[https://codesandbox.io/s/quizzical-framework-0m03h?file=/src/index.js](https://codesandbox.io/s/quizzical-framework-0m03h?file=/src/index.js)

**Comment by dardar4** [comment]
@sukesh-s 
thanks bro. the codeSandBox really helped. using FormHelperText seems a better choice cause it keeps all errors in the same style :)

**Comment by maddhruv** [comment]
Closed as seems to be solved
