### ISSUE TITLE
How Formik displays error message without using <ErrorMessage />?

### ISSUE THREAD

**Issue by dardar4** [formium/formik#2843]
Hi all,

see the follwing expmale:
https://codesandbox.io/s/summer-wave-n62je?file=/src/index.js

there is no "ErrorMessage" in this example, and yet when not entering an email a message is displayed
how is it working?

btw, for some reason, the 'tags' array is not working in this example

thanks

**Comment by johnrom** [comment]
@dardar4 , they use Material UI. You can see they are passing custom TextInput / Select from `formik-material-ui` to Formik's Field Component. `formik-material-ui` connects Formik's Field props like onChange, value, touched and errors to Material UI's custom field components.
