### ISSUE TITLE
Multiple Forms on the same page 

### ISSUE THREAD

**Issue by robinll** [formium/formik#2859]
I have a login form and a forgot password form on the same page.  The login form has fields for username and password and the forgot password form has a field for an email address.  The forms are toggled by state and never appear on the page at the same time.

<Wrapper>
    <UserLogin></UserLogin>
    <ForgotPassword></ForgotPassword>
</Wrapper>

When I switch from the login form to the forgot password form, the initalTouched and touched properties from fields on the the login form persist, but not the values.  So when I'm viewing the forgot password form, I have values for the username, password, and email address fields in the touched and initialTouched properties instead of just values for the email address.

I would expect that when a new form loads it would only have the information about fields in the currently loaded form.

**Comment by adebiyial** [comment]
Hello @robinll, can you share your code snippet? Or is this something that can be re-created on Codesandbox?

**Comment by robinll** [comment]
1.  Yes this does happen the other way around.  

This is very stripped down, but In my parent component, I have this snippet:

{this.state.view === 'logIn' ? (
	<UserLogin /> 
) : null}
{this.state.view === 'forgotPassword' ? (
	<ForgotPassword />
) : null}


**UserLogin**

<Formik
	initialValues={this.initialValues}
	validationSchema={UserLoginSchema}
	onSubmit={this.handleSubmit}
	enableReinitialize={true}
	key="userLogin"
>
	{formProps => {
             return(
                  <Form>
		        <Field id="username" name="username"/>
                       <Field id="password" name="password"/>
                       <div  className="submit-button button-primary green"
		             onClick={() => { 
			           formProps.submitForm()
		          }}>Log In</div>
                </Form>
            )
	}}
</Formik>

**ForgotPasword**

<Formik
	initialValues={this.initialValues}
	validationSchema={ForgotPasswordSchema}
	onSubmit={this.handleSubmit}
	enableReinitialize={true}
	key="forgotPassword"
>
	{formProps => {
		return(
		     <Form>
			    <Field id="fgt_pw_username" name="fgt_pw_username"/>
                            <div className="submit-button button-primary green"
					onClick={() => { 
						formProps.submitForm()
					}}>Submit</div>
			</Form>
		)
	}}
</Formik>

**Comment by adebiyial** [comment]
Great @robinll, according to the snippet, I re-created this Codesansbox and everything works fine: https://codesandbox.io/s/formik-default-renders-issue-mqfur

Please check it out and see if I captured what you have.

**Comment by robinll** [comment]
In your Codesandbox, the log statments are not writing out the actual values of formProps.touched and formProps.initialTouched.  It's just writing out the values as 'Object'. But other than that, yes, this is basically what I have.

**Comment by adebiyial** [comment]
![image](https://user-images.githubusercontent.com/18689106/99011408-57759d00-254c-11eb-9e28-a180149a5151.png)
Do you mean, like // B? @robinll

**Comment by robinll** [comment]
Yes, like B.  I don't see that the initalTouched property has any value in your example.  I guess I don't really understand why that property is being populated with values in my code.

**Comment by adebiyial** [comment]
Yes, I wonder why. You might want to try re-creating your components following my code.
