### ISSUE TITLE
<form> usage in examples is a security risk when JavaScript fails

### ISSUE THREAD

**Issue by WestonThayer** [formium/formik#2860]
## 📖 Documentation

Take the example on https://formik.org/docs/overview:

```jsx
<form onSubmit={handleSubmit}>
  <input name="email" ... />
  <input name="password" ... />
  <button type="submit" ... >Submit</button>
</form>
```

If you were to ship that code to production, and a client had JavaScript disabled, or there were unhandled JS exceptions that prevent `handleSubmit` from calling `e.preventDefault`, the `<form>` will fall back to it's default behavior, which is `method="get"`, which will navigate to `/sign-in?email=user%40example.com&password=Password!` (assuming the above code is on the `/sign-in` route), exposing the password as plain text in the URL bar.

This could leak the plain text password to any sort of analytics tracker.

I suggest adding `method="post"` to the `<form>`.

**Comment by maddhruv** [comment]
Hey @WestonThayer we would really appreciate if you can raise a PR updating the example code 🤝

**Comment by WestonThayer** [comment]
@maddhruv sure thing, see https://github.com/formium/formik/pull/2873.
