### ISSUE TITLE
A duplicate value is added automatically in form values and touched object

### ISSUE THREAD

**Issue by yogesh021** [formium/formik#2864]
## ❓Question
I am writing a contact detail form where two input fields(name, contact) are required to be filled.
A user can add multiple contact details. I'm using FieldArray.

Here's [code](https://codesandbox.io/s/tender-mendeleev-4ntcs?file=/src/App.js)

 
Below is `ValidationSchema` for name and contact.
```
const FormSchema = Yup.object().shape({
  Details: Yup.array()
    .of(
      Yup.object().shape({
        name: Yup.string()
          .trim()
          .min(4, "too short!")
          .max(40, "Too long!")
          .required("Required"), // these constraints take precedence
        contact: Yup.number()
          .max(10, "Invalid no")
          .min(10, "Invalid no")
          .required("Required") // these constraints take precedence
      })
    )
    .required("Must have name and phone no.") // these constraints are shown if and only if inner constraints are satisfied
});
```

**Issue**: 

![fieldarray-screenshot](https://user-images.githubusercontent.com/43965132/98277874-d81d2200-1fbd-11eb-8488-b2fd8e8f3751.PNG)

When I console.log, Both Input fields are displaying `Required` for any kind of error in Input. 
Also a new field in values and touched object is created with the same name as of FieldArray. Only difference is the FieldArray name is **Details** and duplicate field is **details** . Notice the Capitalization. @jaredpalmer @johnrom @TrySound @brikou @rahulbhooteshwar

**Comment by johnrom** [comment]
Please don't ping when opening an issue.

`Details` in your initialValues doesn't match the `name` prop passed to your fields, `details[index].value`. Note the capitalization. They should match.
