### ISSUE TITLE
Form Validation onChange not working on v2.2.2

### ISSUE THREAD

**Issue by daryanka** [formium/formik#2866]
### Current Behavior

Form not validating on change, instead it only validates on blur. Even with the validateOnChange prop.

### Expected behavior

Fields should be validating on change

### Reproducible example

CodeSandbox link: https://codesandbox.io/s/frosty-mountain-tyifi?file=/src/index.js

### Additional context

This is only occurring on v2.2.2, I have tested with v2.2.1 and it does correctly validate on change on the older version.

Using Yup for validation.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.2
| React            | 17.0.0

**Comment by jasson2788** [comment]
Yes, I have the same bug but with the validate prop.

**Comment by raoul2000** [comment]
same here : no validation onChange .. only onBlur and submit

**Comment by karthias93** [comment]
same here In version 2.2.2 onChange validation not working properly

**Comment by jan-tee** [comment]
Same here.

**Comment by karlosvallejo** [comment]
The v2.2.3 release solve this for me.

**Comment by daryanka** [comment]
Thanks for letting me know @karlosvallejo 
Just tested it out on v2.2.3 and its fixed https://codesandbox.io/s/keen-fire-r5y8b

Closing issue.

**Comment by sernaferna** [comment]
Did a subsequent version break this again? On 2.2.9 I'm still seeing that validation is not happening in onChange, only onBlur.

Relevant code for a simple login screen (leveraging react-bootstrap for the UI controls):

```TSX
const schema = yup.object({
  loginUsername: yup.string().required('Please enter a username'),
  loginPassword: yup.string().required('Please enter a password'),
});
type ValuesSchema = yup.InferType<typeof schema>;

export const Login = () => {
  return (
    <Formik
      initialValues={initialValues} // elided
      validationSchema={schema}
      onSubmit={formSubmit} // elided
      validateOnBlur={true}
      validateOnChange={true} // not working???
    >
      {(fp: FormikProps<ValuesSchema>) => (
        <Form noValidate onSubmit={fp.handleSubmit}>
          <Form.Group>
            <Form.Label>User Name</Form.Label>
            <Form.Control
              placeholder="username"
              name="loginUsername"
              value={fp.values.loginUsername}
              onChange={fp.handleChange}
              onBlur={fp.handleBlur}
              type="text"
              isValid={fp.touched.loginUsername && !fp.errors.loginUsername}
              isInvalid={fp.touched.loginUsername && !!fp.errors.loginUsername}
            />
            <Form.Control.Feedback type="invalid">{fp.errors.loginUsername}</Form.Control.Feedback>
          </Form.Group>

          <Form.Group>
            <Form.Label>Password</Form.Label>
            <Form.Control
              type="password"
              placeholder="password"
              name="loginPassword"
              value={fp.values.loginPassword}
              onChange={fp.handleChange}
              onBlur={fp.handleBlur}
              isValid={fp.touched.loginPassword && !fp.errors.loginPassword}
              isInvalid={fp.touched.loginPassword && !!fp.errors.loginPassword}
            />
            <Form.Control.Feedback type="invalid">{fp.errors.loginPassword}</Form.Control.Feedback>
          </Form.Group>

          <Button
            variant="primary"
            type="submit"
            disabled={
              fp.isSubmitting ||
              !!fp.errors.loginUsername ||
              !!fp.errors.loginPassword ||
              !fp.touched.loginUsername ||
              !fp.touched.loginPassword
            }
          >
            Login
          </Button>
        </Form>
      )}
    </Formik>
  );
};

```

When entering text in that form, username then password, the submit button doesn't get enabled until I Tab off the password field. The following tweaks, however, can *force* it to work:

```TSX
            <Form.Control
              name="loginUsername"
              onChange={(e) => {
                fp.setFieldTouched('loginUsername', true, true);
                fp.handleChange(e);
              }}
            />

            <Form.Control
              name="loginPassword"
              onChange={(e) => {
                fp.setFieldTouched('loginPassword', true, true);
                fp.handleChange(e);
              }}
            />

```

**Comment by brycefranzen** [comment]
We're having the same issue. It was fixed in 2.2.3 and still worked in 2.2.4.  However, it is broken again with any newer version past that. :/

Could we please re-open this issue?  Thanks!

**Comment by dev-ishwar** [comment]
I'm facing the same issue in 2.2.9. validateOnChange is not working initially though it starts working if I tab out and start making changes to the field again.
Does anyone have a workaround for this? Thanks! 
@sernaferna did you find any workaround??

**Comment by sernaferna** [comment]
Only the workaround mentioned above, of manually setting the field to touched in `onChange` before calling the Formik `handleChange` callback to do its usual work.

If that's still not working for you check how you're using the information. e.g. in my code sample above I'm disabling the button if there are any errors or if either of the fields isn't "touched." If you have different logic for enabling/disabling things, or for error vs. "it's valid" messaging for specific fields, you might need to approach things a bit differently than what I did.

**Comment by itamarmoa** [comment]
Hi :) Issue still happening with version 2.4.3

**Comment by samiullahMtechub** [comment]
you can solve it by passing touched object to the formik and validate your text input if it is focused and you onBlur i am sharing a code snippet it may help you all



  <Formik
            initialValues={{
              email: '',
              password: '',
            }}
            validationSchema={formSchema}
            validateOnChange={true}
            validateOnBlur
            onSubmit={values =>
              handleCreate(values.email, values.password)
            }>
            {({
              values,
              handleChange,
              handleBlur,
              handleSubmit,
              touched,
              errors,
            }) => (
              <>
                <TextField
                  label={'Email'}
                  onChangeText={handleChange('email')}
                  value={values.email}
                  // onFocus={()=>setEmailFocused(true)}
                  onBlur={handleBlur('email')}
                />
                {errors.email&&touched.email && (
                  <View flexDir={'row'} alignItems={'center'} mt={1} ml={2}>
                    <View
                      bg={'red.500'}
                      h={1}
                      w={1}
                      rounded={'full'}
                      mx={1}></View>
                    <Text color={'red.500'} fontSize={12}>
                      {errors.email}
                    </Text>
                  </View>
                )}
                <TextField
                  label={'Password'}
                  onChangeText={handleChange('password')}
                  value={values.password}
                  onBlur={handleBlur('email')}
                />
                {errors.password &&touched.password&& (
                  <View flexDir={'row'} alignItems={'center'} mt={1} ml={1}>
                    <View
                      bg={'red.500'}
                      h={1}
                      w={1}
                      rounded={'full'}
                      mx={1}></View>
                    <Text color={'red.500'} fontSize={12}>
                      {errors.password}
                    </Text>
                  </View>
                )}
                <TouchableOpacity
                  onPress={() => {
                    navigation.navigate('ForgetPassword');
                  }}>
                  <Text
                    fontSize={'16'}
                    mr={2}
                    textAlign={'right'}
                    color={'pro'}
                    mt={4}
                    fontFamily={'Jost-Medium'}>
                    Forgot Password?
                  </Text>
                </TouchableOpacity>

                <View mt={'40%'}>
                  <AButtons label={'Sign In'} loading={isLoading} onPress={()=>{if(values?.email!==''||values?.password!==''){handleSubmit()}
                else{
                  setEmailFocused(true);
                  setPasswordFocused(true);
                }
                }} />
                </View>
              </>
            )}
          </Formik>
          
          
          
          
          this solved my error for validate my inputs on the basis of value change
