### ISSUE TITLE
showing formik error

### ISSUE THREAD

**Issue by kyle-hensoon** [formium/formik#2868]
## ❓Question

i want show form errors for user , but actually i want show error like a chain , i mean when user doesn't fill the first input , formik try to show just this input error  and while user fill the input , formik show second input error if it empty

how i can do this ?

**Comment by adebiyial** [comment]
Hey there @kyle-hensoon, I made a quick demo here: https://codesandbox.io/s/showing-formik-error-qcl05?file=/src/App.js

Let's see if that solves your needs.
