### ISSUE TITLE
typescript error bug v2.2.4

### ISSUE THREAD

**Issue by maystrenkoYurii** [formium/formik#2888]
"formik": "2.2.4"
<img width="1775" alt="Снимок экрана 2020-11-11 в 12 01 52" src="https://user-images.githubusercontent.com/23016311/98797886-dc11cf80-2415-11eb-86c7-04c6f33e0108.png">

**Comment by yohai-zv** [comment]
Also in "2.2.2"

**Comment by jaredpalmer** [comment]
@umidbekkarimov can you please look into this?
