### ISSUE TITLE
The onSubmit method of the useFormik hook and jest

### ISSUE THREAD

**Issue by AlexeyKorkoza** [formium/formik#2901]
## ❓Question
Hi, I faced one issue that I cannot resolve. I try to test the `onSubmit` method using `jest`.
So, I created my custom hook where I made calling useEffect hooks to fetch data from the backend and the initialization of the useFormik hook. The hook is used in my component.
However, I couldn't find any tests in the repository or any articles in the documentation to test the `onSubmit` method.  
Below I added the part of the code where I had made the initialization of the useFormik hook.
```
const useTestHook = () => {

const useFormikProps = useFormik({
        initialValues: {
            firstName: "",
            lastName: "",
        },
        onSubmit: (values) => {
            const formData = createFormData(values)
            // here I send the data to the backend
        },
        validateOnBlur: true,
        validationSchema: schema,
    })
  
return {
     useFormikProps 
  }
}
```

Could anyone, please, help me to write tests right? 
Thanks in advance.

**Comment by krvajal** [comment]
Are you trying to test Formik, or your a specific form in your app? 
The `onSubmit` method is called by Formik when you submit your form. You can either call `useFormikProps.handleSubmit` with a https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent or if you are testing an actual form, just trigger the form submission like an normal user would do

**Comment by AlexeyKorkoza** [comment]
@krvajal Actually, I am trying to test my hook and, especially, I want to make sure that the `onSubmit` method will be called with the form values.
I have created the repository to reproduce my issue. 
https://github.com/AlexeyKorkoza/formik-reproduce-issue

So, my test passes, however, when I look at the test coverage the lines of the `onSubmit` method aren't covered.

**Comment by krvajal** [comment]
Does this helps?

https://github.com/AlexeyKorkoza/formik-reproduce-issue/pull/1

**Comment by AlexeyKorkoza** [comment]
@krvajal Thank you very much for your pull request but it didn't help me.
So, I committed new changes to the repository to reproduce the issue exactly. I am sorry if I didn't explain my issue clearly in the first comment.
I added the modal component because my form appears inside it. I must mock the returned values of the hook in the 'App.test.js`. It allows me to find the button. However, the line where it occurred the submitting the form doesn't help to cover. 
I would want to test that the `onSubmit` method has been called once as a minimum and it has been called with the values.

**Comment by AlexeyKorkoza** [comment]
I will close this issue because it has become not actual for me. In last month I found an article on how to test formik using `react-testing-library` a right way and also I understood where I had made some mistakes. 
Article link: https://testing-library.com/docs/example-react-formik/

**Comment by huykon** [comment]
@AlexeyKorkoza your solution of formik only work for situation we have prop is function submit form. If I haven't, how to handle it?

**Comment by Mori-666** [comment]
Hi, Could you share the solution you found cuz i probably have the same issue as you and cant find any answer about it. @AlexeyKorkoza
