### ISSUE TITLE
How to disable formik's auto submit on Enter?

### ISSUE THREAD

**Issue by oieeaaaa** [formium/formik#2907]
## ❓Question

I'm having a hard time trying to disable Formik's auto submit on enter.

The issue occurs, after pressing `Enter` on my **custom multi-select** input.

I wonder if there is a way to disable auto-submit on `Enter` in Formik.

ss:
<img width="273" alt="Screen Shot 2020-11-16 at 8 46 35 AM" src="https://user-images.githubusercontent.com/37941956/99201924-506abb00-27e8-11eb-9114-e010e6d5dfdd.png">

**Comment by davidohlin** [comment]
@oieeaaaa I had to disable submit on enter press from the forms inputs. I solved it by checking for enter press in `onKeyPress` and calling `e.preventDefault()`.

Example:

```html
<form onSubmit={handleSubmit} className="p-3">
  <input
    type="text"
    name="pin"
    value={values.pin}
    onKeyPress={e => { e.which === 13 && e.preventDefault() }}
    onChange={handleChange}
/>
</form>
```

Hope this helps!

**Comment by oieeaaaa** [comment]
Thanks, Man!

**Comment by kreshnik01** [comment]
`onKeyPress` has been deprecated [(read-here)](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) alongside with 'which' [(read-here)](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event).

You can use its equivalent `onKeyDown` with `e.key` instead of `e.which`

```
<form onSubmit={handleSubmit}>
  <input
    type="text"
    name="pin"
    value={values.pin}
    onKeyDown={e => { e.key === 'Enter' && e.preventDefault() }}
    onChange={handleChange}
/>
</form>
```

**Comment by jtw-r** [comment]
I ran into this problem but had an extra layer since I was using multiline textareas. The user wanted to type new-lines using the enter key so I couldn't `event.preventDefault()`.

Instead, I unwrapped my parent Formik element, and removed the `<Form></Form>` element, since the HTML `<form>` element also submits on return. I'm not sure if this is bad practice though?

For my submit buttons, I have them in separate component files, but I just get the formik context hook and use the provided `submitForm` function it passes down. Ex:
```tsx
export default const SubmitButton = () => {
  const { handleSubmit, ..._ } = useFormikContext<T>()

  return (
    <button type={"submit"} onClick={handleSubmit} className={"fancy-button-that-requires-its-own-file"}>Submit</button>
  );
}
```

**Comment by sanajani** [comment]
add this function in your file  and then         <Form onKeyDown={handleKeyPress}>
add onKeyDown on your Formik Form function
 const handleKeyPress = (e) => {
    // Prevent form submission on Enter key press
    if (e.key === 'Enter') {
      e.preventDefault();
    }
  };
