### ISSUE TITLE
useformik hook doesnt receive the latest form values on submitting the form

### ISSUE THREAD

**Issue by 12sam12** [formium/formik#2908]
### Current Behavior

useFormik hook doesnt receive the form data on submit

```
const formik = useFormik({
      initialValues: {
          email: "12345",
          password: "67890"
      },
      onSubmit: async (values,a,b,c) => {
          console.log(values);       // logs above initialvalues
      }
    });
<div>
        <form onSubmit={formik.handleSubmit}>
        </form>
</div>
```

### Expected behavior

```
onSubmit: async (values,a,b,c) => {
       console.log(values);       // to log new form submitted values
}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | "^2.2.2"
| React            |  "^17.0.1"
| TypeScript       |  "Not used"
| Browser          |  "chrome"
| npm/Yarn         |  "npm  6.14.4"
| Operating System |  "Linux, Ubuntu, Focal Fossa"

**Comment by fabricioNavarrete95** [comment]
Greetings @12sam12.
I would like to know how you solved this bug. Because I am in the same situation currently, the onSubmit method is not called and I did this according to the documentation with useFormik I have used the same props but it still does not work.
