### ISSUE TITLE
Multiple material UI inputs in Formik FieldArray very slow

### ISSUE THREAD

**Issue by oualidmaz** [formium/formik#2920]
### Current Behavior
Trying to add multiple Textfiled in Fromik form using FieldArray. But when filling the inputs there is a delay (very slow).
However, when inputs are out of the array there is no delay 

### Reproducible example
https://codesandbox.io/s/formik-fieldarray-forked-itytq

Steps:

1. click on "add products" to generate Textfiled inputs
2. Press and hold any key on any input
3. Notice the delay

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.1
| React            | 17.01
| Browser          | Chrome

**Comment by Pfahlf** [comment]
Any news on this? Having the same exact problem...

**Comment by oualidmaz** [comment]
this bug occurs  cause when you try fill any input the whole inputs in the FiledArray are re-rendered. the only solution I found is using react-hook-form https://react-hook-form.com/ .  which is built in isolate re-renders

**Comment by Pfahlf** [comment]
@oualidmaz Thank you very much! I did saw your issue and answer on material-ui and already moved to react-hook-form! Have a nice day

**Comment by johnrom** [comment]
v3 will have isolated renders, unfortunately it is impossible in v2's API due to overdependence on React Context.

**Comment by tparvi** [comment]
> v3 will have isolated renders, unfortunately it is impossible in v2's API due to overdependence on React Context.

We are currently using v3 beta. How do we use FieldArray correctly so that we don't get this behavior? Right now we are using FieldArray the same way as v2 documentation shows and it is very slow even with few items.

**Comment by tparvi** [comment]
ping @johnrom do you have any pointers on how to use FieldArray in v3 so that we don't get this behavior? We are using formik@3.0.0-next.8 but the issue persists.

**Comment by johnrom** [comment]
@tparvi unfortunately I don't have any updates on the status of v3 nor have I contributed to the `next` branch

v3 may be considered in a state of flux as I have recommended a different method of optimization than what has been released on that branch.
