### ISSUE TITLE
How To Upload a file using Formik

### ISSUE THREAD

**Issue by Yakusa26** [formium/formik#2923]
## ❓Question

Hi Team, 
Thanks for the great work that you are doing on Formik. 

I was wondering if there is a way to upload a file using formik? 
I found this: https://github.com/formium/formik/issues/45
Is it the same? 
I try this, but, eveytime, the file is not uploaded because of my "HandleChange"

`<Formik
                        onSubmit={location.datas ? this.update : this.submit}
                        initialValues={{nom: '', 
                                        prenom: '', 
                                            numCNI: '', 
                                            birth: '', 
                                            photo: '', 
                                            tel: '', 
                                            whatsapp:  '', 
                                            ville: '', 
                                            quartier: '', 
                                            email: '', 
                                            pass: '',
                                            confirmPass: ''}}
                        // validate={this.validate}
                    >
                    {({ handleSubmit, handleChange, handleBlur,setFieldValue, values, isSubmitting, errors, touched }) => (
                    <form onSubmit={handleSubmit} encType="multipart/form-data" method="POST">
                    <div className="modal">
                        <div className="modal-content modal-content-1">
                            <img src={Cross} className="modal-icon"  onClick={this.closeModal} alt="" />
                            <h2>Enregistrer une CNI</h2>
                            <br/>
                            <div className="input-flex">
                                <div className="input-wrapper">
                                    <p className="input-label">Nom</p>
                                    <input type="text" 
                                        name="nom"
                                        id="nom"
                                        onChange={handleChange}
                                        onBlur={handleBlur}
                                        value={values.nom}
                                    />
                                    {errors.nom && touched.nom ? (<label className="text-danger">{errors.nom}</label>) : null}
                                </div>
                                <br/>
                                <div className="input-wrapper">
                                    <p className="input-label">Prénom</p>
                                    <input type="text" 
                                        name="prenom" 
                                        value={values.prenom} 
                                        onChange = {handleChange} 
                                        onBlur={handleBlur} 
                                    />
                                    {errors.prenom && touched.prenom ? (<label className="text-danger">{errors.prenom}</label>) : null}
                                </div>
                            </div>
                            
                            <div className="input-wrapper">
                                <p className="input-label">Photo de la CNI</p>
                                <div className="file-wrapper">
                                    <img src={Id} className="file-icon" alt="" />
                                    <p>Ajouter un fichier</p>
                                    <input type="file" 
                                        name="photo" 
                                        id="photo"
                                        value={values.photo} 
                                        className="form-control" 
                                        **onChange = {(event) =>{
                                            setFieldValue("imgCNI", event.currentTarget.files[0]);
                                          }}**
                                        onBlur={handleBlur}     
                                    />
                                </div>
                            </div>
                            <br/>...`

Thanks For you help

**Comment by johnrom** [comment]
It is the same, but because you are using the File object returned from the browser, you must submit your form using a FormData object as `application/x-www-form-urlencoded`.

So you build an object like ```
const formData = new FormData();
formData.append("myFile", values.photo);

fetch("/my/api", {
  method: 'POST',
  body: formData,
};
```
