### ISSUE TITLE
Error updating to version 3.0.0-next.7

### ISSUE THREAD

**Issue by deniscpereira** [formium/formik#2925]
## ❓Question

Hello guys, I updated my version to 3.0.0-next.7 because I need the feature format and parse but I have an error that I didn't have before.

Has errors in the properties that are passed to the component

`Property 'options' does not exist on type '(IntrinsicAttributes & ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & UseFieldProps<...> & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>)'.`

`Property 'fluid' does not exist on type '(IntrinsicAttributes & ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & UseFieldProps<...> & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>)'.`

`Property 'options' does not exist on type '(IntrinsicAttributes & ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & UseFieldProps<...> & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>)'.`

`Property 'multiple' does not exist on type '(IntrinsicAttributes & ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & UseFieldProps<...> & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>) | (IntrinsicAttributes & ... 3 more ... & SharedFieldProps<...>)'.` .....

Field error

```
<Field
      name='estabelecimentos'
      component={FDropdown}
      options={estabelecimentos}   // <- has error
      fluid                                        // <- has error
      multiple                                  // <- has error
      search                                   // <- has error
      selection                               // <- has error
      noResultsMessage="Estabelecimento não encontrado"  // <- has error
      className="input"
/>
```

```
const FDropdown = ({ field, form: { setFieldValue, setFieldTouched }, ...props }: any) => (
	<Dropdown
		{...field}
		{...props}
		onChange={(e, { name, value }) => setFieldValue([name], value)}
		onBlur={(e, { name }) => setFieldTouched([name], true, true)}
	/>
)
```

If you can help me please with some example of correction ... I'm a beginner react typescript

**Comment by jaredpalmer** [comment]
Looks like it may have been a regression in TS
