### ISSUE TITLE
Alternative wizard multi-step form abstraction

### ISSUE THREAD

**Issue by klis87** [formium/formik#2930]
### Current Behavior

There is no built-in way to create wizard forms, there is an example though [here](https://github.com/formium/formik/blob/master/examples/MultistepWizard.js). However, this is not flexible enough and is not too reusable.

### Desired Behavior

We should have a reusable component to make such forms. Moreover, current solution in example doesn't take more complex scenarios into account, for example validation among fields from multiple steps. 

### Suggested Solution

I created the following prototype:
```js
const FormikWizard = ({
  validationSchemas,
  onSubmit,
  children,
  initialValues: customInitialValues,
}) => {
  const [currentStep, setCurrentStep] = useState(0);
  const validationSchema = useMemo(
    () => validationSchemas.reduce((prev, current) => prev.concat(current)),
    [validationSchemas],
  );
  const initialValues = useMemo(
    () => customInitialValues || validationSchema.default(),
    [validationSchema, customInitialValues],
  );
  const validationSchemasCascading = useMemo(
    () =>
      validationSchemas.reduce((prev, current) => {
        const previousSchema = prev.length === 0 ? null : prev[prev.length - 1];
        return prev.concat(
          previousSchema ? previousSchema.concat(current) : current,
        );
      }, []),
    [validationSchemas],
  );

  return (
    <Formik
      validationSchema={validationSchemasCascading[currentStep]}
      initialValues={initialValues}
      onSubmit={async (values, actions) => {
        if (currentStep === validationSchemas.length - 1) {
          return onSubmit(values, actions);
        }

        setCurrentStep(v => v + 1);
        actions.resetForm(values);
      }}
    >
      {formik => children({ ...formik, currentStep, setCurrentStep })}
    </Formik>
  );
};
```

You could use it like that:
```js
const schemas = [schema1, schema2, schema3];

<FormikWizard
   validationSchemas={validationSchemas}
   onSubmit={handleSubmit}
 >
  {({ values, currentStep, setCurrentStep }) => {
    return (
     <Form>
       <Stepper activeStep={currentStep}>
         <Step>
           <StepLabel>Step 1</StepLabel>
         </Step>
         <Step>
           <StepLabel>Step 2</StepLabel>
         </Step>
         <Step>
           <StepLabel>Step 3</StepLabel>
         </Step>
       </Stepper>
       {currentStep === 0 && <FieldsForStep1 />}
       {currentStep === 1 && <FieldsForStep2 />}
       {currentStep === 2 && <FieldsForStep3 />}
       {currentStep > 0 && (
         <Button
           type="button"
           onClick={() => setCurrentStep(v => v - 1)}
         >
           Go back
         </Button>
       )}       
       <Button type="submit">Save/Go next</Button>
     </Form>
   );
 }}
</FormikWizard>
```

Interesting part is that you don't need to pass initial values, those are calculated from merged schema. 

Another part is that Formik children render props are extended with wizard related stuff - `currentStep` and `setCurrentStep`.

And yet another one, passed `validationSchema` to `Formik` is.. I would call it cascading. For step 0 it is first schema, for 1 it is first and second schema merged and so on. This is to support conditional/dependent validation across multiple steps. 

It would be cool to add a reusable component such as this to the core or as a community package. Above prototype could be extended, probably to support also `validate` not only schemas and so on.

### Who does this impact? Who is this for?

Anyone needing multi-step forms

### Describe alternatives you've considered

Shown examples

### Additional context
n/a

**Comment by jaredpalmer** [comment]
I like this. Add a PR with an example?

**Comment by klis87** [comment]
@jaredpalmer I could do this, but what would you say about also a community package I will maintain? I think example is one thing, but reinventing the wheel by copying it for every project using wizard is inferior in comparison to have a ready to use abstraction.

**Comment by athenawisdoms** [comment]
@klis87 Will love a community package, been looking everywhere for one! 

Has one been published to NPM yet?

**Comment by klis87** [comment]
@athenawisdoms no, because I didn't receive any confirmation, and without making this official it doesn't make sense for me to do it, as I am not popular enough to make this addon popular, hence community won't gain too much ;)

**Comment by athenawisdoms** [comment]
@jaredpetker Any chance this can be incorporated into a community package if it is built?

**Comment by jaredpetker** [comment]
Hey @athenawisdoms, I believe you got the wrong Jared P. Though I do enjoy formik, but believe you're looking for @jaredpalmer

**Comment by athenawisdoms** [comment]
@jaredpalmer Any chance this can be incorporated into a community package if it is built? :)

**Comment by harshamv** [comment]
Any update on this?
