### ISSUE TITLE
what is formik.registerField()?

### ISSUE THREAD

**Issue by hacker0limbo** [formium/formik#2940]
## ❓Question

I find there are two methods get exposed when using `useFormik()` hook, which is `registerField()` and `unregisterField()`:

```typescript
registerField: (name: string, { validate }: any) => void;
unregisterField: (name: string) => void;
```

However I didn't see doc mentioned those two methods and i am wondering the use case of it and more importantly how to use it.

Tried to do like this, but not sure if this is correct:

```js
formik.registerField('somefield', {
  validate(value) {
    let errorMessage
    if (!value) {
      errorMessage = 'Required'
    }
    return errorMessage
  }
})
```

**Comment by jaredpalmer** [comment]
This is an internal method that passes a `validate` function back up to the parent `<Formik>` for field-level validation orchestration. It should only be used in an effect. It used inside of Field and FastField. In addition, when using, you need to also cleanup the effect with `unregisterField` as well

**Comment by jaredpalmer** [comment]
It is not documented because the registration mechanism may change over time and we do not make guarantees about breaking this method between semantic versions
