### ISSUE TITLE
Support custom props defined on <Formik>

### ISSUE THREAD

**Issue by dmudro** [formium/formik#2948]
## Feature request
There is a need to pass custom prop, i. e. `foo`:

```
...
<Formik
  initialValues={...}
  onSubmit={...}
  component={ModalForm}
  foo="bar"
/>
...
```

...down onto the mounted / rendered form component:

```
...
type Props = FormikProps<Values> & {
  foo: string;
}

const ModalForm: React.FC<Props> = ({ foo }) => {
  // foo is undefined
}
...
```

### Current Behavior

Custom prop does not get passed and the value is undefined.

### Desired Behavior

I am able to access the passed prop value.

### Suggested Solution

Could any custom prop defined on <Formik> get passed?

### Describe alternatives you've considered

Currently the only workaround is to render with `children` instead of `component`:

```
<Formik
  initialValues={...}
  onSubmit={...}
>
  {(props) => (
    <ModalForm
      {...props}
      foo="bar"
    />
  )}
</Formik>
```

**Comment by johnrom** [comment]
You can provide a custom context to your own components in any way you want with React Context:

I don't recommend adding any custom props to Formik because the API could change in the future and conflict with some custom props you end up creating. I'd recommend this all be handled in pure React and the concerns remain separate.

```jsx
const MyFormStateContext = React.createContext({}),
const MyForm = () => {
  const [myState, setMyState] = React.useState();
  useEffect(() => {
    setMyState('updated');
  });
  return <MyFormStateContext.Provider value={{ myState }}>
    <Formik {...formikProps} component={MyFormComponent} />
  </MyFormStateContext>
}
const MyFormComponent = () => {
  const formContext = React.useContext(MyFormStateContext);

  useEffect(() => {
    console.log('context: ', formContext.myState);
  }, [formContext.myState]);
}
```

**Comment by dmudro** [comment]
Fair enough, the potential prop name conflict is a valid concern.

Employing React context probably too heavy for simple use cases; will stick to the render prop pattern for now.
