### ISSUE TITLE
Incomplete type of error property in FieldMetaProps

### ISSUE THREAD

**Issue by mindtraveller** [formium/formik#2953]
### Current Behavior

The `error` property of `FieldMetaProps` interface is declared to be only of `string` type. 

### Expected behavior

The `error` property of `FieldMetaProps` interface can be `string` or `string[]`.

### Reproducible example

The yup shema which returns list of strings as errors:
```
const EMAIL_LIST_RULE = yup.array<string>()
  .strict(false)
  .transform((_, originalValue: string) => originalValue.split(';')
    .map(it => it.trim())
    .filter(it => !!it),
  )
  .of(yup.string().email('validationErrors.invalidEmail'))

yup.object({
  cc: EMAIL_LIST_RULE,
})

// provide cc with values of '1231231;123123'
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.5
| React            | 16.12.0
| TypeScript       | 3.8.3
| yup       | 0.28.1
| Operating System | macos 11.0.1

**Comment by mindtraveller** [comment]
any response?

**Comment by wtorsi** [comment]
It could be an object as well
