### ISSUE TITLE
Manage "disabled" state of form fields

### ISSUE THREAD

**Issue by halcarleton** [formium/formik#2971]
### Current Behavior

Currently, the disabled prop needs to be directly passed to the form field/input to disable it.

### Desired Behavior

I would like to control the disabled state of inputs through formik context.

### Suggested Solution

* Add `disabled: boolean` prop to FieldInputProps
* Add `setDisabled: (value: boolean, shouldValidate?: boolean) => void` method to FieldHelperProps
* Add `disabled: { [key: string]: boolean }` to formik bag
* Add `setFieldDisabled: (field: string, value: boolean, shouldValidate?: boolean) => void` to formik bag
* Add `initialDisabled: { [key: string]: boolean }` prop to the Formik component
* Update the Field component to disable the field if it is marked as disabled in formik context.

### Who does this impact? Who is this for?

This is for anyone who needs top level logic to control the disabled state of inputs.

### Describe alternatives you've considered

The no-op solution, and what I am currently using, is to just track this state in custom context. This works, but seems like unnecessary additional effort to manage form state.

### Additional context

Here's a use case:

Image you have a form which is used both for creating a resource and editing a resource. It displays all the same fields, but during an edit, some of those fields need to be disabled because they cannot be edited after creation.

With this solution, you could simply change the `initialDisabled` prop being passed to the Formik component to initialize those fields as disabled, and update the `onSubmit` handler to use the appropriate http request for editing the resource.

**Comment by halcarleton** [comment]
bump

**Comment by halcarleton** [comment]
bump

**Comment by halcarleton** [comment]
bump

**Comment by halcarleton** [comment]
bump

**Comment by johnrom** [comment]
This is a duplicate of #2454

**Comment by KSBarsukov** [comment]
bump
