### ISSUE TITLE
Field not touched when using up/down arrow selectors on type='number' Fields

### ISSUE THREAD

**Issue by esr52** [formium/formik#2983]
### Current Behavior
Using up/down "scoller" arrows with mouse on number type Field, setFieldTouched not set.  I'm depending on the touched field to enable an update button.  Seems redundant to have to click inside the field after changing the value using the scoller arrows.  

![image](https://user-images.githubusercontent.com/11124189/103191433-f78c4900-48a2-11eb-9e36-80a44d8feff0.png)

### Expected behavior
When up/down arrow clicked, setFieldTouched should trigger

### Reproducible example
```
<Formik
      initialValues={{
        ...initVals,
      }}
      validationSchema={mylValidationSchema}
      onSubmit={onSubmit}
      enableReinitialize
    >
      {(
        { values, setFieldValue, touched, dirty, isValid, handleBlur } // this is for DatePicker
      ) => (
        <Form styling='structure'>
        ...
                  <div className='block ml-5'>
                        <div className='d-flex'>
                          <div className='input-group'>
                            <Label htmlFor='correctionFactor'>
                              Correction Factor
                            </Label>
                          </div>
                          <Field
                            id='correctionFactor'
                            name='correctionFactor'
                            type='number'
                          />
                        </div>
                        <ErrorMessage
                          name='correctionFactor'
                          component={TextError}
                        />
                      </div>
                      ...
          </Form>)}
    </Formik>
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 16.13.1
| TypeScript       |
| Browser          | Firefox
| npm/Yarn         | npm 
| Operating System | MX Linux 19.3

**Comment by mkarajohn** [comment]
Not sure if this is an acceptable solution, but you could manually set it to `touched` by calling [setFieldTouched](https://formik.org/docs/api/formik#setfieldtouched-field-string-istouched-boolean-shouldvalidate-boolean--void) when the value changes ( I suppose the `onChange` event does fire when you change the number with the buttons)

**Comment by mkarajohn** [comment]
Commenting to remove the stale label

**Comment by johnrom** [comment]
This is not what touched means. Touched occurs when a user left / blurred a field. It is a way for Formik to say "a user is done with this field and may want to know if there were any errors".

**Comment by esr52** [comment]
My proposition is: Tabbing to the field, using arrow keys to select an value from the number scroller and then tabbing to the next field should blur the field without having to hit the “enter” key. 
That is not the current behavior...current behavior is you must hit the enter key to blur the field for type=“number”.

**Comment by johnrom** [comment]
hmm.. interesting. Seems like a browser bug in Firefox to me, I would expect blur to happen as I described above.

**Comment by johnrom** [comment]
Some discussion here on workarounds: https://github.com/facebook/react/issues/11062

I wouldn't probably implement anything like this in Formik itself. Any workarounds can be discussed here, though.

**Comment by mkarajohn** [comment]
wait, what?
