### ISSUE TITLE
useField() with React Native TextInput

### ISSUE THREAD

**Issue by blooak** [formium/formik#2987]
### Current Behavior

When trying to use useField() hook with React Native TextInput component like so:

```javascript
// inside the component
const [field] = useField(props.name);

// return
<TextInput {...field} />
```

When the value changes I get this warning:

```
Warning: Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:
    undefined
    Formik cannot determine which value to update. For more info see https://formik.org/docs/api/formik#handlechange-e-reactchangeeventany--void
```

It's because unlike HTML input, TextInput does not have a "name" or an "id" prop.

### Desired Behavior

There must be an alternative prop support for React Native TextInput.

### Suggested Solution

Maybe using "key" prop alongside "name" and "id" so that React Native TextInput will support it too.

### Who does this impact? Who is this for?

React Native Developers.

**Comment by hsavit1** [comment]
formik hooks don't work with react native. use render props

**Comment by Tsugami** [comment]
I'm using hook but passing the `helpers` instead of the `fields`
```tsx
export function Input({ name, ...rest }: InputProps) {
  const [field, meta, helpers] = useField({ name });

  return (
    <TextInput
      {...rest}
      value={field.value}
      onBlur={() => helpers.setTouched(!meta.touched)}
      onChangeText={helpers.setValue}
    />
  );
}
````
