### ISSUE TITLE
FormikErrors does not allow string for fields with object values

### ISSUE THREAD

**Issue by zenefits-brody** [formium/formik#2996]
### Current Behavior

```
type MyFormValues = {
    foo: { id: string; label: string };
};

const errors: FormikErrors<MyFormValues> = { foo: 'Foo is required' };
```

This gets an error

```
Type 'string' has no properties in common with type 'FormikErrors<{ id: string; label: string; }>'.ts(2559)
```

### Expected behavior

The above code does not get the error.

### Additional context

After looking at the type definition, it looks like Formik assumes field values will always be strings, and when it sees an object in the values type, it assumes there are some nested fields.

Is that by design? 🤔 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4
| React            | 16.10.2
| TypeScript       | 3.8.3
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by zenefits-brody** [comment]
Comment to keep issue active.

**Comment by zenefits-brody** [comment]
Could this be a bug in the types? 🤔

**Comment by johnrom** [comment]
It is not necessarily a bug in the types, but a limitation of the current API.

There is currently no way for Formik to know whether an object is supposed to be a value for a single field, or a set of nested fields.

I think we should consider handling fields in a flat way, so the object looks like:

```ts
values = {
  stringValue: "hello",
  objectValue: { hello: "world" },
  "nested.stringValue": "hello",
  "nested.objectValue": { hello: "world" },
}
```

Then onSubmit, Formik will have a default transformation which turns that into an object like:

```tsx
onSubmit(values) => {
  values === {
    stringValue: "hello",
    objectValue: { hello: "world" },
    nested: { 
      stringValue: "hello",
      objectValue: { hello: "world" },
    }
  }
}
```
