### ISSUE TITLE
Field value, `isValidating` and error are not synchronized.

### ISSUE THREAD

**Issue by mycolaos** [formium/formik#3001]
## Bug report
`error` and `isValidating` is not synchronized with the field value change. Why is it a problem? It isn't possible to have a precise knowledge of the state of validity of a value, i.e. "valid", "invalid", "validating".

### Current Behavior

`isValidating` is not synchronized with the field value change. Example
```
// First render after value changed:
console.log(fieldValue, isValidating) // "an invalid value" false
// Next render: 
console.log(fieldValue, isValidating) // "an invalid value" true
```
or
```
// First render after value changed:
console.log(fieldValue, isValidating, error) // "an invalid value" false undefined
// Next render: 
console.log(fieldValue, isValidating, error) // "an invalid value" false "here is an error"
```

### Expected behavior

`isValidating` must be set to true at the same moment the value changes.
```
// First render after value changed:
console.log(fieldValue, isValidating) // "an invalid value" true
```
or
```
// First render after value changed:
console.log(fieldValue, isValidating, error) // "an invalid value" false "here is an error"
```

### Reproducible example

Just type one more char to get error.
https://codesandbox.io/s/useformik-forked-4fb5l?file=/src/Register.js

### Suggested solution(s)

`isValidating` should be set to true at the same moment a value is changed and, maybe, the error, if the validation in synchronous.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4
| React            |17.0.1
| TypeScript       |4.1.2
| Browser          |Firefox 84.0.2
| npm/Yarn         |6.14.5/1.22.10
| Operating System |Windows 10

**Comment by ericArbour** [comment]
I think this may be a duplicate of #2373.
