### ISSUE TITLE
Support value as numbers on number inputs

### ISSUE THREAD

**Issue by avendiart** [formium/formik#3002]
### Current Behavior

Values of number inputs are treated as strings.

### Desired Behavior

Values of number inputs should be treated as numbers.

### Suggested Solution

Use `event.target.valueAsNumber` or parse value to number within the change handler.

### Who does this impact? Who is this for?

All users.

### Describe alternatives you've considered

An obvious alternative is to parse the value manually (e.g. within the `onSubmit` handler).

### Additional context

Open question: how to deal with NaN in case of an empty value.

**Comment by fxh1357** [comment]
This goes in the same direction as #2775 in which @johnrom metioned the parse property which will be part of v3 (see #2360)

**Comment by johnrom** [comment]
Yes this is a duplicate of many others centered around numbers, checkboxes with boolean values, etc. It is part of v3 because the parse and format would require field.onChange and formik.handleChange to be different, breaking backwards compatibility.

**Comment by avendiart** [comment]
Agree, this might break backwards compatibility, however I'm not sure the proposed solution with user land parse prop will do the trick, as I don't see any benefit using it over other methods involving manual parse. The requested feature implies formik would do the parsing behind the scenes for inputs marked as number inputs by default.

**Comment by johnrom** [comment]
the default parsing for v3 _does_ do this automatically:

https://github.com/formium/formik/pull/2846/files#diff-2421f0a25f33b0ee81ca1de9dee2a1743711e08f273a5733ed03493de527de21R949

**Comment by avendiart** [comment]
Great! It wasn't clear from the comments there would be some default behavior already, but good to know then :)

**Comment by bbigras** [comment]
It still matters.
