### ISSUE TITLE
Custom comparator

### ISSUE THREAD

**Issue by bdrazen** [formium/formik#3004]
## Feature request
Custom comparator functions for determining dirty state.

### Suggested Solution
```
initialValues={{
  accountName: data.accountName
  payDate: data.payDate
}}
comparator={{
  payDate: (old, new) => moment(new).isSame(old, 'day')
}}
```

**Comment by jaredpalmer** [comment]
```jsx
const App = data => {
  const { initialValues, values } = useFormik({
    accountName: data.accountName,
    payDate: data.payDate
  });
  const isPayDateDirty = moment(values.payDate).isSame(
    initialValues.payDate,
    "day"
  );
  return ...
};
```

Side note: I suggest avoiding `moment.js` if you can and instead using [`date-fns`](https://date-fns.org/). Moment is no longer maintained https://www.theregister.com/2020/09/15/moment_js_javascript_library_future/ and I'm pretty sure Google Lighthouse will now warn you if you use moment.js in your site (https://twitter.com/addyosmani/status/1304676118822174721?s=20)

**Comment by bdrazen** [comment]
Aware of alternative strategies, just thought a more integrated approach (acting on the existing `dirty` parameter) would be cleaner.

Yeah, aware of moment.js. Stuck with it at the... moment unfortunately.
