### ISSUE TITLE
`helpers.setError` from `useField` called inside field async `validate` method brings inconsistent form state

### ISSUE THREAD

**Issue by chestozo** [formium/formik#3008]
## Bug report
If `helpers.setError` is called inside async field `validate` method in `useField` form state becomes inconsistent:

```
const [field, meta, helpers] = useField({
  name,
  validate: (value: string) => {
    helpers.setError(undefined) // <-- this call breaks form validity state
    return new Promise((res) => {
      setTimeout(() => res('validation error'), 1000)
    })      
  },
})
```

What I am trying to achieve is  
a field with a debounced async check:
- I want this check to be part of the Formik validation - that's why I am using a custom `validate` method that returns a `Promise`
- but I also want it to be debounced (because it involves async API call and I don't what to call API on each key press)
- I want to clear current error on each key press though (to not show outdated error while user is changing the input value)

But anyway the example I have is a more basic one.  

### Current Behavior
Steps:
- enter any value
- press Submit
- error will be shown
- press Submit again (without any changes in input)
- error will not be shown
- press Submit again (again without changes)
- error is shown again

### Expected behavior
I would expect error to be shown each time.

### Reproducible example

https://codesandbox.io/s/withformik-codesandbox-template-forked-bdmwu

### Suggested solution(s)

Either we should not use `helpers.setError()` inside field `validate` method or we need this case to be handled properly.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.2.6 |
| React            | ^16.14.0 |
| TypeScript       | any |
| Browser          | any |
| npm/Yarn         | yarn v1.22.10 |
| Operating System | Mac OS X |

**Comment by johnrom** [comment]
You can check isValidating to hide the error while validation is happening in the background. I do think it is odd that `formik.errors` can be out of sync with `formik.values`, but I don't believe Formik.errors should be unset while validation is pending, either. In the short term the best way to handle it is something like: 

```
{isValidating 
  ? "Validating..."
  : <ErrorMessage />
}
```

The issue with this is that obviously it will hide the error if any other async validations are running, not just the validation for this field. I've been thinking about way to improve the validation scheduling API to account for this, but haven't landed on anything concrete yet. So I added custom state handling to the sandbox in the form of `isSpecificFieldValidating` which might solve your problem.

Revised sandbox: https://codesandbox.io/s/withformik-codesandbox-template-forked-s0fcz?file=/index.js

**Comment by chestozo** [comment]
@johnrom thank you for your answer
while it fixes the issue I am not really happy with this approach
I am trying to rely on formik internal mechanisms as much as I can.

So my main question for now is:
is it ok to call `helpers.setError()` inside field `validate` method?
and if not - how to reset field error in a more formik way?

**Comment by johnrom** [comment]
For the specific problem you are experiencing, it is a consequence of the Context implementation of React which Formik uses. State in Formik is currently bound to a specific render. When you call helpers.setError(), you are updating the state in Formik, but the ValidateForm function Formik is calling in the background is going to test whether your validate method results in an object that is equivalent to the state.errors object it was passed to begin with. 

In v2, updates to the errors object are optimized by bailing when the next errors match the previous errors. However, there is no way to determine whether or not the errors object matches the "future" state you created by calling setError() in the validate function:

```tsx
    (values: Values = state.values) => {
      dispatch({ type: 'SET_ISVALIDATING', payload: true });
      return runAllValidations(values).then(combinedErrors => {
        if (!!isMounted.current) {
          dispatch({ type: 'SET_ISVALIDATING', payload: false });
          //
          // here, state.errors.token still equals "validation error", as does the resolved value of your `validate` Promise.
          // Formik cannot access the state where `state.errors.token = undefined` because it is "in the future".
          // 
          if (!isEqual(state.errors, combinedErrors)) {
            dispatch({ type: 'SET_ERRORS', payload: combinedErrors });
          }
        }
        return combinedErrors;
      });
    }
```

This problem doesn't exist in a v3 implementation I am working on. But there are other issues with it that must be addressed before it can be considered for v3 of Formik. This could also be solved by moving the isEqual check to the reducer, but I'm not certain at this time whether that would have other consequences. You're free to open a PR if one hasn't already, making this change which should fix your problem.

**Comment by chestozo** [comment]
@johnrom thank you again
back to one of my questions:
Is it not recommended / prohibited to call `helpers.setError()` inside field `validate` method?
If so what is the recommended way for resetting field error?

**Comment by chestozo** [comment]
BTW is this line correct?
https://github.com/formium/formik/blob/e50040abe49cf7bb46580ea46af6a2b487539830/packages/formik/src/Formik.tsx#L262

in my case `fieldRegistry.current[field].validate(value)` returns a `Promise`

**Comment by johnrom** [comment]
You can't currently setError within validate because the value of the full errors object will be stale.

I've exhausted my list of alternatives above.
