### ISSUE TITLE
Spreading object to initalValues does not take 

### ISSUE THREAD

**Issue by maartenraes** [formium/formik#3011]
### Current Behavior

![image](https://user-images.githubusercontent.com/26487384/105328876-cddbee80-5bd0-11eb-9974-8d4d37faed0b.png)

We're using an object with an unknown number of customer, for each customer there should be a checkbox rendered with the correct value. 
When spreading our `customers` object the values provided by Formik does not inherit the typing of the spread object.

### Expected behavior

Expect the typing of `customers` to be inherited by `values`.

```
var values : {
   budgetRangeStart: number;
   budgetRangeEnd: number;
   [key: string]: value;
}
```
This way we could still use `values[customer]` without having to cast it to `any`

### Reproducible example

https://codesandbox.io/s/weathered-cdn-pu788?file=/src/App.tsx

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 16.14.0
| TypeScript       |  4.2.0
| Browser          | N/A
| npm/Yarn         |  6.14.8
| Operating System | Tested on Mac and Windows

**Comment by renancleyson-dev** [comment]
After trying to declare the interface in other ways, it looks to me that the problem is with how typescript infers interfaces. In your example, I tried to declare an ```InitialValues``` variable:
```typescript
const const initialValues = {
    name: "",
    ...customers
  };
```
and this is what typescript infers:
```typescript
const initialValues: {
    name: string;
}
```
But if I specify the interface to something like ```const initialValues: { [key: string]: boolean | string }``` the compiler doesn't complain and the ```props.values``` becomes the same as the initialValues variable interface:
```typescript
  const initialValues: { [key: string]: boolean | string } = {
    name: "",
    ...customers
  };

// on form component
var values: {
    [key: string]: string | boolean;
}
```

Here's a fork of your sandbox with what I did: https://codesandbox.io/s/brave-pine-7b3x2?file=/src/App.tsx

**Comment by johnrom** [comment]
Your type cannot be consumed by TypeScript. I hopefully explain it thoroughly in code and several workarounds, here:

https://codesandbox.io/s/compassionate-feistel-wnuhh?file=/src/App.tsx
