### ISSUE TITLE
handleChange type doesn't work

### ISSUE THREAD

**Issue by olso** [formium/formik#3013]
### Current Behavior

![Screenshot 2021-01-25 at 18 33 12](https://user-images.githubusercontent.com/7975158/105742462-d2d7cf80-5f3b-11eb-8ebf-bb4a930269e8.png)

no type error with

```tsx
onChange(v: number)
```

### Expected behavior

with this commented

![Screenshot 2021-01-25 at 18 33 53](https://user-images.githubusercontent.com/7975158/105742519-e84cf980-5f3b-11eb-9016-73d16a310074.png)

we finally get type error

![Screenshot 2021-01-25 at 18 34 20](https://user-images.githubusercontent.com/7975158/105742568-f7cc4280-5f3b-11eb-9bf0-321a23e61af9.png)

### Suggested solution(s)

https://github.com/formium/formik/blob/80f9a831797429ae3c4457a47b6d8391e9d8bd2c/packages/formik/src/types.tsx#L140-L145

modify preact-like typing

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 17.0.1
| TypeScript       | 4.0.5
| Browser          | Any
| npm/Yarn         | 1.22.4
| Operating System | Big Sur

**Comment by johnrom** [comment]
You would have to pass `onChange={handleChange("lengthMeterTo")}` so it would automatically pass your value back to the field itself.

If that callback is typed with a string, that would be an issue. It should be any. You can accomplish this right now with 

```ts
const [{ onChange }] = useField<number>("lengthMeterTo");

// this onChange knows it will be a number.
<YourInput onChange={onChange} />
```

What you're requesting for handleChange is actually impossible to completely type. Even though you suggest "kind of" typing it, it doesn't type it based off of Values and name, so it is an incomplete type. We're trying to figure out how to give full typing to values and all related callbacks based on name, and have had some success with #1334 #2655 but nothing to merge just yet. Our successful tries require bleeding edge TypeScript, which we're not going to depend on just yet. Probably targeted for v3.

**Comment by olso** [comment]
Thanks for getting back to me, that solution work for me!

**Comment by johnrom** [comment]
Duplicate of #2084 at al
