### ISSUE TITLE
<Formik handleChange={handleChange}> never get's triggered

### ISSUE THREAD

**Issue by unutoiul** [formium/formik#3014]
```
const handleChange = (data)=>{
console.log(data);
}

      <Formik handleChange={handleChange}>
            {(formikProps) => {
                return (
                    <TextField
                        name="name"
                        type="string"
                        onChange={formikProps.handleChange}
                    />
                );
            }}
        </Formik>
```

the handleChange never gets triggered any idea why?

**Comment by johnrom** [comment]
There is no onChange / handleChange prop for Formik. Formik.handleChange is a function defined within the Formik component which does things like set the internal `values` and triggers validations.

**Comment by unutoiul** [comment]
Hi John,

but i can see the typescript and `handleChange={handleChange}` is available on `formik`

**Comment by johnrom** [comment]
Formik does expose a handleChange _callback_, so the way you are using it in your child components is correct: 

```tsx
                    <TextField
                        name="name"
                        type="string"
                        onChange={formikProps.handleChange}
                    />
```

However, it doesn't accept a handleChange prop to allow you to override the handleChange function, so this won't work:

```
      <Formik handleChange={handleChange}>
```

Your handleChange isn't being called because Formik is still calling its own internal handleChange, and ignoring your prop.

**Comment by lucasfiltered** [comment]
so internal handle change is overwriting the <Formik handleChange={handleChange}>?

**Comment by johnrom** [comment]
That prop doesn't exist on Formik (are you using TypeScript?)

**Comment by hatched** [comment]
I was having a similar issue and came across this issue...

I think it's less that it's defined in TS but that it doesn't complain if you provide it, although it doesn't appear to complain about any extra props.

The core issue is likely that it is included in the docs as a [prop](https://formik.org/docs/api/formik#handlechange-e-reactchangeeventany--void). So all that might be required is to remove that invalid docs entry.

**Comment by johnrom** [comment]
@hatched agreed the language is not clear. However, that documentation isn't referring to the props passed to the Formik components, but what is passed down to the props.

_Each render methods will be passed the same props:_ (lists props you are referring to)
