### ISSUE TITLE
onError callback

### ISSUE THREAD

**Issue by StErMi** [formium/formik#3018]
### Current Behavior

In my current scenario, I have an inline form with an input field and a button and I cannot show an inline error because it would result in an ugly UX. So what I would like to do is to show a Toast explaining to the user the current problem.

At the moment I have found no way to have a Formik onError callback that gives me back the `errors` prop of the form.

### Desired Behavior

Have an `onError` method to implement in the `Formik` object.

### Suggested Solution

Provide an `onError` method to implement in the `Formik` object.

### Who does this impact? Who is this for?

Beginners

### Describe alternatives you've considered

implementing `validate` method with an external `Yup` schema but it's not the best option

**Comment by SantosBright** [comment]
Hello everyone, am new to the community and open source entirely but I this is a good place to start. I think I can do this if am permitted and guided to. Thank you

**Comment by oncet** [comment]
I agree this would be useful, for example for displaying a toast message in case of error. The only workaround I can think of is using `validate` prop instead of `validationSchema`: Validate Yup schema manually and show toast if there are any errors.
