### ISSUE TITLE
Error: Cannot find module 'formik'

### ISSUE THREAD

**Issue by hsavit1** [formium/formik#3041]
### Current Behavior

Getting this error upon npm installing Formik v2.2.6 in a React Native project

```
error: Error: Unable to resolve module `react-fast-compare` from `node_modules/formik/dist/formik.cjs.production.min.js`: react-fast-compare could not be found within the project or in these directories:
  node_modules
```

upon doing the standard clearing node_modules and re-installing packages, I saw this
```
Cannot find module 'formik' or its corresponding type declarations
```

Mac, arm64, node v15.4.0

**Comment by johnrom** [comment]
@hsavit1 this is probably an issue with your environment. can you replicate it in a codesandbox?

**Comment by hsavit1** [comment]
i believe the problem i had was with my node environment, i was able to fix by using node 14 (installed via nvm). closing this issue

**Comment by Shivakumar137** [comment]
im using nextjs , everthing is working in local , but im unable to deploy . did you resolved this error
![Screenshot 2023-07-10 at 11 32 43 AM](https://github.com/jaredpalmer/formik/assets/67864487/3ba7f3bc-a66d-4754-9216-765d449b54d0)
