### ISSUE TITLE
API Docs website: "On This Page" sidebar does not update when navigating

### ISSUE THREAD

**Issue by edbrannin** [formium/formik#3043]
### Current Behavior

1. Go to https://formik.org/docs/api/fastfield
2. Click on `<Formik />` under "API Reference"

### Expected behavior

The right sidebar updates to show the new page's Table of Contents

(Note: the TOC does fix itself if I Refresh)

### Screenshots

1. 
![image](https://user-images.githubusercontent.com/121909/107800448-c968a880-6d2c-11eb-8b9e-863ca8932d57.png)
2. 
![image](https://user-images.githubusercontent.com/121909/107800502-d4bbd400-6d2c-11eb-979e-27d537d37617.png)

### Suggested solution(s)

I'm afraid I have not spent the time to see how your website works.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          | Google Chrome Version 88.0.4324.150 (Official Build) (x86_64)
| npm/Yarn         |
| Operating System | MacOS 10.15.7

**Comment by cjroebuck** [comment]
Seems like the useEffect hook that regenerates the headings isn’t being re-rendered on client side route change. Passing down the current route/path to this useEffect dependency array should cause it to rerender

**Comment by Svish** [comment]
Ran into this myself. Was confused for a while, as the links (obviously) goes nowhere.
