### ISSUE TITLE
3.0.0-next.3 => @3.0.0-next.4 - focus jumping to end of input on edit

### ISSUE THREAD

**Issue by followbl** [formium/formik#3050]
## Bug report

This is admittedly will be a half-hearted bug report - but since it's on the next/beta branch I figured you'd want it reported anyways. I've been unable to reproduce in one of your codebox sandboxes - but am experiencing within our app and have been able to narrow it down to this release below.

https://github.com/formium/formik/compare/formik@3.0.0-next.3...formik@3.0.0-next.4

I've taken a look at the source and cannot discern anything that stands out.

### Current Behavior

Type: "Brooks was here"
Move cursor to after "Brooks"
Type: "hello"

Result is: "Brooksh was hereello"

### Expected behavior

Should be: "Brookshello was here"

### Additional context

We are using the new FastField component as recommended. Will continue to try to reproduce in a sandbox and attach here if narrowed down.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by followbl** [comment]
This was a user error (me) - after refactoring all our formik fields to utilize the new apis and removing the function call inside of `<Form>` i.e. 

```tsx
<Form>{((props) => {

}))}
</Form>
```

the issue went away. Very happy with the refactor - if I could just get isDirty working, I'd be thrilled. Closing this issue

**Comment by valstu** [comment]
I noticed the same, this bug wasn't on `3.0.0-next.7` versoin but occured again on `v3.0.0-next.8`
