### ISSUE TITLE
Dirty is always false. InitialValues automatically changes with input field onchange

### ISSUE THREAD

**Issue by jleslie02** [formium/formik#3054]
### Current Behavior

I built a simple form with 2 input fields, a reset button and a submit button. I use a yup shema to validate:
`const validationSchema = Yup.object({
  job_name: Yup.string()
    .min(2, "Job's name should be at least 2 characters")
    .required('Job name is Required'),
  region: Yup.string().required('Region is required')
})`

I built custom inputfield component that uses "usefield" props in the input.
`const [fieldProps, { touched, error }] = useField({ name })`

I imported { Formik } from Formik and I built the form with it as wrapper.
Here is my configuration

` 
      initialValues={{region: '', job_name: ""}}
      validateOnChange={true}
      validationSchema={validationSchema}
      onSubmit={values => console.log("submit")}`
      
    on the submit button I added a disabled condition:
`disabled={!(isValid && dirty)}`

Upon investigation, everytime I change one of the inputs, the "initialValues" of the formik props changes as well to match the "values" props. In consequence, "dirty" seem to always be false and my submit button is always disabled.

ResetForm also doesn't reset any values in the form which makes sense because when I log "initialValues" on "onClick" of the reset button, the initialValues and the values are the same.

### Expected behavior

When I change values in either of the input the validation should occur, the "dirty" property should be true and the submit button should be enabled if "isValid" is true. InitialValues should stay the same and values should be the variable during interactions in the form. If I call resetForm() the form inputs should go back to the initialValues previously entered and the isValid should be false

### Suggested solution(s)
InitialValues should stay consistent with values initially passed and not automatically change to match the content of the "values" property onBlur or onChange.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 17.0.1
| TypeScript       | x
| Browser          | chrome
| npm/Yarn         | npm
| Operating System | mac os

**Comment by sanamumtaz** [comment]
Did you find any fix?

**Comment by orinoco** [comment]
Doesn't work here either - it's always false. 2.2.9
