### ISSUE TITLE
Submit event is swallowed when field is focused

### ISSUE THREAD

**Issue by g12i** [formium/formik#3058]
### Current Behavior

Pressing "submit" button when focused on a field swallows the submit event.

### Expected behavior

Pressing "submit" button should submit the form.

### Reproducible example

https://codesandbox.io/s/formik-blur-bug-olqym

1. Focus on "First name" field
1. Enter anything
1. Click on the "Submit" button with your mouse, **while focus is still in the text input**

Expected state:

```json
{
  "submitCount": 1,
}
```

Actual state:

```json
{
  "submitCount": 0,
}
```

### Suggested solution(s)

I think the problem originates from [`setFieldTouched`](https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L660).  See [v.1.5.8](https://github.com/formium/formik/blob/v1.5.8/src/Formik.tsx#L504) - validation was triggered after the "touched" state was updated. In 2.x.x it happens at the same time.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | ^16.12.0
| TypeScript       | N/A
| Browser          | Firefox 85.0.2 (x64)
| npm/Yarn         | N/A
| Operating System | Windows 10

**Comment by johnrom** [comment]
This is a react issue. The blur is updating your HTML which pushes the submit button outside of the area that you clicked meaning by the time you "mouseup" (this is where click happens), the button already moved.

See https://github.com/formium/formik/issues/1796#issuecomment-605685583
