### ISSUE TITLE
Unable to delete a value in form of array with useFormik hook

### ISSUE THREAD

**Issue by kanishk30** [formium/formik#3061]
### Current Behavior

I am using `useFormik` hook to render my forms. My `formik.values` looks like this - 
``` 
{
  "test": "\"8f0479549f8c4406\", \"8f0479549f8c4406\",",
  "hsn": "94042110",
  "packages": [
    {
      "sku_id_p0": "2/2",
      ....
    },
    {
      "sku_id_p1": "1/2",
       ...
    }
  ],
...
}
```

As one can see, it consists of an array as well ( `packages` ). Now, one can remove packages. I am able to achieve it by changing the form schema. Now, my schema holds 1 value ( object) only under packages array, but `formik.values.packages` still has two objects. So, when populating the values in the form, it's value is been picked from incorrect index of formik.values. 

### Expected behavior
If on removing the packages, after changing the schema, if it is possible to remove the object in formik.values.packages ? If so, then my problem will be resolved.

i tried `formik.setFieldValue(`packages${[index]}`, undefined)`. this also doesnt work. I doubt it works on array. I didnt find this clarity in docs as well.

Is there any way I can achieve this? 
Note: I cannot use `FieldArray` as it doesnt support `useFormik` hook.
### Suggested solution(s)
be able to modify the formik.values in form of an array.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |  2.1.5
| React            | 16.11.0
| TypeScript       | NA
| Browser          | Chrome 86
| npm/Yarn         | npm
| Operating System | mac

**Comment by johnrom** [comment]
@kanishk30 if you create a codesandbox reproduction you're more likely to get some help with this.

You can use Formik's components with `useFormik` if you provide a FormikProvider:

```jsx
const MyForm = () => {
  const formik = useFormik(formikProps);

  return <FormikProvider value={formik}>
    <FieldArray name="packages" />
  </Formik>
}
```
