### ISSUE TITLE
update lodash to 4.17.21

### ISSUE THREAD

**Issue by odykyi** [formium/formik#3062]
Snyk vulnerability

Please update lodash to 4.17.21

https://snyk.io/vuln/SNYK-JS-LODASH-1040724

**Comment by AvinashBalodiya** [comment]
Hi @odykyi , Is this about packages\formik\package.json ? Cause i don't see lodash inside root package.json file

**Comment by vapurrmaid** [comment]
Any progress on this? I see https://github.com/formium/formik/pull/3081 but it's getting stale.

https://github.com/advisories/GHSA-p6mc-m468-83gw
