### ISSUE TITLE
How can I put a counter up in my form and add data in the databases using reactjs ,formik and axios 

### ISSUE THREAD

**Issue by mariamahmed9** [formium/formik#3066]
I need help I have this question, can one of you give me the answer and see what is the problem in my code

I ‘m new in react js 
I put a counter up in my form I have problem to put the result of counter with the form result in the databases 
I use for my Api mongodb and spring boot 

### My environment
* version of JDK 8
* Spring boot
* Mongodb 
* Reactjs
* Formik
* Axios

Count up function 

``` 
export default function Index(props)  {
    /* Server State Handling */

    const [count, setCount] = useState(0);
    const [delay, setDelay] = useState(1000);

    useInterval(() => setCount((c) => c + 1), delay);

    useEffect(() => {
        if (delay === null) alert(`Count ${count}`);
    }, [count, delay]);

    function useInterval(callback, delay) {
        const savedCallback = useRef();

        useEffect(() => {
            savedCallback.current = callback;
        });

        useEffect(() => {
            let id;
            if (delay) {
                id = setInterval(savedCallback.current, delay);
            }
            return () => clearInterval(id);
        }, [delay]);
    }
const [serverState, setServerState] = useState();
    const handleServerResponse = (ok, msg) => {
        setServerState({ok, msg});
    };

``` 
Function of submitting data
``` 

    const handleOnSubmit = (values, actions) => {
        axios.post( "/consultations", values,
        )
            .then(response => {
                props.history.push("/listcons");
                actions.setSubmitting(false);
                actions.resetForm();
                handleServerResponse(true, "Thanks!");

                alert("Consultation enregister avec succer");

            })
            .catch(error => {
                actions.setSubmitting(false);
                handleServerResponse(false, error.response.data.error);
            });

``` 
My form with the counter up

I have problem here when I submitted my form in my databases the count value is always 0 (the initial value) how can I resolve this problem what is the problem of my code
``` 

return (
        <div className="container ">
            <div className="card-body bg-white">
            <Formik
                initialValues={{count:0,titre: ""}}
                onSubmit={handleOnSubmit}
                validationSchema={formSchema}
            >
                {({ isSubmitting }) => (

                    <Form id="fs-frm" noValidate >
   <div style={{textAlign: 'center'}}>
                            <h3>Count</h3>
                            <h2> {count}</h2>
                        </div>
                        <div className="form-group" >
                        <label htmlFor="titre">Titre</label>
                        <Field id="titre" name="titre" className="form-control" />
                        <ErrorMessage name="titre" className="errorMsg" component="p" />
                        </div>
                        <Card.Footer style={{ "textAlign": "right" }}>
                        <button type="submit" className="btn btn-primary"  disabled={isSubmitting}>
                            Submit
                        </button>
                            </Card.Footer>
                        {serverState && (
                            <p className={!serverState.ok ? "errorMsg" : ""}>
                                {serverState.msg}
                            </p>
                        )}
                    </Form>
                )}
            </Formik>
        </div>
        </div>
    );
};
``` 

example of my submit data

```
{
{count:0,
titre:jiji},
{count:0,
titre:fifa}
}

```
The counter is always equal 0

**Comment by adil-waqar** [comment]
That's because you don't have a field named "count" in your form that would update the value of your initial count value. So whenever you submit, it takes the initial value.

**Comment by johnrom** [comment]
I recommend separating the concerns all over the place here to _what is my form submitting_ and ignore the database entirely.

The problem is that your handleSubmit callback has a reference to `count`, which at the instant that the callback is created is 0. When you call handleSubmit later, it still uses this callback.

You can handle this 2 ways:

- use a ref for `count` -- but then you can't use it to render or use effects
- update your handleSubmit callback every time count updates. you'll have to test if this causes rendering issues for you because it will cause the Formik component to rerender
- or you can combined them using a stable ref for handleSubmit which has an internal callback which is updated whenever count updates, see [useEventCallback](https://reactjs.org/docs/hooks-faq.html#how-to-read-an-often-changing-value-from-usecallback)

Try them out, whichever one you use is up to you. I'd probably update a ref + setState for count at the same time, with the knowledge that render could be out of sync for a few hundred milliseconds.

**Comment by mariamahmed9** [comment]
@johnrom I try it in a sandbox but the same things look at my code please https://codesandbox.io/s/lucid-rgb-tj89d?file=/src/index.js

**Comment by johnrom** [comment]
@mariamahmed9 you've fixed the handleSubmit issue you were having previously, but `values.counter` will never have your update value if you do not call it in Formik. I'd recommend removing counter from `values` if you plan to handle it completely outside of user input, or move Counter to a child component of Formik and have it run `setFieldValue('counter', newNumber)` on every effect (this is a bit more expensive than handling it outside of Formik).

You can always combined the values later in your onSubmit function like `{...values, counter}` to get a combined object.
