### ISSUE TITLE
Formik loses it's state on form submission

### ISSUE THREAD

**Issue by adil-waqar** [formium/formik#3068]
### Current Behavior

When I submit my form, I show the user a loading spinner. After the submission, my `values` get reset to the `initialValues`.

### Expected behavior

I expected my `values` to retain their value as filled by the user even after form submission.

### Reproducible example

[This](https://codesandbox.io/s/snowy-bush-trobt?file=/src/App.js) is the link to my sandbox. Add your first and last name and hit submit. You'll see your fields empty after submission.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.2.0
| React            | 16.5.0
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by johnrom** [comment]
This isn't a bug. You've unmounted Formik by doing:

```
if (loading) return <div>Loading...</div>;
```

You can add an overlay with a z-index higher than your form like this:

```
  return (
    <div className="App">
      {loading && <div className="overlay">Loading...</div>}
      <div className="form-wrapper">
        <h2>Form</h2>
        <Formik />
      </div>
    </div>
  );
```

Or you can always render both, and adjust App's classes based on the state of the form, like, 

```
// I use the common package `classnames` here, but you can also do it manually
return <div className={classNames("App", loading && "App--loading")} />

// css, this will also disable user input
.App--loading form {
  display: none;
}
```

**Comment by adil-waqar** [comment]
> This isn't a bug. You've unmounted Formik by doing:
> 
> ```
> if (loading) return <div>Loading...</div>;
> ```
> 
> You can add an overlay with a z-index higher than your form like this:
> 
> ```
>   return (
>     <div className="App">
>       {loading && <div className="overlay">Loading...</div>}
>       <div className="form-wrapper">
>         <h2>Form</h2>
>         <Formik />
>       </div>
>     </div>
>   );
> 
> // css for example, but you'll def need more than this
> .overlay { position: relative; /* or absolute, or fixed */ z-index: 5; }
> form { position: relative; z-index: 1; }
> ```
> 
> Or you can always render both, and adjust App's classes based on the state of the form, like,
> 
> ```
> // I use the common package `classnames` here, but you can also do it manually
> return <div className={classNames("App", loading && "App--loading")} />
> 
> // css, this will also disable user input
> .App--loading form {
>   display: none;
> }
> ```

Oh I see! I kind of also thought about it. Thank you for the explanation!
