### ISSUE TITLE
Getting "Uncaught (in promise)" when validating file format with Yup

### ISSUE THREAD

**Issue by WaqqarSuleman** [formium/formik#3069]
### When intentionally browsing a file of format other than the specified one, I get following error in the browser's console:
`Uncaught (in promise) Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0, …}`

![image](https://user-images.githubusercontent.com/74898820/109349878-9f6ec480-789c-11eb-9c81-be9c700a22c2.png)

I cannot figure out where this error is originating from.
Here a piece of my code:
**Component:**
```
const MAX_RES = 3840 * 2160;
const MAX_FILE_SIZE = 5242880;
const SUPPORTED_IMAGE_TYPES = ['image/png', 'image/jpeg'];
const initialValues = { name: '', image: '' };
const validationSchema = Yup.object({
		name: Yup.string().trim().required('Banner Title is required'),
		image: Yup.mixed()
			.test('imageType', 'Image type is not supported', value =>
				checkFileType(value, SUPPORTED_IMAGE_TYPES)
			)
			.test('imageSize', `Image cannot be more than ${convertBytes(MAX_FILE_SIZE)}`, value =>
				checkFileSize(value, MAX_FILE_SIZE)
			)
			.test('imageResolution', 'Image resolution cannot be more than 4K', value =>
				checkImageResolution(value, MAX_RES)
			)
			.required('Banner Image is required'),
	});
```

**Formik Input Type File Control:**
```
const File = props => {
	const [field, meta] = useField(props);
	const {
		label,
		name,
		required,
		className,
		containerClassName,
		disabled,
		labelClassName,
		multiple,
		accept,
		...rest
	} = props;

	return (
		<div className={containerClassName}>
			<Field id={name} name={name} {...rest}>
				{({ form }) => {
					const { setFieldValue, setFieldTouched } = form;
					return (
						<input
							{...rest}
							type='file'
							className={meta.touched && meta.error ? `${className} input-error` : `${className}`}
							onChange={event => setFieldValue(name, event.target.files[0], true)}
							onBlur={() => setFieldTouched(name)}
							multiple={multiple}
							accept={accept}
							disabled={disabled}
						/>
					);
				}}
			</Field>
			{!meta.error && field.value && typeof field.value === 'object' && (
				<small className='form-text text-muted'>
					<strong>Selected File: </strong>
					{field.value.name.slice(0, 20) +
						'.. ' +
						field.value.name.slice(field.value.name.lastIndexOf('.'))}
				</small>
			)}
			{label && (
				<label
					htmlFor={name}
					className={`${labelClassName} ${meta.touched && meta.error ? 'label-error' : ''}`}
				>
					{label}
					{required && <span className='text-danger'>*</span>}
				</label>
			)}
			<ErrorMessage name={name} component={TextError} />
		</div>
	);
};

File.defaultProps = {
	containerClassName: 'form-group custom-file',
	className: 'custom-file-input',
	labelClassName: 'custom-file-label',
	multiple: false,
	accept: 'image/png, image/jpeg',
};
```

**Utility Functions:**
```
export const checkFileSize = (fileObject, maxSize) => {
	if (fileObject && fileObject instanceof File) {
		return fileObject.size <= maxSize;
	}
	return true;
};

export const checkImageResolution = async (fileObject, maxRes) => {
	if (fileObject && fileObject instanceof File) {
		const { width, height } = await new Promise((resolve, reject) => {
			const img = new Image();
			img.onload = () => resolve({ width: img.width, height: img.height });
			img.onerror = reject;
			img.src = URL.createObjectURL(fileObject);
		});
		URL.revokeObjectURL(fileObject);
		return width * height <= maxRes;
	}
	return true;
};

export const checkFileType = (fileObject, supportedTypes) => {
	if (fileObject && fileObject instanceof File) {
		return supportedTypes.includes(fileObject.type);
	}
	return true;
};
```
### CRA App running on Linux Mint 20.1

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 17.0.1
| TypeScript       | -
| Browser          | Chrome
| npm/Yarn         | yarn
| Operating System | Linux Mint 20.1

**Comment by johnrom** [comment]
Did you try your logic outside of Yup? What happens when you apply the following with a non-image URL?

```
			const img = new Image();
			img.onload = () => resolve({ width: img.width, height: img.height });
			img.onerror = reject;
			img.src = URL.createObjectURL(fileObject);
```

Without a codesandbox it's basically impossible to guess what your issue is. But if I had to, I'd guess the browser is throwing an error on the Image object, which you'd have to prevent with a `try {} catch { reject() }` block

**Comment by johnrom** [comment]
Could be even simpler than that, when you reject the Promise, you're creating an error. Without doing Promise.catch() that error is not suppressed and the exception bubbles to as an uncaught exception up through your code.

**Comment by johnrom** [comment]
If you do catch, width and height will be undefined and `undefined * undefined` will probably also throw an error.

**Comment by WaqqarSuleman** [comment]
@johnrom I thought the` test()` functions in yup would run in a serial order so if the file check failed it would just break from there. But eveidently it is not the case. Anyway, I took your advice and wrapped that piece of erroneous code with `try/catch` and now it works as expected.
Thanks a lot for your time.

**PS:** I need help with preventing formik _onBlur validation when the file browser opens_. Currently if I open the file browser, I immediately get the **"required"** error. I do want to show the error but only if the _user does not choose any file (cancels the file browser)._ 
Can you please tell me any workaround for this situation?
