### ISSUE TITLE
Docs code sandbox examples not loading on live site

### ISSUE THREAD

**Issue by gregkepler** [formium/formik#3120]
### Current Behavior

On the docs website, the sandbox examples fail to load. For every example (such as https://formik.org/docs/examples/basic), it shows "Not found. We could not find the sandbox you're looking for."

![image](https://user-images.githubusercontent.com/165945/112502538-8b659800-8d60-11eb-9f45-7af71f2637a4.png)

Dev tools shows the error `Failed to load resource: the server responded with a status of 422 ()`

**Comment by gregkepler** [comment]
Looks to be working again

**Comment by dskline** [comment]
Not working again 🙁
