### ISSUE TITLE
Double click on checkbox/radios

### ISSUE THREAD

**Issue by drfbwilliams** [formium/formik#3158]
Hi,

When implementing a checkbox or radio - the resulting element requires a double click to check/uncheck the element. This is seen in both radios and checkboxes.

I've looked at so much documentation and tried to find others with the same issues - unfortunately I've just run out of time to resolve it. It is either something very simple that I am doing wrong (most likely) or it is a defect.

[https://codesandbox.io/s/formik-issue-double-check-s13i5?file=/src/form.tsx](url)

If anyone can take a quick look at the attached sandbox, that would be very much appreciated.

If it is a defect, any ideas or work around would also be great.

Many thanks

**Comment by tanmayv** [comment]
Remove `event.preventDefault` from your handleOnChange method. Then it should work fine.

**Comment by drfbwilliams** [comment]
@tanmayv thank you very much for your response - absolutely correct. I am still unsure why the prevent would cause a double click, but hey, I am pleased to have learnt something new.

Many thanks.
