### ISSUE TITLE
Standard HTML Form submit

### ISSUE THREAD

**Issue by sven5** [formium/formik#3182]
Hi,

Does Formik support a standard HTML form submit?
Please don't ask why we need this. We just have to use it in order to submit form data to another site.
We cannot use xhr here because of CORS issues. We cannot control CORS settings on the server.

example:
```
<form action="someurl" method="POST">
</form>
```

I couldn't find a way how to do this.
Thanks a lot

**Comment by johnrom** [comment]
@sven5 you can do this a number of ways, like:

### submit via ref

```
const formRef = React.useRef(null);

return <Formik onSubmit={() => formRef.submit() }><Form ref={formRef} /></Formik>
```

### manually implement Formik's submit fn

return <Formik>
  {formik => (
    <Form onSubmit={(event) => {
      formik.validateForm().then(errors => {
        if (!Object.keys(errors).some(key => !!errors[key])) { 
          event.target.submit();
        }
      });
  )}
</Formik>
```

the API could be a little better here when building the submit manually, but I think the first option is pretty straightforward

**Comment by sven5** [comment]
Hi @johnrom 

Thanks for support. 
I tried it, with no luck. Error: 
```
Warning: An unhandled error was caught from submitForm()
TypeError: formRef.submit is not a function
```

**Comment by johnrom** [comment]
formRef is a ref, so it should be:

```
formRef.current.submit()
```

if there is still an issue, please provide a codesandbox reproduction as it's nearly impossible for me to guess!

**Comment by sven5** [comment]
Correct, it's working now.
Thanks a lot @johnrom
