### ISSUE TITLE
race condition on validation

### ISSUE THREAD

**Issue by artola** [formium/formik#3199]
### Current Behavior

Validation is not working properly when used `validateOnMount` and firing the change asap. It affects unit testing, requiring some workaround.

### Expected behavior

The behaviour using `validateOnMount=true` should be equivalent to `validateOnMount=false`.

### Reproducible example

Here a test example written with React Testing Library:

```js
import {Field, Form, Formik} from 'formik';
import React from 'react';

import {fireEvent, render, screen, waitFor} from '@testing-library/react';

const Example = () => (
  <Formik
    initialValues={{query: ''}}
    validateOnMount={true}
    validate={(values) => (values.query ? {} : {query: 'Required'})}
  >
    {({isValid, isValidating}) => (
      <Form>
        <Field name="query" data-testid="query" />
        <button data-testid="submit" disabled={isValidating || !isValid}>
          search
        </button>
      </Form>
    )}
  </Formik>
);

it('should enable submit button (FAILS)', async () => {
  render(<Example />);

  const query = screen.getByTestId('query');
  fireEvent.change(query, {target: {name: 'query', value: 'foo'}});

  await waitFor(() => {
    const button = screen.getByTestId('submit');
    expect(button.hasAttribute('disabled')).toBe(false);
  });
});

it('should enable submit button (WORKS)', async () => {
  render(<Example />);

  setImmediate(() => { //<== workaround
    const query = screen.getByTestId('query');
    fireEvent.change(query, {target: {name: 'query', value: 'foo'}});
  });

  await waitFor(() => {
    const button = screen.getByTestId('submit');
    expect(button.hasAttribute('disabled')).toBe(false);
  });
});
```

### Suggested solution(s)

The code in the example that is failing triggers the initial validation for `{query: ''}` and soon after for the "typed" value `{query: 'foo'}`. The initial validation will trigger a change in the store for `{errors: {query: 'Required'}}` but when the second validation evaluates the following line, it still finds `{errors: {}}` therefore it is not firing the `dispatch`.

https://github.com/formium/formik/blob/26e4e8d0ddbdce13aba05e13e56ff70f1956a64a/packages/formik/src/Formik.tsx#L328

I can not understand why this happens, because if I just remove the `if (!isEqual(state.errors, combinedErrors)) {` and `dispatch` the `SET_ERRORS` the reducer still performs the "same" assertion and it detects the change properly.
Therefore, it seems some kind of "race" or "batch" happening inside the reducer.

https://github.com/formium/formik/blob/26e4e8d0ddbdce13aba05e13e56ff70f1956a64a/packages/formik/src/Formik.tsx#L65

I would like to recommend to remove the extra check inside `validateFormWithHighPriority` and leave the reducer to decide whether to update or not `return state;` (no change).

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.6
| React            | 17.0.2
| TypeScript       |
| Browser          |
| npm/Yarn         | 1.22.10
| Operating System | OSX 11.3.1

**Comment by artola** [comment]
@jaredpalmer This `if (!isEqual(state.errors, combinedErrors))` in `validateFormWithHighPriority` was reintroduced when you reverted:
https://github.com/formium/formik/blame/26e4e8d0ddbdce13aba05e13e56ff70f1956a64a/packages/formik/src/Formik.tsx#L328

BUT mainly becomes redundant since later on was introduced the "Avoid unnecessary re-renders by comparing errors to previous errors" in the reducer (this improvement should have removed such `if` in `validateFormWithHighPriority`).

https://github.com/formium/formik/blame/26e4e8d0ddbdce13aba05e13e56ff70f1956a64a/packages/formik/src/Formik.tsx#L65

**Comment by jaredpalmer** [comment]
Looks good. Thanks for the writeup.
