### ISSUE TITLE
How does Formik show error on untouched fields?

### ISSUE THREAD

**Issue by SevenOutman** [formium/formik#3263]
### Discussed in https://github.com/formium/formik/discussions/3249

<div type='discussions-op-text'>

<sup>Originally posted by **SevenOutman** June 17, 2021</sup>
### The use case

It's a common use case to validate a required field and show an error if it's not filled.

### The problem

In this case the field is left untouched, thus the `<ErrorMessage>` shall not show according to its implementation (as shown below):
https://github.com/formium/formik/blob/903c1101240632c84fa36c8991ea9fd03b25f1cf/packages/formik/src/ErrorMessage.tsx#L39-L51

### The question

What is the correct/recommended way of showing errors on required fields when it's not touched? My current approach is setting `initialTouched` to `true` on every required field. But it feels so weird. :(</div>

**Comment by CarolynWebster** [comment]
It's not cute, but I just use the Formik `errors` and check the path for an error using [json-ptr](https://github.com/flitbit/json-ptr) aliased as `jsonpointer`. I couldn't make it work using the `ErrorMessage` component without doing what you suggested - setting everything to touched, which was a bummer. Your approach is simpler, but felt like it was worth sharing if setting all to touched was not an option. 

```
{errors && jsonpointer.has(errors, convertDotPathToJsonPointer(path)) && (
    <div className="field-error">
        {jsonpointer.get(errors, convertDotPathToJsonPointer(path)) as Record<string, any>}
    </div>
)}
```

Here is the helper function for converting the path to a json pointer
```
export const convertDotPathToJsonPointer = (dotPath: string): string => {
    const regex = /\./g
    return `/${dotPath.replace(regex, "/")}`
}
```

I made a `FieldWrapper` component that holds the field, a header label, and the error message, so if/when the error message is fixed, I will just have to update it here. 
```
const FieldWrapper = (props: wrapperProps) => {
    const { label, path, depth, field, errors } = props
    return (
        <>
            <div className={`section-depth-${depth}`}>
                <label>{label}</label>
                <div>{field}</div>
                {errors && jsonpointer.has(errors, convertDotPathToJsonPointer(path)) && (
                    <div className="tcomb-file-attachment-uploader-error">
                        {jsonpointer.get(errors, convertDotPathToJsonPointer(path)) as Record<string, any>}
                    </div>
                )}
            </div>
        </>
    )
}
```
