### ISSUE TITLE
There is a bug when using <ErrorMessage />

### ISSUE THREAD

**Issue by yogain123** [formium/formik#3267]
## Bug report

When I am using `<ErrorMessage />` for showing Error like below:
![Screen Shot 2021-07-03 at 12 28 03 AM](https://user-images.githubusercontent.com/14003377/124317946-91f08080-db95-11eb-9152-6f2ccefce976.png)

I am getting this error

why??

![Screen Shot 2021-07-03 at 12 22 20 AM](https://user-images.githubusercontent.com/14003377/124318078-bc423e00-db95-11eb-9a47-c827e8a827aa.png)

**Comment by johnrom** [comment]
It's hard to tell without a codesandbox reproduction, but I'd guess you're using useFormik without FormikProvider.

The Formik component provides a React Context like `<FormikProvider value={formik} />`, if you use useFormik but still want to use helper components you should pass the return value to FormikProvider so the components can access it via context.

**Comment by yogain123** [comment]
Ohh yes. You are correct. Thanks for the help!!
Closing issue.
