### ISSUE TITLE
Formik "FIELD" causes TypeError: formik.getFieldProps is not a function error in Next.js

### ISSUE THREAD

**Issue by raleigh9123** [formium/formik#3327]
## My Code

```
import { Field, useFormik } from 'formik';

export default function LoginForm () {
  const loginForm = useFormik({
    initialValues: {
      email: '',
      password: '',
      remember: false
    },
    onSubmit: async ( values ) => {
      console.log(values);
    },
  })
  return (
    <form onSubmit={loginForm.handleSubmit}>

      {/* Email Input */}
      <label htmlFor="email">Email
        <input
          id="email"
          name="email"
          type="password"
          onChange={loginForm.handleChange}
          value={loginForm.values.email}
        />
      </label>

      {/* Password Input */}
      <label htmlFor="password">Password
        <input
          id="password"
          name="password"
          type="password"
          onChange={loginForm.handleChange}
          value={loginForm.values.password}
        />
      </label>

      <Field
        id="remember-me"
        type="checkbox"
        name="remember"
      />
      <label
        htmlFor="remember-me"
      >
        Remember me
      </label>

      
      <button type="submit">
          Submit
      </button>
    </form>
  )
}
```

## Bug report
<img width="979" alt="Screen Shot 2021-08-31 at 12 13 19 AM" src="https://user-images.githubusercontent.com/41349450/131459311-5f4e7cce-2e0f-447e-942c-46478e6921f3.png">

### Current Behavior
I am using Formik within a Next.js App. Everything has been great.

I have a very simple login form and want to add a checkbox as a "Remember Me" field. I added a new input `checkbox` using Formik's `Field` component and received the following bug from Next.js above.

I'm not sure where this error is coming from? But the form is almost straight out of the Formik tutorial and docs. I do not receive this error with other html inputs. Only with Formik's `Field` input.

### Expected behavior
Adding the `Field` component from Formik should run as expected. I'm not sure where to start looking for a solution here since simply adding the `Field` component seems to be breaking my Next.js build. 

I have multiple Formik forms on my app so far, and each of them has worked without any issues. I got the above error only after adding the `Field` component from the Formik package.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.9
| React            | 17.0.2
| Next.js.         | 11.1

**Comment by johnrom** [comment]
If you use `useFormik` instead of `Formik` or `withFormik`, you'll have to add `FormikProvider` with the result of useFormik:

```tsx
const formik = useFormik();

// do other stuff with `formik` as necessary

return <FormikProvider value={formik}>
  <Form>
    <Field />
  </Form>
</FormikProvider>
```

**Comment by raleigh9123** [comment]
Oh nice! I didn't realize they had a class-based version of the component. The tutorial starts right of with a hook and I didn't realize there was another way to write the Formik form (would have noticed if I looked more closely at the checkbox example though!!) Also seeing how this could be used in more complex forms. 

I do like the syntax of the useFormik() hook though. Otherwise, no issues after running this way in my own project. At some point, I might rewrite my solution with the class-based component here, but for now the solution is here on [Formik's documentation](https://formik.org/docs/api/formik).
