### ISSUE TITLE
Pass field as prop to FieldArray

### ISSUE THREAD

**Issue by rovansteen** [formium/formik#346]
## Bug, Feature, or Question?
Question / Feature

## Current Behavior
Currently the `<FieldArray />` gets only the `arrayHelpers` and `form` passed in as prop. Is there any reason it does not get the field property passed in? Now I have to get the values 'manually' from the form prop. 

## Desired Behavior
It would be nice to get at least the `value` from the field (based on the field name).

## Suggested Solutions
Passing a similar `field` prop as the `<Field />` component receives, except for the `onChange` and `onBlur`.
 
- Formik Version:  0.11.0-beta.1
- OS: Mac OS High Sierra
- Node Version: 9.3.0
- Package Manager and version: 1.3.2

**Comment by charlax** [comment]
+1

It would be nice also for extra props to be passed down the component:

See https://codesandbox.io/s/6y8q0ql34z

```jsx
<FieldArray
            name="categoryIds"
            shouldBePassed="hello"
            component={props => {
              console.log(props)
              return null
    }
/>
```

In the current state, `shouldBePassed` will not be passed down to the rendered component.

**Comment by dmlukichev** [comment]
Also got confused by the fact that rest props are not passed to `<FieldArray/>` component. It would be nice to allow it.

At the same time workaround will look like this:
```
<FieldArray
    name="categoryIds"
    render={props => (
        <Component 
            {...props} 
            shouldBePassed="hello"
        />
    )
/>
```

**Comment by jaredpalmer** [comment]
Update: plan is to likely deprecated FieldArray and move these manipulations into core

**Comment by Tsudhishnair** [comment]
How can I pass custom props to the child component in fieldarray now?

**Comment by maddhruv** [comment]
Closing as `stale`
