### ISSUE TITLE
Docs Homepage Design

### ISSUE THREAD

**Issue by jaredpalmer** [formium/formik#662]
This is a thread to discuss what the docs homepage should look like. I have some ideas, but they are super plain. Ideally,  design conveys "oh fuck, this looks epic" to the viewer. I'm open to modifying the logo if the proposed design/brand is cohesive enough. Otherwise, the current logo is an optical illusion inspired by M.C. Escher, it would be cool to somehow incorporate that as a motif throughout the homepage. 

### Some ideas

- Epic SVG animation that presents the logo in a unique way
- SVG animation that morphs / zooms the Formik logo into inputs as the user scrolls through different steps of a tutorial (would maybe require scroll-jacking)

### Cool Fonts:
- Colfax
- Circular (currently used in the logo)
- Graphik

## Next Steps

- Post a link / screenshot / gif of your designs in this thread. Person with the selected design will get mentioned in README, formik laptop stickers, and Formik t-shirt when 1.0 drops.
- Add reactions to designs you like / dislike. _Be nice_

**Comment by jaredpalmer** [comment]
![image](https://user-images.githubusercontent.com/4060187/40684645-de55c7e8-635f-11e8-98a9-7040f5b7762f.png)

**Comment by jaredpalmer** [comment]
![image](https://user-images.githubusercontent.com/4060187/40684673-f31f3ea2-635f-11e8-840e-b79ee35421c8.png)

**Comment by jaredpalmer** [comment]
![image](https://user-images.githubusercontent.com/4060187/40684684-fc529a32-635f-11e8-9380-c0daf300c428.png)

**Comment by HPieters** [comment]
Nice idea! So I allowed myself 2 hours to come up with a design, this is what I got so far. Needs some work on colors, details and content but for now I hope it will keep the discussion going.

![formik-landing](https://user-images.githubusercontent.com/2362116/41159872-461d5d5c-6b2e-11e8-94d7-90d2587f7c2f.png)

**Comment by jaredpalmer** [comment]
@HPieters so cool! Love copy and the getting started section
