### ISSUE TITLE
Fields not *always* marked as touched

### ISSUE THREAD

**Issue by Andreyco** [formium/formik#738]
## Current Behavior
Only fields whose values are provided as part of `initialValues` are marked as touched when form is submitted.

## Steps to Reproduce
Set `initialValues={{}}` and submit form. Dump `state.touched` and see it empty.

## Expected behavior
All existing field should be marked as touched, even if they are not specified on `initialValues`

## Suggested solution(s)
Thanks to current API (`registerField` and `unregisterField`) we have map of mounted fields. Work with this data, instead of what is provided in `state.values`

## Additional context

**CodeSandbox Link**:
https://codesandbox.io/s/vqjmnkvjn7
---

- Formik Version: all

**Comment by jaredpalmer** [comment]
I think this makes sense. Go for it.

**Comment by Andreyco** [comment]
On it...

**Comment by latviancoder** [comment]
This could be incredibly helpful for the project we are currently working on. Right now we have to manually create "empty objects" and it's a very tedious task, because there are many large and highly dynamic forms.

**Comment by houkanshan** [comment]
Will this also fix the "uncontrolled to controlled error"? In your [CodeSandbox demo](https://codesandbox.io/s/vqjmnkvjn7), if I type some thing in the input, this familiar error will appear:

![image](https://user-images.githubusercontent.com/657962/43257717-1b45da8c-9103-11e8-8736-aa4d1cf91e45.png)

**Comment by latviancoder** [comment]
@houkanshan thank you for this comment, helped me a lot!

**Comment by weyert** [comment]
Hmm, interesting @houkanshan wondering where do you get `touched` and `error` from in your code snippet?

**Comment by houkanshan** [comment]
@weyert updated my code. it's
```js
      const error = getIn(form.errors, name);
      const touch = getIn(form.touched, name);
```

**Comment by weyert** [comment]
Of course, had to be late yesterday :D

**Comment by latviancoder** [comment]
Is there any progress on this?

**Comment by Davidmycodeguy** [comment]
How is the progress on this?

**Comment by releaf** [comment]
I was able to wok around this by adding an onKeyUp event to the input I want to be validated as having been touched like this:
` onKeyUp={() => setFieldTouched(`${name}`, true)}`
https://codesandbox.io/s/5y2vlw594l

**Comment by saschb2b** [comment]
I also noticed this problem when you want to track an input where the onBlur should not be the only result of focused. Like a checkbox.
I had to use the onFocus handler with a timeout to prevent immediate error popping up.
```
<CheckBox
            error={errors.agb && touched.agb}
            onFocus={() => setTimeout(() => setFieldTouched('agb', true), 100)}
```

**Comment by chhornponleu** [comment]
The work around above seem to work with individual field. I having another issue when user press submit button without touching any field, the `touched` param is empty `{}`.

**Comment by maddhruv** [comment]
Closing due to long inactivity
