### ISSUE TITLE
 FieldArray's unshift action does not update touched state correctly

### ISSUE THREAD

**Issue by rrjohnson85** [formium/formik#788]
## Current Behavior
While using the FieldArray's `unshift` action, the array is shifted and the value is correctly added to the beginning of the array; however, the `touched` state is not shifted along with the values. 

## Steps to Reproduce

- Create a field array of inputs
- `unshift` an entry onto the array
- touch the input
- `unshift` another entry onto the array

RESULT:  touched will be true for index zero, but not for index one.

## Expected behavior
I would expect that the input at index zero would be untouched, while the input at index one would be touched.

## Suggested solution(s)
It seems passing true for `alterTouched` to `updateArrayField` solves the issue.  It probably makes sense to do the same for the `alterErrors`.

**CodeSandbox Link**:
https://codesandbox.io/s/qk9rpovn76

---

- Formik Version:  1.0.1
- React Version:  16.4.1
- TypeScript Version:  N/A 
- Browser and Version:  Chrome (v67.0.3396.99)
- OS:  High Sierra
- Node Version: v8.9.3
- Package Manager and Version:  Yarn (v1.7.0) & npm (v6.0.1)

**Comment by rrjohnson85** [comment]
This is likely still an issue...

**Comment by nicholascm90** [comment]
@rrjohnson85 I upgraded Formik in this pen, https://codesandbox.io/s/9j69v3pkyy and wasn't seeing the same behavior where touched gets out of sync with the list of fields. Seems this was resolved.
