### ISSUE TITLE
Nested within nested for FieldArray got error when reached 3rd items

### ISSUE THREAD

**Issue by eldyvoon** [formium/formik#987]
## Current Behavior
Recorded demo, https://www.useloom.com/share/fb484e885247410b9b583b4535d9b716

**CodeSandbox Link**:
https://codesandbox.io/s/23l22z9kwr

**Comment by Saifadin** [comment]
Fixed it for you: [https://codesandbox.io/s/71x5w34z70](https://codesandbox.io/s/71x5w34z70)

Seems like you were pushing the `index` to the main FieldArray. That lead to the main array looking like this:
```
[
  {name: '', games: ['']},
  0,
  1
]
```
Instead it should be like this:
```
<button type="button" onClick={() => arrayHelpers.push({ name: '', games: [''] })}>
  +
</button>
```
Now whenever you add a question the array will be like this:
```
[
  {name: '', games: ['']},
  {name: '', games: ['']},
  {name: '', games: ['']},
]
```

**Comment by maddhruv** [comment]
Closing due to long inactivity
