### ISSUE TITLE
Pushing Arrays of Object in FieldArray Helpers

### ISSUE THREAD

**Issue by ghost** [formium/formik#988]
Any suggestion how can I push arrays of object?

**Comment by Saifadin** [comment]
A little bit more detail would help us help you :)

**Comment by jericbas** [comment]
Check this link: https://codesandbox.io/s/4k92x4vw0

The default rows have 5 field array. Upon clicking the Add button i need to add 2 more rows.
I tried to `push` an object twice but it only adds 1 row.
```                   
 onClick={() => { 
push({templateData}); 
push({templateData});
}}
```

**Comment by Saifadin** [comment]
It seems to me like the two don't happen synchronously and so one of them gets swallowed basically. It worked for me after I added async/await to it. See here: [https://codesandbox.io/s/n9n43p3pj0](https://codesandbox.io/s/n9n43p3pj0)

**Comment by jericbas** [comment]
I see. 
Actually, in my actual project, i need to add 10 rows.  It would be great if I can push an array of objects . Instead of  adding ```push``` X times

example 
``` push([{ product: "books" }, { product: "clothes" }] , { product: "clothes" }], { product: "clothes" }])```

Thanks @Saifadin

**Comment by Saifadin** [comment]
Ahh okay, but you could also do something like this:

```
onClick={() => {
  const countArray = new Array(10);
  countArray.forEach(() => push({ product: '', price: '' }));
}}
```

You create an Array with length 10 and then you loop through them and you will create for each element a `push`.

**Comment by mauscoelho** [comment]
Worked for me after I added `async/await` from the beginning
```js
onChange={async e => 
```
