### ISSUE TITLE
Using validateYupSchema and yupToFormErrors internal utils in the app

### ISSUE THREAD

**Issue by rodgobbi** [formium/formik#989]
Hi!
First, congratulations and thank you for this amazing lib! It helps me a lot and I really enjoyed using it.
So, I'll explain first my use case:
I had a form with a separated time input and day of the year input, each one had a peculiar data format to input. I made a Yup schema for each, and as a last step of the validation of the form, if the inputs were correct, I had to put the day and time together to validate if the date was in the future.
I saw in the source code the utils functions `validateYupSchema` and `yupToFormErrors` and leveraged them in the same way they were used in the `Formik` component, making two steps of validation in the form of my use case.
The question is, is it OK to use these internal functions? (Although they are exported from the package)
And more, if it's fine to use, as a recommendation, would it be good to have a section in the documentation for them?

**Comment by rodgobbi** [comment]
@Grsmto Yep, due to it being used internally and not part of the official exposed API so to speak, it can have breaking changes without passing through a changelog. But if it's ok to use it'd be helpful to document it, it's useful and already implemented.

**Comment by arthur-chan-leapyear** [comment]
My team was wondering the same thing. Sometimes you have a form where you want to show different options, or validate things differently, depending on what the user has entered before. For example, if they selected that they are a pastafarian, then you want to make sure that they don't accidentally select anything that doesn't involve lasagna (hypothetically).
